### ISSUE TITLE
iOS打包失败的issues汇总

### ISSUE THREAD

**Issue by yixiangboy** [didi/DoraemonKit#102]
https://github.com/didi/DoraemonKit/issues/96 iOS打出的企业包安装不了
https://github.com/didi/DoraemonKit/issues/93 fastlane 导包出来 verify bitcode in DoraemonLoadAnalyze.framework 报错
https://github.com/didi/DoraemonKit/issues/90 ios 打包报错
https://github.com/didi/DoraemonKit/issues/67 fastlane 打包导出会有问题
https://github.com/didi/DoraemonKit/issues/40 包含 DoraemonLoadAnalyze.framework 后无法在默认的 `ENABLE_BITCODE = YES` 模式下正常 Archive
https://github.com/didi/DoraemonKit/issues/38 包含 DoraemonLoadAnalyze.framework 后无法正常 Archive

**Comment by Jinkeycode** [comment]
#ifdef DEBUG
#import <DoraemonKit/DoraemonManager.h>
#endif

**Comment by Grayson2019** [comment]
请问只能在DEBUG使用吗，我想在企业包使用
