### ISSUE TITLE
【DoKit生态场景】-Android V3.6.8版本下载不了

### ISSUE THREAD

**Issue by weinierfei** [didi/DoraemonKit#1028]
看到Android新发布了3.6.8版本,但是'io.github.didi.dokit:dokitx-plugin:3.6.8'引用不了;能更新下文档吗?

**Comment by weinierfei** [comment]
@RealOnlyone 大佬给看看,谢谢

**Comment by awq14789** [comment]
还没发布到maven仓库上面，肯定下载不了

**Comment by weinierfei** [comment]
> 还没发布到maven仓库上面，肯定下载不了

我看都release了都

**Comment by weinierfei** [comment]
> > 还没发布到maven仓库上面，肯定下载不了
> 
> 我看都release了都

确实没发布，只是release了个版本

**Comment by RealOnlyone** [comment]
是的在maven上只发布了 3.6.2，3.6.8 只在内网发布了，为了记录打了个release包。最新的今天发布了3.7.1
