### ISSUE TITLE
希望iOS支持直接使用Framework

### ISSUE THREAD

**Issue by sdbaobaodww** [didi/DoraemonKit#104]
因公司项目中未使用Pods，暂不想为使用DoraemonKit而增加Pods，希望能提供一个Framework直接使用。

**Comment by yixiangboy** [comment]
推荐使用 https://github.com/CocoaPods/cocoapods-packager 自己打包。很简单方便。

**Comment by yixiangboy** [comment]
1.1.9版本工程中 也包含了 framework，你也可以自行下载接入

**Comment by Cyandnow** [comment]
> 推荐使用 https://github.com/CocoaPods/cocoapods-packager 自己打包。很简单方便。

您好, 我在使用 pod package 打包后 使用时会产生如下错误

`Undefined symbols for architecture armv7:
  "_dlaLoadModels", referenced from:

      -[DoraemonMethodUseTimeManager fixLoadModelArray] in DoraemonKit(DoraemonMethodUseTimeManager.o)

      -[DoraemonMethodUseTimeManager fixLoadModelArrayForHealth] in DoraemonKit(DoraemonMethodUseTimeManager.o)

ld: symbol(s) not found for architecture armv7
 `

**Comment by Cyandnow** [comment]
> Undefined symbols for architecture armv7:
  "_dlaLoadModels", referenced from:
      -[DoraemonMethodUseTimeManager fixLoadModelArray] in DoraemonKit(DoraemonMethodUseTimeManager.o)
      -[DoraemonMethodUseTimeManager fixLoadModelArrayForHealth] in DoraemonKit(DoraemonMethodUseTimeManager.o)
ld: symbol(s) not found for architecture armv7

**Comment by Cyandnow** [comment]
> > 推荐使用 https://github.com/CocoaPods/cocoapods-packager 自己打包。很简单方便。
> 
> 您好, 我在使用 pod package 打包后 使用时会产生如下错误
> 
> `
> Undefined symbols for architecture armv7:
> "_dlaLoadModels", referenced from:
> 
> ```
>   -[DoraemonMethodUseTimeManager fixLoadModelArray] in DoraemonKit(DoraemonMethodUseTimeManager.o)
> 
>   -[DoraemonMethodUseTimeManager fixLoadModelArrayForHealth] in DoraemonKit(DoraemonMethodUseTimeManager.o)
> ```
> 
> ld: symbol(s) not found for architecture armv7
> `

解决了, 没有带入 DoraemonLoadAnalyze.framework 这个库,
