### ISSUE TITLE
希望在pluginDidLoad方法中把itemData 和 index给传回来，我想动态定义plugin文件pluginDidLoad方法的跳转，需要知道点击的那个按钮的index 和 组头名字

### ISSUE THREAD

**Issue by xuXiaoDan** [didi/DoraemonKit#107]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

**Comment by xuXiaoDan** [comment]
希望在pluginDidLoad方法中把itemData 和 index给传回来以参数的形式返回来，我想用一个plugin文件 根据index 动态定义plugin文件pluginDidLoad方法的跳转，需要知道点击的那个按钮的index 和 组头名字

**Comment by xuXiaoDan** [comment]
希望能尽快解决这个问题，愿望很迫切，不想添加一个item就增加一个plugin文件

**Comment by yixiangboy** [comment]
好的 下个版本 修复。

**Comment by yixiangboy** [comment]
1.1.6版本已经添加改功能
