### ISSUE TITLE
记一个好玩的bug

### ISSUE THREAD

**Issue by a252539783** [didi/DoraemonKit#109]
布局层级中切换页面，然后回到当前页面
![image](https://user-images.githubusercontent.com/16000888/53480707-b2383e00-3ab6-11e9-90e4-b4515ae8bb5e.png)
![image](https://user-images.githubusercontent.com/16000888/53480781-d8f67480-3ab6-11e9-9308-54321a999a05.png)

**Comment by wanglikun7342** [comment]
哈哈哈，我们修复一下
