### ISSUE TITLE
iOS 求问下Load耗时检测 是指什么的耗时，app加载？代码是静态库，这个是不开源的吗？

### ISSUE THREAD

**Issue by dollarfromchina** [didi/DoraemonKit#111]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

**Comment by yixiangboy** [comment]
+load函数必须在app启动之前的时候调用，所以load函数中耗时操作太多的话，会影响app的启动速度。Load函数检测功能是一个动态库，为了保证在我们代码中其他load函数执行之前调用，所以不能直接源码依赖哦。源码在DoraemonLoadAnalyzeDemo这个工程中，也是开源的，跟主Demo在同一个文件夹下面。

**Comment by dollarfromchina** [comment]
> +load函数必须在app启动之前的时候调用，所以load函数中耗时操作太多的话，会影响app的启动速度。Load函数检测功能是一个动态库，为了保证在我们代码中其他load函数执行之前调用，所以不能直接源码依赖哦。源码在DoraemonLoadAnalyzeDemo这个工程中，也是开源的，跟主Demo在同一个文件夹下面。

再问下，动态库加载必然在主工程类的load之前执行，但动态库的load顺序你们这边就没办法让DoraemonLoadAnalyze 最先执行了吧

**Comment by yixiangboy** [comment]
你说的问题的确存在。oc项目的话，除了系统库， 很少会使用动态库的。

**Comment by dollarfromchina** [comment]
嗯嗯 多谢回答
