### ISSUE TITLE
Readme 里面涉及到的PageManager ，DebugService ，EnvSwitchFragment 是如何导入的？

### ISSUE THREAD

**Issue by dupengyun** [didi/DoraemonKit#118]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

**Comment by LinJZong** [comment]
这个是自定义控件功能，用户可以把自己app内的一些功能，比如动态切换环境之类的，放到DoKit的列表内，只需要实现IKit接口，再add进去就行，接入文档是举例说明。
