### ISSUE TITLE
设备Crash的收集包含所有类型还是信号类型？试了转发一个不存在的函数的crash，并没有收集。

### ISSUE THREAD

**Issue by P-Asserby** [didi/DoraemonKit#120]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

**Comment by yixiangboy** [comment]
iOS还是android？

**Comment by P-Asserby** [comment]
iOS的，就给个对象触发一个其不存在的函数。

**Comment by wenquanlebao** [comment]
Crash收集包含了两种类型，一种是Objective-C异常，另一种是信号异常。
我这边测试了两种触发不存在的函数，都是可以收集到的。

例子1：
id wrongArr = @"This is a NSString instance.";
[wrongArr addObject: @"The operate will crash your application"];
这种情况的Crash会被Object-C异常捕获，通过Crash查看日志中会看到含有Crash(Uncaught)字样的日志。

例子2：
Class clazz = NSClassFromString(@"XXXLoginViewController");
SEL sel = NSSelectorFromString(@"sharedInstance");
IMP imp = [clazz methodForSelector:sel];
id (*setUserDataFunc)(id, SEL) = (void *)imp;
id loginVC = setUserDataFunc(clazz,sel);
这种情况的Crash会被信号异常捕获，通过Crash查看日志中会看到含有Crash(Signal)字样的日志。

不知道您的触发过程是不是类似上面两种，或者可以将具体Crash的过程描述下。

最后，感谢对DoraemonKit的关注哈，欢迎PR。
