### ISSUE TITLE
是否支持线上app 统计相关信息例如carsh等，线上app 可否设置隐藏入口触发悬浮窗显示

### ISSUE THREAD

**Issue by sunhongda** [didi/DoraemonKit#121]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（android ）
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

**Comment by sunhongda** [comment]
通过gradle 配置了解到 是否不建议线上项目使用此工具呢？

**Comment by yixiangboy** [comment]
最好不要带到线上去，我们的产品定位就是研发助手类产品，在研发测试阶段使用。目前我们还没有在线上运行过Dokit。
