### ISSUE TITLE
ios:DoraemonPluginProtocol与DoraemonStartPluginProtocol出现方法重名

### ISSUE THREAD

**Issue by awaylyr** [didi/DoraemonKit#123]
Please complete the following informations.
> Expected behavior and actual behavior.
```
@protocol DoraemonStartPluginProtocol <NSObject>

- (void)pluginDidLoad;

@end

@protocol DoraemonPluginProtocol <NSObject>

@optional
- (void)pluginDidLoad;
- (void)pluginDidLoad:(NSDictionary *)itemData;

@end

```
上面两个协议，出现方法名相同的情况，导致无法在同一个类中同时实现两个协议

> Steps to reproducethe problem.

none

> Android or iOS? OS version? Brand? 

iOS 

> More informations such as error messages and stack traces are welcomed.

none

**Comment by yixiangboy** [comment]
代码已经提交master 。tag等修复更多问题之后再打。

**Comment by yixiangboy** [comment]
1.1.7版本已经修改
