### ISSUE TITLE
Doov手机无法正常显示

### ISSUE THREAD

**Issue by 1432886945** [didi/DoraemonKit#125]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

**Comment by yixiangboy** [comment]
请您详细描述一下问题？

**Comment by 1432886945** [comment]
就是初始化之后,那个悬浮工具弹窗无法显示,其他的手机可以

**Comment by wanglikun7342** [comment]
确认是否开启悬浮窗权限

**Comment by 1432886945** [comment]
开启了

**Comment by wanglikun7342** [comment]
悬浮入口可以显示，工具弹窗不能显示？

**Comment by wanglikun7342** [comment]
超时关闭
