### ISSUE TITLE
plugin编写有点bug

### ISSUE THREAD

**Issue by liqianjiang** [didi/DoraemonKit#130]
Configuration 'debugCompile' is obsolete and has been replaced with 'debugImplementation' and 'debugApi'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html。

在apply plugin: 'com.doraemon.compiler.plugin'这个插件里。

**Comment by LinJZong** [comment]
com.didichuxing.doraemonkit:compiler版本是多少，1.0.1版本应该已经修复了这个问题的

**Comment by LinJZong** [comment]
新版本会引用另外一个插件，用以解决无法hook子module、aar内代码的问题。
