### ISSUE TITLE
iOS端，Doraemonkit依赖冲突

### ISSUE THREAD

**Issue by linshizai** [didi/DoraemonKit#133]
![image](https://user-images.githubusercontent.com/13580181/55274056-ae464880-530e-11e9-8929-972cb6519059.png)

DoraemonKit依赖PNChart，PNChart依赖UICountingLabel 的1.2.0版本。但我的项目使用的是最新的UICountingLabel 的1.4.1版本。希望更新下。

我去PNChart看了他们的PNChart.podspec，他们的依赖：s.dependency 'UICountingLabel', '~> 1.4.1'，的确是1.4.1版本，所以不知道是什么原因。我本地也Pod update了，无法解决。

**Comment by yixiangboy** [comment]
估计PNChart的作者没有上传最新的代码到podsepc中心库。目前只能把你们UICountingLabel降低到1.2.0.其他也没啥好方案了，或者我们找一个其他的图形库，有没有推荐的？

**Comment by linshizai** [comment]
> 估计PNChart的作者没有上传最新的代码到podsepc中心库。目前只能把你们UICountingLabel降低到1.2.0.其他也没啥好方案了，或者我们找一个其他的图形库，有没有推荐的？

Charts

**Comment by lxlnihao** [comment]
iOS集成Lumberjack抓不到日志记录 ,有人遇到过吗
