### ISSUE TITLE
Android 8.0.0手机取色透明activity不能设置方向问题没有处理吗?

### ISSUE THREAD

**Issue by hcd2016** [didi/DoraemonKit#136]
大家点击取色的时候都没有遇到过这个BUG吗? Caused by: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation.
Android8.0.0版本google认定非fullscreen(透明activity也被判定)不能设置activity方向,8.1才修复,取色时应该是用的透明activity且设置了方向才导致这个问题吧. 我的baseactivity设置横竖屏的代码都去掉了还是不行.

**Comment by wanglikun7342** [comment]
好的，我们会修复这个问题

**Comment by wanglikun7342** [comment]
1.1.5版本已经修复
