### ISSUE TITLE
Error:(49, 42) 'DDLogMessage' does not have a member named '_message'

### ISSUE THREAD

**Issue by azureplus** [didi/DoraemonKit#137]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

**Comment by yixiangboy** [comment]
能详细的描述一下 吗？

**Comment by azureplus** [comment]
Pod(  # use_frameworks! )
pod install 后出现了这个问题了。。。

**Comment by azureplus** [comment]
关闭log 模块就能使用

**Comment by yixiangboy** [comment]
如果你的没有依赖CocoaLumberjack，就没有必要引入pod 'DoraemonKit/WithLogger'
