### ISSUE TITLE
希望能加一个按照页面进行分类的最高值，最低值、平局值这些数据，对单独页面做分析统计

### ISSUE THREAD

**Issue by su350380433** [didi/DoraemonKit#141]
希望能加一个按照页面进行分类的最高值，最低值、平局值这些数据，
按照页面，进行分析相对应的数据
这样就能很清楚的知道我们App的各方面性能问题了，哈哈。
好期待能有这样的功能。

**Comment by yixiangboy** [comment]
最新版本已经支持
