### ISSUE TITLE
查看crash日志tableview在xr xs等手机被导航栏遮挡

### ISSUE THREAD

**Issue by zhouxing5311** [didi/DoraemonKit#142]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。tableview cell不被遮挡。
> 问题重现的步骤。使用iphonexr真机或模拟器打开crash日志列表页面
> Android 还是 iOS？系统版本是多少？手机品牌是什么？iOS 12.1 iPhone XR
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。

![image](https://user-images.githubusercontent.com/14874355/56404135-90c62800-6297-11e9-9cea-92b54057f0e1.png)

**Comment by yixiangboy** [comment]
代码已提交 下个版本修复

**Comment by yixiangboy** [comment]
主要是针对于 设置了全局配置[UIScrollView appearance].contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;的用户才会有这个问题

**Comment by yixiangboy** [comment]
1.1.8版本已经修复
