### ISSUE TITLE
组件检查和对齐标尺组件展示后切换rootviewcontroller后失去响应

### ISSUE THREAD

**Issue by zhouxing5311** [didi/DoraemonKit#143]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。组件不接受用户响应，不能正常使用。
> 问题重现的步骤。 打开组件检查组件后切换delegate window 的 rootviewcontroller，然后拖动组件检查按钮。
> Android 还是 iOS？系统版本是多少？手机品牌是什么？ iOS 12.1 iPhone XR
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。

屏幕录像：
[屏幕录制 2019-04-19 上午11.11.56.zip](https://github.com/didi/DoraemonKit/files/3096939/2019-04-19.11.11.56.zip)

**Comment by DeveloperLY** [comment]
已修复

**Comment by yixiangboy** [comment]
1.2.2已修复
