### ISSUE TITLE
安装DoraemonKit后摇一摇功能失效

### ISSUE THREAD

**Issue by zhouxing5311** [didi/DoraemonKit#144]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。 安装DoraemonKit后摇一摇功能失效
> 问题重现的步骤。 安装DoraemonKit后，在rootviewcontroller viewdidload写摇一摇相关方法及代理方法。摇动手机检查代理方法执行。
> Android 还是 iOS？系统版本是多少？手机品牌是什么？ iOS 12.1 iPhone XR
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

- (void)viewDidLoad {
    [super viewDidLoad];
    
    self.view.backgroundColor = [UIColor whiteColor];   

    //设置摇一摇
    [UIApplication sharedApplication].applicationSupportsShakeToEdit = YES;
    [self becomeFirstResponder];
}

// 摇一摇开始摇动
- (void)motionBegan:(UIEventSubtype)motion withEvent:(UIEvent *)event {
    NSLog(@"开始摇动");
}

// 摇一摇取消摇动
- (void)motionCancelled:(UIEventSubtype)motion withEvent:(UIEvent *)event {
    NSLog(@"取消摇动");
}

// 摇一摇摇动结束
- (void)motionEnded:(UIEventSubtype)motion withEvent:(UIEvent *)event {
    if (event.subtype == UIEventSubtypeMotionShake) { // 判断是否是摇动结束
        NSLog(@"摇动结束");
        
        BOOL canShake = [UIApplication sharedApplication].applicationSupportsShakeToEdit;
        
        if (!canShake) {
            return;
        }
        
       NSLog(@"执行摇动方法");
    }
}

**Comment by yixiangboy** [comment]
欢迎更新到最新版本，已经解决该问题，详见 http://www.dokit.cn/
