### ISSUE TITLE
建议增加wkwebview的流量拦截检测，也是通过NSURLProtocol去拦截 

### ISSUE THREAD

**Issue by Wbqqqq** [didi/DoraemonKit#148]
github上有比较成熟的解决方案

**Comment by yixiangboy** [comment]
> github上有比较成熟的解决方案

兄弟，可以发一下方案地址吗？

**Comment by yixiangboy** [comment]
> github上有比较成熟的解决方案

兄弟 我们正在举行“提PR 赢大奖”的互动，如果你可以解决这个问题，可以参加 。活动地址如下：https://github.com/didi/DoraemonKit/issues/146

**Comment by yixiangboy** [comment]
有没有同学有相关经验的，求。

**Comment by Bintong** [comment]
https://juejin.im/post/5a37d039518825256362c6ce

**Comment by Wbqqqq** [comment]
https://github.com/LiuShuoyu/HybirdWKWebVIew  我用的这个 还可以的，但是个别h5打开可能会有问题。

**Comment by yixiangboy** [comment]
NSURLProtocol 支持  wkwebview 目前没有完美支持的方案，欢迎PR
