### ISSUE TITLE
Android 流量监控 响应体乱码

### ISSUE THREAD

**Issue by yizems** [didi/DoraemonKit#156]
![image](https://user-images.githubusercontent.com/16949474/56861861-beb61580-69d7-11e9-8803-1f89c929219e.png)

> 期望的表现和实际的表现。响应行乱码=.=
> 问题重现的步骤。必先
> Android ,9.0,华为mate20
okhttp 3.11.0

**Comment by LinJZong** [comment]
服务端返回的数据有加密吗？

**Comment by yizems** [comment]
@LinJZong  没有,都是明文的

**Comment by LinJZong** [comment]
> @LinJZong 没有,都是明文的

可以看看返回的数据的编码格式，现在直接用了默认的解码格式，可能是这个问题导致的

**Comment by yizems** [comment]
@LinJZong 
我是直接加入的 okhttp包下的拦截器，会不会是这里的问题


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by yizems** [comment]
我的错,
![image](https://user-images.githubusercontent.com/16949474/56872893-97eff180-6a60-11e9-84f1-dcc22cbc5821.png)

我加成了 addNetworkInterceptor

**Comment by feiyang1235** [comment]
应该怎么加？大佬~ 我也是这样加的。同样是乱码
