### ISSUE TITLE
Bug iPad UI横竖屏幕切换时出现黑框

### ISSUE THREAD

**Issue by Co2333** [didi/DoraemonKit#158]
如图。iOS12.0.1，iPad Pro 10.5

![C46E38D9-F1D4-4D59-9DB9-BD921EBDC6C6](https://user-images.githubusercontent.com/25259084/56868650-981fcb00-6a27-11e9-8a85-164298b268a7.png)

**Comment by yixiangboy** [comment]
多谢反馈，这个问题，网友[Hugin](https://github.com/HuginChen)正在解决中，争取下个版本上线。

**Comment by HuginChen** [comment]
已解决 https://github.com/didi/DoraemonKit/pull/168
