### ISSUE TITLE
Android 是否考虑增加  获取栈顶的Activity --> Fragment 并展示，快速定位bug

### ISSUE THREAD

**Issue by bingdu0** [didi/DoraemonKit#159]

**Comment by LinJZong** [comment]
现在的组件检查功能里会显示当前栈顶的Activity和Fragment，可以看看能不能满足你的需求

**Comment by azhon** [comment]
> 现在的组件检查功能里会显示当前栈顶的Activity和Fragment，可以看看能不能满足你的需求

https://github.com/didi/DoraemonKit/pull/162

**Comment by imtianx** [comment]
显示 `Fragment` 栈很麻烦吧，看了下代码，[TopActivity](https://github.com/didi/DoraemonKit/blob/master/Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/kit/topactivity/TopActivityFloatPage.java) 组件只有显示 activity 。可以用  adb 来查看 栈信息。
