### ISSUE TITLE
com.hujiang.aspectjx:gradle-android-plugin-aspectjx 问题

### ISSUE THREAD

**Issue by joker-fu** [didi/DoraemonKit#160]
感觉有点大材小用，可以参考下pandora呢，一样实现了网络监控，觉得哆啦功能更多，想缓过来试试，但是看到这儿（com.hujiang.aspectjx:gradle-android-plugin-aspectjx ）总觉得哪里不带劲

**Comment by LinJZong** [comment]
引用aspectj字节码主要为了解决两个问题：一是实现一键接入，即用户只需要在application内写一句DoraemonKit.install就能接入所有功能（事实上如果引入了插件连这句话都可以省略）,二是实现三方库的网络请求。事实上，不引用这个插件也没什么问题，DoKit同样提供了可供手动注册的拦截器DoraemonInterceptor，这一块我在文档里补充说明下。
