### ISSUE TITLE
Android Crash丢失

### ISSUE THREAD

**Issue by androidfei** [didi/DoraemonKit#165]
在Android手机上点击Demo里面的测试Crash然后在进入Demo 查看Crash显示没有Crash日志（Crash日志的收集已经打开）

**Comment by yanjian824** [comment]
@androidfei 通过实现Thread.UncaughtExceptionHandler接口来全局监听crash是比较成熟的方案不太容易出bug，怀疑Doraemon App Demo 没有WRITE_EXTERNAL_STORAGE的权限。

**Comment by wanglikun7342** [comment]
看下打包后Manifest文件中是否有IO权限WRITE_EXTERNAL_STORAGE

**Comment by lizhiwei92** [comment]
![image](https://user-images.githubusercontent.com/22723524/57424565-a8ffe600-724a-11e9-95b5-f282e8b23d77.png)
建议sdk暴露方法给接入方自主设置，毕竟不是所有app都会申请sd卡权限
或者在开关打开时，sdk做权限申请

**Comment by wanglikun7342** [comment]
1.1.8版本已经改为保存到私有文件夹中，欢迎尝试
