### ISSUE TITLE
沙河目录，查看大文件这个功能可以添加一个，目前是按照目录归档，可以多一个根据大小 文件类型 的标签进行归类

### ISSUE THREAD

**Issue by Bintong** [didi/DoraemonKit#169]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

**Comment by wanglikun7342** [comment]
后续版本会增加这一功能，也欢迎主动提交pr，可以获得礼品和荣誉喔
