### ISSUE TITLE
iOS :sanbox 可以支持 webp格式查看

### ISSUE THREAD

**Issue by k373379320** [didi/DoraemonKit#173]
在 DoraemonSanboxDetailViewController.m 中

#import "UIImage+WebP.h"

 if (self.filePath.length>0) {
        NSString *path = self.filePath;
        if ([path hasSuffix:@".png"]  || [path hasSuffix:@".PNG"]
            || [path hasSuffix:@".jpg"]  || [path hasSuffix:@".JPG"]
            || [path hasSuffix:@".jpeg"] || [path hasSuffix:@".JPEG"]
            || [path hasSuffix:@".gif"]  || [path hasSuffix:@".GIF"]|| [path hasSuffix:@".webp"]) {
           
            UIImage *img;
            if ([path hasSuffix:@".webp"]) {
                NSData *data = [NSData dataWithContentsOfFile:self.filePath];
                if (data) {
                    img =  ((UIImage * (*)(id, SEL,id)) objc_msgSend)([UIImage class], NSSelectorFromString(@"sd_imageWithWebPData:"),data);
                }
            } else {
                img = [[UIImage alloc]initWithContentsOfFile:self.filePath];
            }
            // 图片文件
            [self setOriginalImage:img];

**Comment by yixiangboy** [comment]
这个会依赖SDWebImage啊

**Comment by k373379320** [comment]
> 这个会依赖SDWebImage啊

单独copy那个实现呢.

**Comment by yixiangboy** [comment]
> > 这个会依赖SDWebImage啊
> 
> 单独copy那个实现呢.

我看了一下实现，还会引用其他三方库，成本有点大
