### ISSUE TITLE
在已经集成plugin: 'android-aspectjx'的情况下编译报错

### ISSUE THREAD

**Issue by miserydx** [didi/DoraemonKit#174]
在已经集成plugin: 'android-aspectjx'的情况下，依赖'com.didichuxing.doraemonkit:doraemonkit:1.1.6'会发生编译报错
------------------------------------------------------------------
gradle版本：
https\://services.gradle.org/distributions/gradle-4.6-all.zip

根目录build.gradle :
    dependencies {
        ...
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.4'
        ...
    }

主工程 build.gradle :
apply plugin: 'android-aspectjx'
------------------------------------------------------------------
gradle报错：
AGPBI: {"kind":"error","text":"Uncaught translation error: com.android.dx.cf.code.SimException: local variable type mismatch: attempt to set or access a value of type java.lang.Class using a local variable of type java.lang.String[]. This is symptomatic of .class transformation tools that ignore local variable information.","sources":[{}]}
AGPBI: {"kind":"error","text":"1 error; aborting","sources":[{}]}
:app:transformClassesWithDexForDebug FAILED
:app:transformClassesWithDexForDebug spend 20612ms

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 24s

**Comment by Knight-ZXW** [comment]
com.hujiang.aspectjx:gradle-android-plugin-aspectjx 插件似乎存在BUG，因为我们项目使用最新版本的doraemonkit 运行时 会报 dex 找不到 某个类。 clone最新版本的doraemonkit后将com.hujiang.aspectjx:gradle-android-plugin-aspectjx插件改为之前的使用aspectj后  就好了，

**Comment by LinJZong** [comment]
> com.hujiang.aspectjx:gradle-android-plugin-aspectjx 插件似乎存在BUG，因为我们项目使用最新版本的doraemonkit 运行时 会报 dex 找不到 某个类。 clone最新版本的doraemonkit后将com.hujiang.aspectjx:gradle-android-plugin-aspectjx插件改为之前的使用aspectj后 就好了，

这个也遇到了，不过原因是因为方法数超过65536而没有使用mulityDex，不知道你那是不是同样原因

**Comment by TSsimeon** [comment]
同样的问题。不修改插件如何解决呢。

**Comment by LinJZong** [comment]
可以升级到1.1.8版本，具体接入可看文档
https://github.com/didi/DoraemonKit/blob/master/Doc/android_cn_guide.md
