### ISSUE TITLE
重复唤醒DoKit造成重复加载

### ISSUE THREAD

**Issue by Co2333** [didi/DoraemonKit#175]
![IMG_0222](https://user-images.githubusercontent.com/25259084/57216806-7f18aa80-7023-11e9-9a24-e023bb27546e.PNG)

**Comment by yixiangboy** [comment]
install方法只能加载一次。放在应用启动的时候。

**Comment by Co2333** [comment]
有没有show的方法，我放了个打开dokit的按钮

**Comment by yixiangboy** [comment]
> 有没有show的方法，我放了个打开dokit的按钮

代码里面已经添加了，但是要下个版本才上线。
