### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by PerrywLiu** [didi/DoraemonKit#178]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

Pod install 只能安装1.1.5的版本

请补充如下信息。
> 问题重现的步骤。
fork 后，直接pod install
>  iOS
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。

Installing DoraemonKit (1.1.5)

errorInfo：
[!] CocoaPods could not find compatible versions for pod "DoraemonKit":
  In Podfile:
    DoraemonKit (= 1.1.7)

None of your spec sources contain a spec satisfying the dependency: `DoraemonKit (= 1.1.7)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by yixiangboy** [comment]
更新本地仓库 pod install --repo-update

**Comment by PerrywLiu** [comment]
已解决，多谢，是pod版本的问题，更新后就可以了，我用的是pod update --verbose
