### ISSUE TITLE
是否可以将项目拆分成多个子项目自动组装

### ISSUE THREAD

**Issue by Knight-ZXW** [didi/DoraemonKit#181]
因为目前我们的项目中 有自己的性能监控模块。所以Doraemonkit 比如将性能监控功能以及视觉工具 拆分成2单独的子模块及maven项目，这2个功能可以按需添加。

**Comment by LinJZong** [comment]
感谢建议。
目前正在做子模块的动态注册功能，不过针对的不是性能模块和视觉模块，而是其他更加独立和定制化的模块，这些模块会以单独的aar形式提供。另外按我的理解，视觉和性能模块都是基础功能模块，如果拆分的太细，会加大使用者的接入难度；而DoKit的定位是开发和测试期间的调试工具，对于sdk的大小，会关注的较少，因为不会带到线上去。
针对你的需求，是否可以提供一个拆解或者替换当前kit的方法来解决，比如你们自带的CPU监控功能，可以通过定义一个和DoKit自带的CPU相同的Key的Kit，注册到DoKit中，在Dokit面板中点击cpu检测功能，就跳转到自己工程的cpu检测模块。

**Comment by Knight-ZXW** [comment]
提供一个拆解或者替换当前kit的方法来解决，这个感觉可以支持下。

另外我的考虑是虽然DoKit只会在测试期间带入，但是后面功能越来越多，自身的类库及依赖太多的话（比如现在还引入了gson、zxing），是否会对编译速度有一定的影响，尤其是我的项目中也使用了ASM技术， 需要对所有的 类做扫描，当前这个可以通过 过滤包名来优化掉。

**Comment by LinJZong** [comment]
关于依赖，在当时设计之初的时候就想过，除了官方提供的几个库以外，尽量不依赖其他第三方库。目前DoKit对于三方库的依赖不多，zxing是最近才加上去的，后续会慢慢把所有对第三方的依赖都尽量改成自己实现或其他替代方案。
理想情况是DoKit的基础包大小在1m左右，包含一些稳定的核心功能。在这个基础上，提供一些扩展功能，以aar的形式，引用之后自动注册到面板中。这一块也正在进行中。
