### ISSUE TITLE
fps的计算方式是否有误？

### ISSUE THREAD

**Issue by yueshaojun** [didi/DoraemonKit#182]
我看到代码里计算的方式是：
` mLastFrameRate = Math.round(SECOND_IN_NANOS / (frameTimeNanos - mLastFrameTimeNanos));`
doFrame是下一次帧绘制完的回调，frameTimeNanos - mLastFrameTimeNanos 的值是当前帧的耗时。但是fps是一个为秒为单位的值，拿一秒内其中一帧的值去判断一秒的结果可能不太合适。应该是一个平均值？

**Comment by wanglikun7342** [comment]
后续版本会修改成固定时间帧数法

**Comment by yueshaojun** [comment]
期待

**Comment by wanglikun7342** [comment]
最新版本已经修复
