### ISSUE TITLE
iOS xcodebuild Debug模式下，出的包不展示

### ISSUE THREAD

**Issue by muwan** [didi/DoraemonKit#191]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
xcodebuild 打包 debug 情况下，没有加载doraemonkit
希望debug模式打包的时候能有

> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
iOS

**Comment by yixiangboy** [comment]
已在群里沟通过。
