### ISSUE TITLE
Android 版本Dokit依赖了zxing等第三方库，集成后容易和app的原有依赖产生版本冲突，建议在接入文档中说明和提供规避方法

### ISSUE THREAD

**Issue by ChinaStyle812** [didi/DoraemonKit#194]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

**Comment by dengyuhan** [comment]
手动排除掉吧
```
 implementation('com.didichuxing.doraemonkit:doraemonkit:1.1.7') {
        exclude group: 'com.google.code.gson'
        exclude group: 'com.google.zxing'
        exclude group: 'com.squareup.okhttp3'
 }
```

**Comment by Domlaa** [comment]
> 手动排除掉吧
> 
> ```
>  implementation('com.didichuxing.doraemonkit:doraemonkit:1.1.7') {
>         exclude group: 'com.google.code.gson'
>         exclude group: 'com.google.zxing'
>         exclude group: 'com.squareup.okhttp3'
>  }
> ```

我的是百度的LBS依赖冲突，使用exclude也无法解决。。。
