### ISSUE TITLE
为什么要统计我们的使用信息？

### ISSUE THREAD

**Issue by SuiFeng** [didi/DoraemonKit#205]
统计URL：https://doraemon.xiaojukeji.com/uploadAppData
统计参数：
CFBundleDisplayName
CFBundleShortVersionString
bundleIdentifier
开源统计：
可以通过pods或者其他方式，而不采用自己调用自己接口的方式。
如果必须得调用自己接口的方式，麻烦默认关掉，如果使用方想给你上报再主动打开，而非默认方式，毕竟你们是优秀的开源提供方，应该考虑到用户的隐私。

**Comment by yixiangboy** [comment]
我们在官网首页底部有使用提醒。主要是为了统计一下我们产品的使用用户数。不用于任何恶意用途，请放心使用。如果你不放心的话，你也可以选择主动关闭上传信息。

**Comment by SuiFeng** [comment]
那你们至少提供一个开关呀。

**Comment by yixiangboy** [comment]
在install之前调用 [DoraemonStatisticsUtil shareInstance].noUpLoad = YES;

**Comment by SheepYang1993** [comment]
android可以用混淆，直接把上传信息的代码去掉
```
-assumenosideeffects class com.didichuxing.doraemonkit.util.DoraemonStatisticsUtil{
    public static void uploadUserInfo(...);
}
```
