### ISSUE TITLE
监控耗时Activity页面的功能使用不了

### ISSUE THREAD

**Issue by yj024502** [didi/DoraemonKit#209]
Android 9.0 三星s9
测试页面跳转耗时，只有启动耗时，页面跳转耗时打印日志并未有结果，目测PrinterParser类parse方法有问题，各条件走不进去

**Comment by LinJZong** [comment]
android 9.0修改了Activity生命周期相关的的消息导致，下个版本做下适配。

**Comment by LinJZong** [comment]
> android 9.0修改了Activity生命周期相关的的消息导致，下个版本做下适配。
看了下源码，9.0通过ClientTransactionItem来执行Activity不同的生命周期回调，Handler log无法区分这些item的区别，需要改套方案才行了。

**Comment by yj024502** [comment]
嗯嗯  那这个新方案你们这边有计划支持么 渲染的耗时其实对客户端APM和用户直观体验来说还是比较重要的指标

**Comment by LinJZong** [comment]
> 嗯嗯 那这个新方案你们这边有计划支持么 渲染的耗时其实对客户端APM和用户直观体验来说还是比较重要的指标

已经在改了，应该在端午前后可以提供个新版本。

**Comment by LinJZong** [comment]
1.1.18版本已修复该问题
