### ISSUE TITLE
Android流畅度检测，写文件不断报错。

### ISSUE THREAD

**Issue by PengZeHai** [didi/DoraemonKit#210]
PerformanceDataManager.getInstance().init(getContext().getApplicationContext());
只有几个模块调了这个方法，初始化了filePath = getFilePath(context);
其他模块，没有初始化的话，filePath为null

**Comment by LinJZong** [comment]
感谢反馈，下个版本修复这个问题

**Comment by wanglikun7342** [comment]
1.2.0已经修复了这个问题
