### ISSUE TITLE
Android Crash收集功能不好用

### ISSUE THREAD

**Issue by lizhiwei92** [didi/DoraemonKit#211]
v1.1.5版本
CrashHandlerManager
默认path被写死sd卡中，对没有外部存储读写权限的app不友好
uncaughtException()被handle两次，同一个崩溃被存两次
`
@Override
    public void uncaughtException(Thread thread, Throwable ex) {
        if (!handleException(ex) && mDefaultHandler != null) {
            mDefaultHandler.uncaughtException(thread, ex);
        } else {
            handler.post(new Runnable() {
                @Override
                public void run() {
                    Toast.makeText(mContext, R.string.dk_crash_capture_tips, Toast.LENGTH_LONG).show();
                }
            });
        }

        if (!handleException(ex) && mDefaultHandler != null) {
            mDefaultHandler.uncaughtException(thread, ex);
        } else {
            try {
                Thread.sleep(3000);
            } catch (InterruptedException e) {

            }
            android.os.Process.killProcess(android.os.Process.myPid());
            System.exit(0);
        }
    }
`

**Comment by wanglikun7342** [comment]
1.1.8版本已经优化了体验，欢迎尝试
