### ISSUE TITLE
Android TV小米电视点不了

### ISSUE THREAD

**Issue by shangmengmeng** [didi/DoraemonKit#212]
Android Tv小悬浮按钮点不了，就没然后了

**Comment by shangmengmeng** [comment]
可能设个focusable =true 就行

**Comment by wanglikun7342** [comment]
小米tv我们这边没有设备，可能要后面才能支持

**Comment by ff-frida** [comment]
> Android Tv小悬浮按钮点不了，就没然后了

Gimi的也不行，整个程序的焦点都不见了

**Comment by lyb5834** [comment]
> > Android Tv小悬浮按钮点不了，就没然后了
> 
> Gimi的也不行，整个程序的焦点都不见了

请问 TV 调试怎么解决的啊？焦点完全不见了，遥控器就是摆设
