### ISSUE TITLE
我直接用签名打包也遇到了这个问题java.lang.NoSuchMethodError: No static method aspectOf()Lcom/didichuxing/doraemonkit/DoraemonHooker;

### ISSUE THREAD

**Issue by martin-huang** [didi/DoraemonKit#213]
我直接用签名打包也遇到了这个问题java.lang.NoSuchMethodError: No static method aspectOf()Lcom/didichuxing/doraemonkit/DoraemonHooker;

_Originally posted by @jokerzzzz in https://github.com/didi/DoraemonKit/issues/187#issuecomment-491174337_

我也遇到了 很蛋疼，文档里面没有说明，请更新一下文档如何解决

**Comment by LinJZong** [comment]
下个版本会把AJ注解类移到一个单独的aar包内，来解决这个问题。

**Comment by LinJZong** [comment]
可以升级到1.1.8版本，具体接入可看文档
https://github.com/didi/DoraemonKit/blob/master/Doc/android_cn_guide.md
