### ISSUE TITLE
Android端日志查看页面，日志内容期望提供到底和到顶的功能

### ISSUE THREAD

**Issue by mengxin1995** [didi/DoraemonKit#214]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
提供操作能够定位日志内容快速到顶，快速到底
> 问题重现的步骤。（如有）
每次搜索完关键字日志内容会停止不动，需手动滑到底部
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
Android
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

**Comment by wanglikun7342** [comment]
欢迎提交pr
