### ISSUE TITLE
iOS SDK crash 收集不到  为什么？

### ISSUE THREAD

**Issue by zhanghaibo6488** [didi/DoraemonKit#215]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

**Comment by yixiangboy** [comment]
可以试一下我们的demo。我们只支持最基本的crash拦截，具体详见 https://www.jianshu.com/p/5b17d78b9c7b
