### ISSUE TITLE
[!] Error installing WeexSDK

### ISSUE THREAD

**Issue by AdminTestsGitHub** [didi/DoraemonKit#216]
1.1.9 DoraemonKitDemo pod 安装失败。

pod install

Installing AFNetworking (2.6.3)
Installing BSBacktraceLogger (0.0.1)
Installing CocoaLumberjack (3.5.2)
Installing DoraemonKit (1.2.0)
Installing PNChart (0.8.9)
Installing SocketRocket (0.5.1)
Installing UICountingLabel (1.2.0)
Installing UITextView+Placeholder (1.2.1)
Installing WXDevtool (0.20.0)
Installing WeexSDK (0.20.1)

[!] Error installing WeexSDK
[!] /usr/local/bin/git clone https://github.com/apache/incubator-weex.git /var/folders/cr/8ctf1zz54sx6msvr6m2m3fcw0000gn/T/d20190614-72459-wryx32 --template= --single-branch --depth 1 --branch 0.20.1

Cloning into '/var/folders/cr/8ctf1zz54sx6msvr6m2m3fcw0000gn/T/d20190614-72459-wryx32'...
warning: Could not find remote branch 0.20.1 to clone.
fatal: Remote branch 0.20.1 not found in upstream origin

**Comment by yixiangboy** [comment]
可以指定weex版本号试试，感觉是网络的问题
