### ISSUE TITLE
DoraemonMetricsView建议使用Layer绘制

### ISSUE THREAD

**Issue by MSAlertController** [didi/DoraemonKit#218]
请补充如下信息。
> 期望的表现和实际的表现。（如有）希望不影响原有代码
> 问题重现的步骤。（如有）元素边框线，不管开不开启都有问题
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）iOS10.3.3
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）没崩

DoraemonMetricsView使用UIView的两个BUG：
①如果原来的工程中使用subviews通过下标去取值，有可能出现取到DoraemonMetricsView的情况
②不知道12上怎么样，在我的10.3.3上，因为DoraemonMetricsView的存在UIMenuItem出不来，键盘也经常弹不出来，或者弹出来无法点击。
我自己尝试了CALayer，可以解决上面的两个BUG，而且使用CALayer还有三个好处，不用屏蔽高德地图，不用屏蔽毛玻璃视图，不用屏蔽DoraemonMetricsView
（时间原因，只能把问题提出来了，就不帮你们改代码了😂）

**Comment by hiXgb** [comment]
https://github.com/didi/DoraemonKit/pull/221 已合并该PR，感谢反馈
