### ISSUE TITLE
打开元素边框线开关，崩溃在RN [RCTScrollView RCTScrollView] 中

### ISSUE THREAD

**Issue by 329463417** [didi/DoraemonKit#219]
- (void)layoutSubviews
{
  [super layoutSubviews];
  RCTAssert(self.subviews.count == 1, @"we should only have exactly one subview");
  RCTAssert([self.subviews lastObject] == _scrollView, @"our only subview should be a scrollview");

#if !TARGET_OS_TV
  // Adjust the refresh control frame if the scrollview layout changes.
  UIView<RCTCustomRefreshContolProtocol> *refreshControl = _scrollView.customRefreshControl;
  if (refreshControl && refreshControl.isRefreshing) {
    refreshControl.frame = (CGRect){_scrollView.contentOffset, {_scrollView.frame.size.width, refreshControl.frame.size.height}};
  }
#endif

  [self updateClippedSubviews];
}

**Comment by hiXgb** [comment]
https://github.com/didi/DoraemonKit/pull/221 这个PR修改成layer的方式，请使用最新代码尝试是否还有这个问题，感谢反馈
