### ISSUE TITLE
iPad pro真机设置了限制帧速率最高60，fps侦测值最高为120

### ISSUE THREAD

**Issue by yvetteyoung4** [didi/DoraemonKit#220]
iPad pro真机（3代 12.9寸，ipad8,5 iOS 12.3）
设置了限制帧速率（通用-》辅助功能-》显示调节-》限制帧速率）最高60

期望的表现：fps侦测帧率最高为60
实际的表现：fps侦测帧率以及自定义测试报告fps最高值为120

**Comment by yixiangboy** [comment]
暂无设备可以复现。我们是基于CADisplayLink方法回调的。限制帧速率 是不是不会影响CADisplayLink的回调？
