### ISSUE TITLE
无法pod

### ISSUE THREAD

**Issue by stone4302** [didi/DoraemonKit#225]
iOS pod库已升级到最新 但是pod install 失败
提示：
[!] CocoaPods could not find compatible versions for pod "DoraemonKit/WithWeex":
  In Podfile:
    DoraemonKit/WithWeex (~> 1.2.0)

Specs satisfying the `DoraemonKit/WithWeex (~> 1.2.0)` dependency were found, but they required a higher minimum deployment target.

pod search DoraemonKit/WithWeex也找不到

**Comment by yixiangboy** [comment]
更新一下 本地仓库试试

**Comment by yixiangboy** [comment]
pod search找不到的话，尝试使用 https://www.jianshu.com/p/9add72f11df6
