### ISSUE TITLE
iOS UITextView (Placeholder)加上doraemon_前缀

### ISSUE THREAD

**Issue by SuiFeng** [didi/DoraemonKit#231]
很多App都实现了UITextView的placeholder的方法，这样会与DoraemonKit中的placeholder方法冲突。

目前我们库中就发现会与移动的一键登录的SDK会有冲突，导致crash。

DoraemonKit中的很多系统类的扩展中都加了doraemon_的前缀，但是有个别的还是没有加上，希望你们统一一下，多谢。

**Comment by yixiangboy** [comment]
最新代码已修复，下个版本支持
