### ISSUE TITLE
部分iOS机型如iPhone XR，未适配横屏app，部分工具下方内容无法显示

### ISSUE THREAD

**Issue by yvetteyoung4** [didi/DoraemonKit#232]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
--》适配横屏app，所有工具可完整显示；

> 问题重现的步骤。（如有）
--》1.在iOS横屏app中引入工具并打开app；
2.选择“自定义测试” or “流量检测”等工具；
3.工具下方内容无法显示；

> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
--》iOS 12.3.1 ，iPhone XR
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

**Comment by yixiangboy** [comment]
最新代码已修复，下个版本支持

**Comment by yixiangboy** [comment]
1.2.1已修复
