### ISSUE TITLE
希望能支持下CocoaPods1.7 的generate_multiple_pod_projects新特性

### ISSUE THREAD

**Issue by Panway** [didi/DoraemonKit#234]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现：支持CocoaPods1.7新特性
> 问题重现的步骤。
Podfile加入以下代码增加索引速度会报错，原因是头文件的引用出错：
``` ruby
install! 'cocoapods',
  generate_multiple_pod_projects: true,
  incremental_installation: true
```
把`DoraemonH5ViewController.m`的第13行：
`#import "UITextView+Placeholder.h"`
改成
`#import <UITextView_Placeholder/UITextView+Placeholder.h>`
即可

**Comment by yixiangboy** [comment]
1.2.1已修复
