### ISSUE TITLE
Android依赖库的一些问题

### ISSUE THREAD

**Issue by dengyuhan** [didi/DoraemonKit#238]
*  建议`com.android.support`升级28
*  是否考虑升级`androidx`
*  因为不是每个功能都会用到，把`DoKit`所依赖的库全部`compileOnly`，需要用哪个功能再手动加入所依赖的库，这样是否更好一点

**Comment by jtsky** [comment]
> * 建议`com.android.support`升级28
> * 是否考虑升级`androidx`
> * 因为不是每个功能都会用到，把`DoKit`所依赖的库全部`compileOnly`，需要用哪个功能再手动加入所依赖的库，这样是否更好一点

这个问题我们近期会考虑，并单独提供一个androidx版本，敬请期待
