### ISSUE TITLE
iOS8模拟器crash

### ISSUE THREAD

**Issue by yirenyiyi** [didi/DoraemonKit#241]
运行在 iOS8 模拟器上crash 报错如下：
dyld: Library not loaded: /System/Library/PrivateFrameworks/ContactsPersistence.framework/Versions/A/ContactsPersistence   Referenced from: /System/Library/Frameworks/Contacts.framework/Contacts   Reason: no suitable image found.  Did find: 	/System/Library/PrivateFrameworks/ContactsPersistence.framework/Versions/A/ContactsPersistence: mach-o, but not built for iOS simulator
（xcode 版本：10.1）

**Comment by yixiangboy** [comment]
请问一下 如何操作才能复现？

**Comment by yirenyiyi** [comment]
一运行就会crash @yixiangboy

**Comment by y500** [comment]
我试了，没崩

**Comment by yixiangboy** [comment]
无法复现 暂时关闭。如果您那边必先的话，欢迎给我们pr
