### ISSUE TITLE
请求抓包问题

### ISSUE THREAD

**Issue by JDongKhan** [didi/DoraemonKit#242]
NSURLSession的网络不能监控吗？ NSURLSessionConfiguration相关的配置好像没有效果，导致项目的接口都没有采集到，其他第三方的SDK请求到是抓到了。 

AFNetworking版3.1.0。

**Comment by Bintong** [comment]
监控问题 是因为protocl并没有兼容到你的情况，和AFN 无关。可以Hook 通过Swizzle method 方式 对NSURLSession 进行获取。 目前Didi 这个库网络监控 如果兼容到你那个 预计要一定时间

**Comment by lxlnihao** [comment]
iOS都抓不到数据 你们有遇到过吗

**Comment by yixiangboy** [comment]
可以加qq群，找群主私聊。

**Comment by yixiangboy** [comment]
暂时无法复现，先行关闭
