### ISSUE TITLE
Android无法添加aop库依赖

### ISSUE THREAD

**Issue by cpecho** [didi/DoraemonKit#243]
gradle版本4.4
在app的build.gradle中添加如下两个依赖
    debugImplementation 'com.didichuxing.doraemonkit:doraemonkit:1.1.8'
    debugImplementation 'com.didichuxing.doraemonkit:doraemonkit-aop:1.0.0'
但编译一直报错，无法找到aop依赖
ERROR: Failed to resolve: com.didichuxing.doraemonkit:doraemonkit-aop:1.0.0
Show in Project Structure dialog
Affected Modules: app

依赖配置
 dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4' 
        classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.4'
    }
不配置aop，单独使用doraemonkit:1.1.8是可以正常使用的，这两个库放的是不同的仓库吗？aop的库需要做什么特殊处理吗？

**Comment by aopi1125** [comment]
the same problem appeared in my project

**Comment by jtsky** [comment]
> gradle版本4.4
> 在app的build.gradle中添加如下两个依赖
> debugImplementation 'com.didichuxing.doraemonkit:doraemonkit:1.1.8'
> debugImplementation 'com.didichuxing.doraemonkit:doraemonkit-aop:1.0.0'
> 但编译一直报错，无法找到aop依赖
> ERROR: Failed to resolve: com.didichuxing.doraemonkit:doraemonkit-aop:1.0.0
> Show in Project Structure dialog
> Affected Modules: app
> 
> 依赖配置
> dependencies {
> classpath 'com.android.tools.build:gradle:3.1.4'
> classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.4'
> }
> 不配置aop，单独使用doraemonkit:1.1.8是可以正常使用的，这两个库放的是不同的仓库吗？aop的库需要做什么特殊处理吗？

目前已经发布2.0.0版本，请升级以后再试下

**Comment by MycroftWong** [comment]
> > gradle版本4.4
> > 在app的build.gradle中添加如下两个依赖
> > debugImplementation 'com.didichuxing.doraemonkit:doraemonkit:1.1.8'
> > debugImplementation 'com.didichuxing.doraemonkit:doraemonkit-aop:1.0.0'
> > 但编译一直报错，无法找到aop依赖
> > ERROR: Failed to resolve: com.didichuxing.doraemonkit:doraemonkit-aop:1.0.0
> > Show in Project Structure dialog
> > Affected Modules: app
> > 依赖配置
> > dependencies {
> > classpath 'com.android.tools.build:gradle:3.1.4'
> > classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.4'
> > }
> > 不配置aop，单独使用doraemonkit:1.1.8是可以正常使用的，这两个库放的是不同的仓库吗？aop的库需要做什么特殊处理吗？
> 
> 目前已经发布2.0.0版本，请升级以后再试下

2.0.0我仍然无法导入，2.0.0之前也尝试过，不知道这个库到底是什么问题
