### ISSUE TITLE
android Q 已经打开悬浮窗权限，但是还是 无法显示那个 入口

### ISSUE THREAD

**Issue by huanglaoxielwj** [didi/DoraemonKit#244]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

**Comment by huanglaoxielwj** [comment]
android Q 已经打开悬浮窗权限，但是还是 无法显示那个 入口

**Comment by wanglikun7342** [comment]
能提供更详细的信息吗，如机型和操作视频等

**Comment by jtsky** [comment]
> Please complete the following informations.
> 
> > Expected behavior and actual behavior.
> > Steps to reproduce the problem.
> > Android or iOS? OS version? Brand?
> > More informations such as error messages and stack traces are welcomed.
> 
> 请补充如下信息。
> 
> > 期望的表现和实际的表现。（如有）
> > 问题重现的步骤。（如有）
> > Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> > 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

目前已经发布2.0.0版本，请更新以后看下
