### ISSUE TITLE
Android接入后，activity切换悬浮标会先显示再隐藏。

### ISSUE THREAD

**Issue by ehangwork** [didi/DoraemonKit#247]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。
       anctivity切换始终显示。

> 问题重现的步骤。（如有）
     初始化后显示正常， 切换activity时会看到先显示一下浮层然后就被隐藏了。
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
    小米6X android9

> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

**Comment by jtsky** [comment]
> Please complete the following informations.
> 
> > Expected behavior and actual behavior.
> > Steps to reproduce the problem.
> > Android or iOS? OS version? Brand?
> > More informations such as error messages and stack traces are welcomed.
> 
> 请补充如下信息。
> 
> > 期望的表现和实际的表现。
> > anctivity切换始终显示。
> 
> > 问题重现的步骤。（如有）
> > 初始化后显示正常， 切换activity时会看到先显示一下浮层然后就被隐藏了。
> > Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> > 小米6X android9
> 
> > 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

我这边测试了一下好像并没有出现该问题，最近发布了2.0.0版本 请更新后试下
