### ISSUE TITLE
性能测试的数据报表能否导出？

### ISSUE THREAD

**Issue by JerryMR** [didi/DoraemonKit#248]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

哆唻爱梦的性能测试工具对开发来说十分方便，但测试想看性能测试的数据报表，想问一下哆唻爱梦是否已经支持导出性能测试数据？

**Comment by yixiangboy** [comment]
可以导出的，自定义测试完毕之后，会有toast提示，以json形式保存在沙盒中
