### ISSUE TITLE
ERROR: Failed to resolve: com.didichuxing.doraemonkit:doraemonkit:1.2.1

### ISSUE THREAD

**Issue by LiWeiQiangAndroid** [didi/DoraemonKit#252]
下载不下来，
repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url 'https://maven.fabric.io/public' }
    }

allprojects {
    repositories {
        google()
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven { url 'http://maven.aliyun.com/nexus/content/repositories/releases/' }
    }
}

**Comment by wanglikun7342** [comment]
1.2.1刚刚发布，你之前使用了错误的版本号

**Comment by LiWeiQiangAndroid** [comment]
1.2.0就可以
