### ISSUE TITLE
xcode打全局断点，每次启动都会在这里卡一下，然后手动continue一下又好了

### ISSUE THREAD

**Issue by wqforever** [didi/DoraemonKit#255]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> iOS 手机iPhone6 iOS8.4
![994DF9B96DC075444B53570314A0E9FB](https://user-images.githubusercontent.com/15868474/63068941-aa2a6880-bf47-11e9-890a-8064826850dc.jpg)

**Comment by yixiangboy** [comment]
无法复现，暂不修复。等有其他人反馈，再看
