### ISSUE TITLE
官方长期激励活动

### ISSUE THREAD

**Issue by yixiangboy** [didi/DoraemonKit#256]
# 官方长期激励活动
各位社区的朋友您们好：

为了鼓励更多的开发者参与到Dokit开源项目的共建中来，我们准备发起一个长期有效的激励活动，只要给我们提交PR，并被我们采纳的话，就有机会获得相应的奖品。

* 活动规则：每一个月为一次获奖周期，我们会统一评审本月所有被我们采纳的PR，挑选出前5名的贡献者，即可获得我们提供的奖品。
* 活动时间：2019-08-15~2019-12-31。
* 活动奖品：每个月前5的贡献者将会获得热门电影票一张，加入到我们首页的外部贡献者名单中。
* 原来提过PR并被采纳但是没有在我们外部贡献者名单的开发者可以私聊群主补上。
* 我们年底会评选出2~3名杰出贡献者，获得由滴滴技术委员会主席章文嵩老师签名的滴滴开源荣誉证书，还有机会参与到年度开源颁奖典礼。

#####  获奖证书如下：

![https://javer.oss-cn-shanghai.aliyuncs.com/2019/101.png](https://javer.oss-cn-shanghai.aliyuncs.com/2019/101.png)

#####  8月参与情况一览

1. [PR#245](https://github.com/didi/DoraemonKit/pull/245) github : https://github.com/zld   
2. [PR#250](https://github.com/didi/DoraemonKit/pull/250) [PR#251](https://github.com/didi/DoraemonKit/pull/251) github : https://github.com/Knight-ZXW   
3. [PR#258](https://github.com/didi/DoraemonKit/pull/258) [PR#262](https://github.com/didi/DoraemonKit/pull/262) github : https://github.com/klone1127  
4. [PR#259](https://github.com/didi/DoraemonKit/pull/259) [PR#261](https://github.com/didi/DoraemonKit/pull/261) [PR#270](https://github.com/didi/DoraemonKit/pull/270) github : https://github.com/DeveloperLY 
5. [PR#260](https://github.com/didi/DoraemonKit/pull/260) github : https://github.com/0xd-cc  
6. [PR#263](https://github.com/didi/DoraemonKit/pull/263) [PR#269](https://github.com/didi/DoraemonKit/pull/269) github : https://github.com/sagdragon
7. [PR#273](https://github.com/didi/DoraemonKit/pull/273) github : https://github.com/ccworld1000. 

8月份获奖名单：
[Knight-ZXW](https://github.com/Knight-ZXW)
[klone1127](https://github.com/klone1127)
[DeveloperLY](https://github.com/DeveloperLY)
[sagdragon](https://github.com/sagdragon)
[ccworld1000](https://github.com/ccworld1000)

9月份参与情况一览
1. [PR#293](https://github.com/didi/DoraemonKit/pull/293) github : https://github.com/0xd-cc
2. [PR#285](https://github.com/didi/DoraemonKit/pull/285) [PR#284](https://github.com/didi/DoraemonKit/pull/284) github:https://github.com/DeveloperLY 
3. [PR#273](https://github.com/didi/DoraemonKit/pull/273) [PR#276](https://github.com/didi/DoraemonKit/pull/276) [PR#280](https://github.com/didi/DoraemonKit/pull/280) github:https://github.com/ccworld1000
4. [PR#279](https://github.com/didi/DoraemonKit/pull/279) github : https://github.com/passerbyloo 
5. [PR#291](https://github.com/didi/DoraemonKit/pull/291) github : https://github.com/kaiattrib 
6. [PR#281](https://github.com/didi/DoraemonKit/pull/281) github : https://github.com/ydlsl

9月份获奖名单
[0xd-cc](https://github.com/0xd-cc)
[DeveloperLY](https://github.com/DeveloperLY)
[ccworld1000](https://github.com/ccworld1000)
[passerbyloo](https://github.com/passerbyloo)
[kaiattrib](https://github.com/kaiattrib)

10月份参与情况一览
1. [PR#294](https://github.com/didi/DoraemonKit/pull/294) [PR#300](https://github.com/didi/DoraemonKit/pull/300) github : https://github.com/DeveloperLY
2. [PR#295](https://github.com/didi/DoraemonKit/pull/295) github : https://github.com/passerbyloo
3. [PR#296](https://github.com/didi/DoraemonKit/pull/296)  [PR#297](https://github.com/didi/DoraemonKit/pull/297) github : https://github.com/J3n5en
4. [PR#298](https://github.com/didi/DoraemonKit/pull/298) [PR#299](https://github.com/didi/DoraemonKit/pull/299) github : https://github.com/goodleixiao

10月获奖名单
[DeveloperLY](https://github.com/DeveloperLY)
[passerbyloo](https://github.com/passerbyloo)
[J3n5en](https://github.com/J3n5en)
[goodleixiao](https://github.com/goodleixiao)

11月份参与情况一览
1.[PR#331](https://github.com/didi/DoraemonKit/pull/331)  [PR#329](https://github.com/didi/DoraemonKit/pull/329)  [PR#321](https://github.com/didi/DoraemonKit/pull/321) 
github:https://github.com/wangfengye
2.[PR#333](https://github.com/didi/DoraemonKit/pull/333) github:https://github.com/fachrifaul
3.[PR#327](https://github.com/didi/DoraemonKit/pull/327) github:https://github.com/passerbyloo
4.[PR#326](https://github.com/didi/DoraemonKit/pull/326) github:https://github.com/Liulinzhe17
5.[PR#325](https://github.com/didi/DoraemonKit/pull/325) github:https://github.com/coderxdotwang
6.[PR#316](https://github.com/didi/DoraemonKit/pull/316) github:https://github.com/kaiattrib
7.[PR#309](https://github.com/didi/DoraemonKit/pull/309) github:https://github.com/HDB-Li
8.[PR#307](https://github.com/didi/DoraemonKit/pull/307) github:https://github.com/DeveloperLY
9.[PR#305](https://github.com/didi/DoraemonKit/pull/305) github:https://github.com/cornerAnt
10.[PR#302](https://github.com/didi/DoraemonKit/pull/302) github:https://github.com/ccworld1000

11月获奖名单
[wangfengye](https://github.com/wangfengye)
[coderxdotwang](https://github.com/coderxdotwang)
[HDB-Li](https://github.com/HDB-Li)
[DeveloperLY](https://github.com/DeveloperLY)
[ccworld1000](https://github.com/ccworld1000)

12月份参与情况一览

1、[PR#365](https://github.com/didi/DoraemonKit/pull/365) github:https://github.com/ghbhaha
2、[PR#360](https://github.com/didi/DoraemonKit/pull/360) github:https://github.com/alvince
3、[PR#355](https://github.com/didi/DoraemonKit/pull/355) github:https://github.com/xiandanin
4、[PR#350](https://github.com/didi/DoraemonKit/pull/350) github:https://github.com/wangfengye
5、[PR#340](https://github.com/didi/DoraemonKit/pull/340) github:https://github.com/wangfengye
6、[PR#380](https://github.com/didi/DoraemonKit/pull/380) github:https://github.com/DeveloperLY
7、[PR#347](https://github.com/didi/DoraemonKit/pull/347) github:https://github.com/0xd-cc
8、[PR#344](https://github.com/didi/DoraemonKit/pull/344) github:https://github.com/0xd-cc
9、[PR#341](https://github.com/didi/DoraemonKit/pull/341) github:https://github.com/0xd-cc
10、[PR#343](https://github.com/didi/DoraemonKit/pull/343) github:https://github.com/Feijunjie
11、[PR#339](https://github.com/didi/DoraemonKit/pull/339) github:https://github.com/yu-jianfeng
12、[PR#338](https://github.com/didi/DoraemonKit/pull/338) github:https://github.com/klone1127
13、[PR#336](https://github.com/didi/DoraemonKit/pull/336) github:https://github.com/HDB-Li

12月获奖名单

[xiandanin](https://github.com/xiandanin)
[wangfengye](https://github.com/wangfengye)
[0xd-cc](https://github.com/0xd-cc)
[yu-jianfeng](https://github.com/yu-jianfeng)
[klone1127](https://github.com/klone1127)

暂未领奖的各位可以继续联系群主领奖，一直保留至2020年2月1号  

本次电影票活动截止到目前12月份为止已经全部结束  新的一年dokit将启动更多具有意义的新活动 大家敬请期待

**Comment by DeveloperLY** [comment]
![111567520969_ pic](https://user-images.githubusercontent.com/9148980/64323665-7e0a8080-cff7-11e9-8f0b-3ec1d3b441d1.jpg)
电影已经看完了，感谢，哈哈~

**Comment by klone1127** [comment]
电影已看过😁
<img width="412" alt="截屏2019-09-05下午3 57 47" src="https://user-images.githubusercontent.com/8508391/64326735-1820f780-cffd-11e9-9925-fe81427d1d65.png">

**Comment by kaiattrib** [comment]
成功收到电影票一张😆
