### ISSUE TITLE
[iOS] 关于大图检测功能的一些讨论

### ISSUE THREAD

**Issue by 0xd-cc** [didi/DoraemonKit#257]
嗨，@yixiangboy ：
「大图检测」被合并并发布后，自己用了一段时间，有一些考虑到可以优化的点，本来打算直接提pr优化，但是考虑之后，防止这些优化只考虑到自己的痛点，不够通用。所以，打算在issue区开个讨论，希望大家可以一起讨论一下：

**一、应用刚启动时加载的图片无法检测：**

	问题原因：因为需要手动打开开关，所以应用启动时加载的图是没法检测的
	解决方案：可以将开关状态存在`NSUserDefaults`，下次启动从`NSUserDefaults`取开关状态
	缺点：存在`NSUserDefaults`可能会存在开发人员一直忘关该开关，一直在检测图片

**二、已经缓存的图片不会被检测到**

	问题原因：第三方库会缓存图片，缓存过的图片直接从本地读取，不会通过网络请求，所以无法检测。
	解决方案1：提示手动清理缓存
	缺点：①. 麻烦 ②.可能某些应用没有清理缓存按钮，无法手动清理

	解决方案2: 打开开关后自动清理本地文件
	缺点：清理所有本地文件，可能会引发更多的问题，例如数据库文件被清理等。

	解决方案2: 打开开关后自动清理第三方库图片缓存（SDWebImage/ Kingfisher）
	缺点：① 所有图片都需要重新请求，但是因为是debug工具，不会影响到用户，所以副作用不大
	② 某些应用可能会修改缓存目录，导致清理失败

	解决方案3: 增加一个开关「开启并清理图片缓存」
	优点是清理作为可选项，适用场景更多，缺点还是：某些应用可能会修改缓存目录，导致清理失败

**三、是否需要自定义检测Size范围**

        问题原因：现在的逻辑是默认检测超过50k的图片，是否有必要新增设置检测size范围功能

**Comment by yixiangboy** [comment]
针对第一个问题：应用刚启动时加载的图片无法检测，的确可以在本地缓存一个开关，下一次启动生效。其实dokit很多功能目前已经是这么实现的，比如crash，mockGPS，日志监控等等，都会在dokit初始化的时候进行开关判断。
针对第二个问题： 我目前的处理方式是，hook住了SDwebImage的回调方法，在回调方法中进行处理的。详见UIImageView+DoraemonSDImage.h文件。
不过你提的打开开关，自动清理常用图片的缓存也是一个很好的思路，可以实现，具体图片的缓存位置，你看一下是否可以通过图片库的api获得。
针对第三个问题：我已经在DoraemonManager添加了bigImageDetectionSize属性进行控制。
给你点赞。

**Comment by yixiangboy** [comment]
我当时之所以要hook住sdwebimage的回调方法，是为了直接在图片上展示大图的信息，查看起来更加方便。

**Comment by 0xd-cc** [comment]
看来没有其他人参与讨论了，我先关了issue，然后去实现功能了
