### ISSUE TITLE
请问iOS 手动导入framework后还需要添加哪些系统库的依赖

### ISSUE THREAD

**Issue by RipperLiew** [didi/DoraemonKit#267]
我这边手动将framework1.1.9导入到项目中 提示报错：
:-1: Undefined symbol: _OBJC_CLASS_$_EKEventStore
:-1: Undefined symbol: _OBJC_CLASS_$_CNContactStore
:-1: Undefined symbol: _ABAddressBookGetAuthorizationStatus

**Comment by yixiangboy** [comment]
![https://javer.oss-cn-shanghai.aliyuncs.com/2019/github/mustF.jpg
](https://javer.oss-cn-shanghai.aliyuncs.com/2019/github/mustF.jpg
)

**Comment by Cyandnow** [comment]
![image](https://user-images.githubusercontent.com/12554248/83250852-51c50e80-a1db-11ea-93d1-7917bea562b1.png)
其他都没有问题了 剩这一个解决不了

**Comment by Cyandnow** [comment]
解决了, 没有带入 DoraemonLoadAnalyze.framework 这个库,
