### ISSUE TITLE
ios打出的包不包含MockGPS和WithLoad功能

### ISSUE THREAD

**Issue by xyh44934776** [didi/DoraemonKit#275]
pod按照如下配置：
  pod 'DoraemonKit/Core', '1.2.1', :configurations => ['Debug', 'Debug2Test', 'Release']
  pod 'DoraemonKit/WithGPS', '1.2.1', :configurations => ['Debug', 'Debug2Test', 'Release']
  pod 'DoraemonKit/WithLoad', '1.2.1', :configurations => ['Debug', 'Debug2Test', 'Release']
但是打出的ipa包没有Mock和WithLoad功能。

**Comment by yixiangboy** [comment]
本地暂时没法复现
