### ISSUE TITLE
“退出”按钮点击退出不了组件

### ISSUE THREAD

**Issue by aopi1125** [didi/DoraemonKit#277]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 点击退出应该能退出组件功能，目前点击无法关闭退出
> Android 系统

**Comment by jtsky** [comment]
我这边暂时无法复现该问题，能否提供更多信息帮助我们排查问题？或者把点击关闭的时候的详细日志贴上 谢谢

> Please complete the following informations.
> 
> > Expected behavior and actual behavior.
> > Steps to reproduce the problem.
> > Android or iOS? OS version? Brand?
> > More informations such as error messages and stack traces are welcomed.
> 
> 请补充如下信息。
> 
> > 点击退出应该能退出组件功能，目前点击无法关闭退出
> > Android 系统

我这边暂时无法复现该问题，能否提供更多信息帮助我们排查问题？或者把点击关闭的时候的详细日志贴上 谢谢

**Comment by jtsky** [comment]
> Please complete the following informations.
> 
> > Expected behavior and actual behavior.
> > Steps to reproduce the problem.
> > Android or iOS? OS version? Brand?
> > More informations such as error messages and stack traces are welcomed.
> 
> 请补充如下信息。
> 
> > 点击退出应该能退出组件功能，目前点击无法关闭退出
> > Android 系统
我这边暂时无法复现该问题，能否提供更多信息帮助我们排查问题？或者把点击关闭的时候的详细日志贴上 谢谢

**Comment by jtsky** [comment]
> Please complete the following informations.
> 
> > Expected behavior and actual behavior.
> > Steps to reproduce the problem.
> > Android or iOS? OS version? Brand?
> > More informations such as error messages and stack traces are welcomed.
> 
> 请补充如下信息。
> 
> > 点击退出应该能退出组件功能，目前点击无法关闭退出
> > Android 系统

我这边暂时无法复现该问题，能否提供更多信息帮助我们排查问题？或者把点击关闭的时候的详细日志贴上 谢谢
