### ISSUE TITLE
缺少部分机型判断（例如：XR）

### ISSUE THREAD

**Issue by zhu410289616** [didi/DoraemonKit#28]
DoraemonAppInfoUtil文件中的 + (NSString *)iphoneType 方法缺少新机型支持。

**Comment by tigerZhang86** [comment]
> DoraemonAppInfoUtil文件中的 + (NSString *)iphoneType 方法缺少新机型支持。

提个 PR

**Comment by yixiangboy** [comment]
tag : 1.1.4已经解决
