### ISSUE TITLE
关于DoraemonKit屏幕旋转问题.

### ISSUE THREAD

**Issue by honbolau** [didi/DoraemonKit#283]
当前的APP禁止屏幕旋转了, DoraemonKit还是会屏幕旋转

**Comment by jtsky** [comment]
> 当前的APP禁止屏幕旋转了, DoraemonKit还是会屏幕旋转

新版本已修复

**Comment by honbolau** [comment]
> > 当前的APP禁止屏幕旋转了, DoraemonKit还是会屏幕旋转
> 
> 新版本已修复

@jtsky 请问在哪里修改的这个问题,,我想知道一下如何解决这个问题的  麻烦了
