### ISSUE TITLE
iOS 9.0 statusBarStyle 无法正常切换

### ISSUE THREAD

**Issue by c344081** [didi/DoraemonKit#286]
请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
1. 调用install即可重现
2. 使用View controller-based status bar appearance, 10.0以上似乎不能复现
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
iOS 9.3.5 iPhone 4S
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

**Comment by yixiangboy** [comment]
欢迎升级到最新版本。http://www.dokit.cn
