### ISSUE TITLE
Double-Checked Locking

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [didi/DoraemonKit#288]
https://github.com/didi/DoraemonKit/blob/90d8bb99e02390ce82a9d36e5844f0bcd84d0a57/Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/util/threadpool/ThreadPoolProxyFactory.java#L4-L15

Double-Checked Locking is widely cited and used as an efficient method for implementing lazy initialization in a multithreaded environment.
Unfortunately, it will not work reliably in a platform independent way when implemented in Java, without additional synchronization.
declares the mThreadPoolProxy field volatile offers a much more elegant solution

**Comment by jtsky** [comment]
> https://github.com/didi/DoraemonKit/blob/90d8bb99e02390ce82a9d36e5844f0bcd84d0a57/Android/doraemonkit/src/main/java/com/didichuxing/doraemonkit/util/threadpool/ThreadPoolProxyFactory.java#L4-L15
> 
> Double-Checked Locking is widely cited and used as an efficient method for implementing lazy initialization in a multithreaded environment.
> Unfortunately, it will not work reliably in a platform independent way when implemented in Java, without additional synchronization.
> declares the mThreadPoolProxy field volatile offers a much more elegant solution

看了一下 该方法只有一个地方被调用 影响不是很大
