### ISSUE TITLE
iOS『App基本信息』模块的网络权限判断有误

### ISSUE THREAD

**Issue by codingiran** [didi/DoraemonKit#29]
### 运行环境

- [x] 设备：`All` 
- [x] 系统：`iOS 12.1`
- [x] Xcode 版本：`10.1`
- [x] DoraemonKit 版本：`1.0.3`

### 具体问题
实际上设备已经完全授权了网络权限，但```CTCellularDataRestrictedState```查询网络授权状态 有误：
![image](https://user-images.githubusercontent.com/11780294/50874811-6b0bc600-1400-11e9-8952-c8915a5012e4.png)

### 可能原因
```CTCellularData```这个类设计成所有的状态变化都通过```cellularDataRestrictionDidUpdateNotifier```来触发，必须在其```block```内获取状态信息
![image](https://user-images.githubusercontent.com/11780294/50874932-03a24600-1401-11e9-873d-dda7c04c402a.png)

### 其他
- 另外需要注意的是：在模拟器上
```typedef void (^CellularDataRestrictionDidUpdateNotifier)(CTCellularDataRestrictedState);```这个回调是不会进的，不过模拟上对网络权限也没啥好判断的😓

- ```CTCellularData```这个类有局限性，只能判断出：**未知**、**完全授权(蜂窝 && WIFI)** 以及 **不完全授权(only WIFI || both 关闭)**，如果需要更详尽的判断可以参考[简书: 检测 iOS 系统网络权限被关闭
](https://www.jianshu.com/p/81d0b7f06eba)  *MARK: 作者在DoraemonKit群里 @Zie*

**Comment by yixiangboy** [comment]
多谢 tag:1.1.4 已经解决

**Comment by xuanyuelin** [comment]
how to distinguish only wifi or both closed at kCTCellularDataRestricted ?
