### ISSUE TITLE
DoraemonLoadAnalyze有考虑开源么

### ISSUE THREAD

**Issue by geemaple** [didi/DoraemonKit#290]
RT

**Comment by yixiangboy** [comment]
已经开源 在同一目录下

**Comment by geemaple** [comment]
嗯，已经找到了 https://github.com/didi/DoraemonKit/blob/a79bb82b7bb77a2617120f7e77b61dbe53ac4b50/iOS/DoraemonLoadAnalyzeDemo/DoraemonLoadAnalyze/DoraemonLoadAnalyze.mm
