### ISSUE TITLE
Android 1.2.7 app name

### ISSUE THREAD

**Issue by Richard-Cao** [didi/DoraemonKit#304]
为什么升级到1.2.7版本之后，Android app名字会变成DoraemonKit？

**Comment by jtsky** [comment]
> 为什么升级到1.2.7版本之后，Android app名字会变成DoraemonKit？

1.2.8版本已修复 请升级一下 不好意思

**Comment by Richard-Cao** [comment]
老哥，怎么修复的？我看没提代码啊

**Comment by Richard-Cao** [comment]
还有 debugImplementation 'com.didichuxing.doraemonkit:doraemonkit-leakcanary:1.2.7' 这个拉不下来

**Comment by jtsky** [comment]
> 还有 debugImplementation 'com.didichuxing.doraemonkit:doraemonkit-leakcanary:1.2.7' 这个拉不下来

我刚更新了一个1.2.8版本 你升级一下 这个是由于我内部的app_name 把你的给覆盖了 不好意思

**Comment by Richard-Cao** [comment]
是不是你们内部更新版本不会很及时的同步到开源仓库？其实我还挺想知道你们是怎么覆盖的。

**Comment by Richard-Cao** [comment]
文档也得改了，不然会有更多人遇到这个问题。现在看起来你们会先内部发版本，这个仓库的更新是延后的，能不能尽量能够同步的更新呢？很多人都会关注最新的改动呢

**Comment by jtsky** [comment]
> 文档也得改了，不然会有更多人遇到这个问题。现在看起来你们会先内部发版本，这个仓库的更新是延后的，能不能尽量能够同步的更新呢？很多人都会关注最新的改动呢

你再看下文档  我已经改过了
