### ISSUE TITLE
因为Cocoapods的原因， 目前不支持单独在Debug环境安装该Pod的Subspec

### ISSUE THREAD

**Issue by roshanman** [didi/DoraemonKit#306]
`[!] The subspecs of `DoraemonKit` are linked to different build configurations for the `Pods-XXXX` target. CocoaPods does not currently support subspecs across different build configurations.`

args = {
    :git => 'https://github.com/didi/DoraemonKit.git', 
    :tag => '1.2.5', 
    :modular_headers => true, 
    :configurations => ['Debug'] #必选
  }

  pod 'DoraemonKit/Core',             args
  pod 'DoraemonKit/WithMLeaksFinder', args
  pod 'DoraemonKit/WithGPS',          args
  pod 'DoraemonKit/WithLoad',         args

**Comment by DeveloperLY** [comment]
1.2.5 都还没发布

**Comment by yixiangboy** [comment]
1.2.5还没发布呢，目前最新是1.2.4

**Comment by roshanman** [comment]
我指定了git目录，所以可以用1.2.5
而且即使我换成低版本的问题依然还是有
请问下我应该怎么只在Debug环境下依赖DoraemonKit

**Comment by yixiangboy** [comment]
pod 'DoraemonKit/Core', '~> 1.2.4', :configurations => ['Debug'] //必选

**Comment by roshanman** [comment]
我还想用其他的工具 WithMLeaksFinder, WithGPS, WithLoad
但是我估计直接依赖源码的方式估计是不行了，等Cocoapods升级吧

我提供一个解决方法给后面遇到同样问题的人参考一下吧，
我们可以手动编译编一个集成了所有subspec的framework
然后再弄一个私有库依赖这个framework

**Comment by Cyandnow** [comment]
> 手动编译编一个集成了所有subspec的framework

这个应该如何实现呢, 我用 pod package 的话, 会报一个错误

`
Undefined symbols for architecture armv7:

  '_dlaLoadModels', referenced from:

      -[DoraemonMethodUseTimeManager fixLoadModelArray] in DoraemonKit(DoraemonMethodUseTimeManager.o)

      -[DoraemonMethodUseTimeManager fixLoadModelArrayForHealth] in DoraemonKit(DoraemonMethodUseTimeManager.o)

ld: symbol(s) not found for architecture armv7
`
