### ISSUE TITLE
1.2.8Caused by: java.lang.NullPointerException；UIUtils.getDokitAppContentView(activity).setId(R.id.dokit_app_contentview_id);

### ISSUE THREAD

**Issue by jxerjh** [didi/DoraemonKit#308]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setId(int)' on a null object reference
        at com.didichuxing.doraemonkit.DoraemonKit$2.onActivityResumed(DoraemonKit.java:204)
        at android.app.Application.dispatchActivityResumed(Application.java:218)
        at android.app.Activity.onResume(Activity.java:1345)
        at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:514)
        at com.yunji.imaginer.base.activity.BaseYJActivity.onResume(BaseYJActivity.java:201)
        at com.yunji.imaginer.personalized.base.BaseBizActivity.onResume(BaseBizActivity.java:27)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1355)
        at android.app.Activity.performResume(Activity.java:7182)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3626)
源码出错位置：
1. DoraemonKit         
     //设置app的直接子view的Id
     UIUtils.getDokitAppContentView(activity).setId(R.id.dokit_app_contentview_id);
2.UIUtils
    public static View getDokitAppContentView(Activity activity) {
        View mAppContentView = activity.findViewById(R.id.dokit_app_contentview_id);
        if (mAppContentView != null) {
            return mAppContentView;
        }
        FrameLayout decorView = (FrameLayout) activity.getWindow().getDecorView();

        for (int index = 0; index < decorView.getChildCount(); index++) {
            View child = decorView.getChildAt(index);
            //解决与布局边框工具冲突的问题
            if (child instanceof LinearLayout || child instanceof ViewBorderFrameLayout) {
                if (child instanceof ViewBorderFrameLayout) {
                    mAppContentView = ((ViewBorderFrameLayout) child).getChildAt(0);
                } else {
                    mAppContentView = child;
                }
                break;
            }
        }

        return mAppContentView;
    }

因为child布局是SwipeBackLayout extends FrameLayout，导致获取的mAppContentView=null，所以UIUtils.getDokitAppContentView(activity).setId(R.id.dokit_app_contentview_id);报了NullPointerException，麻烦1.2.8版本源码解决下这个问题
————————————————
接入版本1.2.8

**Comment by jtsky** [comment]
> Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setId(int)' on a null object reference
> at com.didichuxing.doraemonkit.DoraemonKit$2.onActivityResumed(DoraemonKit.java:204)
> at android.app.Application.dispatchActivityResumed(Application.java:218)
> at android.app.Activity.onResume(Activity.java:1345)
> at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:514)
> at com.yunji.imaginer.base.activity.BaseYJActivity.onResume(BaseYJActivity.java:201)
> at com.yunji.imaginer.personalized.base.BaseBizActivity.onResume(BaseBizActivity.java:27)
> at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1355)
> at android.app.Activity.performResume(Activity.java:7182)
> at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3626)
> 源码出错位置：
> 
> 1. DoraemonKit
>    //设置app的直接子view的Id
>    UIUtils.getDokitAppContentView(activity).setId(R.id.dokit_app_contentview_id);
>    2.UIUtils
>    public static View getDokitAppContentView(Activity activity) {
>    View mAppContentView = activity.findViewById(R.id.dokit_app_contentview_id);
>    if (mAppContentView != null) {
>    return mAppContentView;
>    }
>    FrameLayout decorView = (FrameLayout) activity.getWindow().getDecorView();
>    ```
>     for (int index = 0; index < decorView.getChildCount(); index++) {
>         View child = decorView.getChildAt(index);
>         //解决与布局边框工具冲突的问题
>         if (child instanceof LinearLayout || child instanceof ViewBorderFrameLayout) {
>             if (child instanceof ViewBorderFrameLayout) {
>                 mAppContentView = ((ViewBorderFrameLayout) child).getChildAt(0);
>             } else {
>                 mAppContentView = child;
>             }
>             break;
>         }
>     }
>    
>     return mAppContentView;
>    ```
>    
>    
>    }
> 
> 因为child布局是SwipeBackLayout extends FrameLayout，导致获取的mAppContentView=null，所以UIUtils.getDokitAppContentView(activity).setId(R.id.dokit_app_contentview_id);报了NullPointerException，麻烦1.2.8版本源码解决下这个问题
> ————————————————
> 接入版本1.2.8

你好 该bug已修复 我们近期会发布版本更新 请关注
