### ISSUE TITLE
Android layout_anchorGravity属性冲突

### ISSUE THREAD

**Issue by iamlocky** [didi/DoraemonKit#310]
Android resource compilation failed
duplicate value for resource 'attr/layout_anchorGravity' with config ''
resource previously defined here.
项目中没有定义该属性，应该是和其他第三方库重名了，希望能给属性命名加上前缀区分

**Comment by jtsky** [comment]
> Android resource compilation failed
> duplicate value for resource 'attr/layout_anchorGravity' with config ''
> resource previously defined here.
> 项目中没有定义该属性，应该是和其他第三方库重名了，希望能给属性命名加上前缀区分

我查了一下layout_anchorGravity这个属性是系统库CoordinatorLayout里的一个attr属性，应该是support版本冲突了，或者你引用的第三方库里有相同的属性。方便问下你的android support扩展库的版本是多少吗？我这边是27.1.1。
