### ISSUE TITLE
出现crash

### ISSUE THREAD

**Issue by www851903307** [didi/DoraemonKit#313]
Android手机，依赖版本为2.0.0

Fatal Exception: java.lang.NullPointerException:Attempt to invoke virtual method 'boolean com.didichuxing.doraemonkit.ui.dialog.DialogProvider.isCancellable()' on a null object reference
at com.didichuxing.doraemonkit.ui.dialog.UniversalDialogFragment.onCreateView(UniversalDialogFragment.java:43)

**Comment by jtsky** [comment]
> Android手机，依赖版本为2.0.0
> 
> Fatal Exception: java.lang.NullPointerException:Attempt to invoke virtual method 'boolean com.didichuxing.doraemonkit.ui.dialog.DialogProvider.isCancellable()' on a null object reference
> at com.didichuxing.doraemonkit.ui.dialog.UniversalDialogFragment.onCreateView(UniversalDialogFragment.java:43)

已修复，近期会随着下个版本一起发布
