### ISSUE TITLE
查看日志不自动更新

### ISSUE THREAD

**Issue by wangfengye** [didi/DoraemonKit#315]
> 查看log日志
> 开启日志功能后,只显示打开日志时刻之前的日志,之后日志不显示
>Android 7.1.1 锤子OS103

**Comment by jtsky** [comment]
> > 查看log日志
> > 开启日志功能后,只显示打开日志时刻之前的日志,之后日志不显示
> > Android 7.1.1 锤子OS103

“ 欢迎更新到3.0_beta1版本 ，应该已经解决，接入手册详见 http://www.dokit.cn/ 使用中心“
