### ISSUE TITLE
跳转到其他支持库Weex或leakCannary的Activiy应用崩溃

### ISSUE THREAD

**Issue by lodqc** [didi/DoraemonKit#317]
>按照安卓文档集成，点击leakCannary，Weex信息和DevTool按钮应用崩溃
> Android ，系统版本9.1.0，荣耀10
> Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?

**Comment by lodqc** [comment]
使用DoraemonKit版本
debugImplementation 'com.didichuxing.doraemonkit:doraemonkit:2.0.0'
releaseImplementation 'com.didichuxing.doraemonkit:doraemonkit-no-op:2.0.0'
implementation 'com.squareup.okhttp3:okhttp:3.12.1'
debugImplementation 'com.didichuxing.doraemonkit:doraemonkit-weex:2.0.0'
releaseImplementation 'com.didichuxing.doraemonkit:doraemonkit-weex-no-op:2.0.0'
debugImplementation 'com.didichuxing.doraemonkit:doraemonkit-leakcanary:2.0.0'

**Comment by jtsky** [comment]
> Calling startActivity() from outside of an Activity context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want

新增intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK),并不是所有手机都会出现崩溃,所以我们会随着下个版本发布修复
