### ISSUE TITLE
一个关于悬浮窗的小问题

### ISSUE THREAD

**Issue by songdehuai** [didi/DoraemonKit#319]
接入了DoKit的都知道它有一个悬浮窗，现在默认是常规模式，这个模式下有个小问题。

    在非全屏activity下，悬浮窗会把这个非全屏的activity撑大。切换至系统级的悬浮窗即可。可以的话，希望能弄个机制解决一下，否则可能会影响应用的正常显示。一部分没发现这个细节的，可能就会反复的去改一个不存在的问题。

**Comment by jtsky** [comment]
> ```
> 接入了DoKit的都知道它有一个悬浮窗，现在默认是常规模式，这个模式下有个小问题。
> 
> 在非全屏activity下，悬浮窗会把这个非全屏的activity撑大。切换至系统级的悬浮窗即可。可以的话，希望能弄个机制解决一下，否则可能会影响应用的正常显示。一部分没发现这个细节的，可能就会反复的去改一个不存在的问题。
> ```

可以详细描述一下 或者截个图传上来看一下效果吗 我没有很明白你的意思

**Comment by songdehuai** [comment]
> > ```
> > 接入了DoKit的都知道它有一个悬浮窗，现在默认是常规模式，这个模式下有个小问题。
> > 
> > 在非全屏activity下，悬浮窗会把这个非全屏的activity撑大。切换至系统级的悬浮窗即可。可以的话，希望能弄个机制解决一下，否则可能会影响应用的正常显示。一部分没发现这个细节的，可能就会反复的去改一个不存在的问题。
> > ```
> 
> 可以详细描述一下 或者截个图传上来看一下效果吗 我没有很明白你的意思

https://pan.baidu.com/s/1eSYzCvtnwiFWr0ZOKla0hA
录了一个视频

**Comment by jtsky** [comment]
> > > ```
> > > 接入了DoKit的都知道它有一个悬浮窗，现在默认是常规模式，这个模式下有个小问题。
> > > 
> > > 在非全屏activity下，悬浮窗会把这个非全屏的activity撑大。切换至系统级的悬浮窗即可。可以的话，希望能弄个机制解决一下，否则可能会影响应用的正常显示。一部分没发现这个细节的，可能就会反复的去改一个不存在的问题。
> > > ```
> > 
> > 
> > 可以详细描述一下 或者截个图传上来看一下效果吗 我没有很明白你的意思
> 
> https://pan.baidu.com/s/1eSYzCvtnwiFWr0ZOKla0hA
> 录了一个视频

你的遮罩弹窗是一个activity是吧？

**Comment by GeeJoe** [comment]
可以动态设置悬浮窗为系统模式吗

**Comment by jtsky** [comment]
> 可以动态设置悬浮窗为系统模式吗

动态设置悬浮窗为系统模式是什么意思？

**Comment by jtsky** [comment]
> > > ```
> > > 接入了DoKit的都知道它有一个悬浮窗，现在默认是常规模式，这个模式下有个小问题。
> > > 
> > > 在非全屏activity下，悬浮窗会把这个非全屏的activity撑大。切换至系统级的悬浮窗即可。可以的话，希望能弄个机制解决一下，否则可能会影响应用的正常显示。一部分没发现这个细节的，可能就会反复的去改一个不存在的问题。
> > > ```
> > 
> > 
> > 可以详细描述一下 或者截个图传上来看一下效果吗 我没有很明白你的意思
> 
> https://pan.baidu.com/s/1eSYzCvtnwiFWr0ZOKla0hA
> 录了一个视频

可以考虑切换成系统模式试一下

**Comment by jtsky** [comment]
> 可以动态设置悬浮窗为系统模式吗

欢迎更新到3.0_beta1版本 ，接入手册详见 http://www.dokit.cn/ 使用中心“
