### ISSUE TITLE
Android 4.4的设备上，安装时报错，别的设备没什么问题

### ISSUE THREAD

**Issue by igding** [didi/DoraemonKit#320]
java.lang.RuntimeException: Unable to get provider com.didichuxing.doraemonkit.DebugFileProvider: java.lang.ClassNotFoundException: Didn't find class "com.didichuxing.doraemonkit.DebugFileProvider" on path: DexPathList[[zip file "/data/app/com.qccvas.org.quantumcloudyards-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.qccvas.org.quantumcloudyards-2, /vendor/lib, /system/lib]]

**Comment by jtsky** [comment]
> java.lang.RuntimeException: Unable to get provider com.didichuxing.doraemonkit.DebugFileProvider: java.lang.ClassNotFoundException: Didn't find class "com.didichuxing.doraemonkit.DebugFileProvider" on path: DexPathList[[zip file "/data/app/com.qccvas.org.quantumcloudyards-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.qccvas.org.quantumcloudyards-2, /vendor/lib, /system/lib]]

你好 我刚在安卓4.4的模拟器上跑过没有出现你说说的问题  我猜测应该是分包问题导致的 建议你在项目中添加multidex试试
