### ISSUE TITLE
文件占用问题.

### ISSUE THREAD

**Issue by wangfengye** [didi/DoraemonKit#322]
> 下载项目源码自己修改调试.install时 偶尔出现文件占用异常.(一般重复install几次后出现,重启AS后正常)
> Win10 ,AS3.5.2

![image](https://user-images.githubusercontent.com/19565572/68839326-73f1b600-06fb-11ea-98d7-be39d144a78a.png)
> 我曾经遇到过类似异常,只在win上出现,mac正常,后来排查是编译期操作字节码的部分流没有释放,win系统下,同时只能一个流持有一个文件.而mac系统,只要流不在使用中,其他流也能操作同一个文件,

**Comment by jtsky** [comment]
> > 下载项目源码自己修改调试.install时 偶尔出现文件占用异常.(一般重复install几次后出现,重启AS后正常)
> > Win10 ,AS3.5.2
> 
> ![image](https://user-images.githubusercontent.com/19565572/68839326-73f1b600-06fb-11ea-98d7-be39d144a78a.png)
> 
> > 我曾经遇到过类似异常,只在win上出现,mac正常,后来排查是编译期操作字节码的部分流没有释放,win系统下,同时只能一个流持有一个文件.而mac系统,只要流不在使用中,其他流也能操作同一个文件,

这个问题我曾经在windows平台上也经常碰到  但是在mac基本上没有遇到过 这个应该是as在windows平台上的bug 建议升级as试试
