### ISSUE TITLE
阿里仓库里一直没有同步

### ISSUE THREAD

**Issue by devilived** [didi/DoraemonKit#323]
阿里public仓库上doraemon的版本只有1.2.1。 只要在gradle中配置阿里镜像，就会找不到最新的包。

**Comment by zyl5721451** [comment]
正解

**Comment by jtsky** [comment]
> 阿里public仓库上doraemon的版本只有1.2.1。 只要在gradle中配置阿里镜像，就会找不到最新的包。

我去阿里云的镜像上看了一下是有同步的
![阿里云](https://user-images.githubusercontent.com/4486497/69022128-3b9cf100-09f5-11ea-8d7c-2796799032fe.png)

**Comment by DaveBoy** [comment]
同样的问题  导致我正常项目引用阿里仓库build失败，不用阿里仓库反而没问题

**Comment by zyl5721451** [comment]
classpath 'com.github.franticn:gradle_plugin_android_aspectjx:2.0.6'，这个包也下载不下来，一直同步失败

**Comment by zyl5721451** [comment]
> > 阿里public仓库上doraemon的版本只有1.2.1。 只要在gradle中配置阿里镜像，就会找不到最新的包。
> 
> 我去阿里云的镜像上看了一下是有同步的
> ![阿里云](https://user-images.githubusercontent.com/4486497/69022128-3b9cf100-09f5-11ea-8d7c-2796799032fe.png)

Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find doraemonkit.jar (com.didichuxing.doraemonkit:doraemonkit:2.0.1).
Searched in the following locations:
    http://maven.aliyun.com/nexus/content/groups/public/com/didichuxing/doraemonkit/doraemonkit/2.0.1/doraemonkit-2.0.1.jar

阿里仓库找不到doraemonkit-2.0.1.jar，我看仓库中没有这个文件，只有一个doraemonkit-2.0.1.arr，报的错误如上所示

**Comment by jtsky** [comment]
> > > 阿里public仓库上doraemon的版本只有1.2.1。 只要在gradle中配置阿里镜像，就会找不到最新的包。
> > 
> > 
> > 我去阿里云的镜像上看了一下是有同步的
> > ![阿里云](https://user-images.githubusercontent.com/4486497/69022128-3b9cf100-09f5-11ea-8d7c-2796799032fe.png)
> 
> Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find doraemonkit.jar (com.didichuxing.doraemonkit:doraemonkit:2.0.1).
> Searched in the following locations:
> http://maven.aliyun.com/nexus/content/groups/public/com/didichuxing/doraemonkit/doraemonkit/2.0.1/doraemonkit-2.0.1.jar
> 
> 阿里仓库找不到doraemonkit-2.0.1.jar，我看仓库中没有这个文件，只有一个doraemonkit-2.0.1.arr，报的错误如上所示

那去掉阿里仓库 直接用默认的jcenter仓库能拉下来吗 或者挂个vpn试试？

**Comment by zyl5721451** [comment]
去掉阿里仓库，可以

**Comment by jtsky** [comment]
> 去掉阿里仓库，可以

恩  好的 这也是as的一个bug 按照正常的逻辑 它应该会去每个仓库去拉 直到拉到 但是有时候好像不起作用
