### ISSUE TITLE
DBViewPC访问功能优化.

### ISSUE THREAD

**Issue by wangfengye** [didi/DoraemonKit#330]
> 今天使用时发现手机自动切换wifi后,应用上没有体现.浪费调试时间.
> 我修改源码,新增了网络状态监听,自动启动,关闭服务.
```
    @NetWork(NetType.WIFI)
    public void listenWifi(NetType type) {
        if (type == NetType.NONE) {
            DebugDB.shutDown();
            TextView tvIp = findViewById(R.id.tv_ip);
            tvIp.setText("servse is not start");
        } else {
            initView();
        }
    }
```
##  我想问的有几点
1. 这个功能有必要吗
2. 如果有必要.提示是只在DBView上,还是做全局的提示.

**Comment by jtsky** [comment]
> > 今天使用时发现手机自动切换wifi后,应用上没有体现.浪费调试时间.
> > 我修改源码,新增了网络状态监听,自动启动,关闭服务.
> 
> ```
>     @NetWork(NetType.WIFI)
>     public void listenWifi(NetType type) {
>         if (type == NetType.NONE) {
>             DebugDB.shutDown();
>             TextView tvIp = findViewById(R.id.tv_ip);
>             tvIp.setText("servse is not start");
>         } else {
>             initView();
>         }
>     }
> ```
> 
> ## 我想问的有几点
> 1. 这个功能有必要吗
> 2. 如果有必要.提示是只在DBView上,还是做全局的提示.

好的 我这边全局监听一下网络变化 重启dbview的服务

**Comment by jtsky** [comment]
> > 今天使用时发现手机自动切换wifi后,应用上没有体现.浪费调试时间.
> > 我修改源码,新增了网络状态监听,自动启动,关闭服务.
> 
> ```
>     @NetWork(NetType.WIFI)
>     public void listenWifi(NetType type) {
>         if (type == NetType.NONE) {
>             DebugDB.shutDown();
>             TextView tvIp = findViewById(R.id.tv_ip);
>             tvIp.setText("servse is not start");
>         } else {
>             initView();
>         }
>     }
> ```
> 
> ## 我想问的有几点
> 1. 这个功能有必要吗
> 2. 如果有必要.提示是只在DBView上,还是做全局的提示.

欢迎给我们提PR 我合到master分支上

**Comment by wangfengye** [comment]
提交了一个[PR](https://github.com/didi/DoraemonKit/pull/331);
我还有些想法.
1. 增加网络监听网络变化对低版的兼容.
2. 增加一个sharedPreference,用于判断是否开启DBView,避免不需要的时候开启.
3. 增加一个API,控制各个功能模块自动启动.遇到的问题是,`Ikit.onAppInit()`函数执行时,activity未创建.无法添加监控界面.感觉要加个首个activity加载的api.
4. `IKit`没有提供销毁回调,一般IKit都是全局的用到很少,我改后DBView模块增加了全局网络监听.没有注销操作,虽然是全局的监听,没啥影响,但还是感觉不太好
