### ISSUE TITLE
Android使用高德定位，无法模拟位置

### ISSUE THREAD

**Issue by bailibaili** [didi/DoraemonKit#335]
```
机型是：mate20   android 9
打开并设置模拟位置嘉兴市坐标120.750865,30.762653，但是还是输出北京
//高德client
AMapLocationClient client = LocationUtils.getDefaultClient(getApplicationContext());
client.setLocationListener(aMapLocation -> {
                    Log.e("位置", aMapLocation.getLatitude() + "---" + aMapLocation.getLongitude());
                });
client.startLocation();
```
demo中只有这一句错误
```com.didichuxing.doraemondemo E/LocationManager: thread is not runable, msg ignore, state:TIMED_WAITING, pkg:com.didichuxing.doraemondemo```

**Comment by 176569797** [comment]
机型是：荣耀8 Android8
定位权限授予正常，高德定位位置正常且准确，进行模拟定位以后，高德输出的日志显示定位信息都是空，文字提示是：缺少定位权限#locationDetail=获取到的基站为空，并且获取WIFI权限被禁用,请在安全软件中打开应用的定位权限

**Comment by jtsky** [comment]
> ```
> 机型是：mate20   android 9
> 打开并设置模拟位置嘉兴市坐标120.750865,30.762653，但是还是输出北京
> //高德client
> AMapLocationClient client = LocationUtils.getDefaultClient(getApplicationContext());
> client.setLocationListener(aMapLocation -> {
>                     Log.e("位置", aMapLocation.getLatitude() + "---" + aMapLocation.getLongitude());
>                 });
> client.startLocation();
> ```
> 
> demo中只有这一句错误
> `com.didichuxing.doraemondemo E/LocationManager: thread is not runable, msg ignore, state:TIMED_WAITING, pkg:com.didichuxing.doraemondemo`

我问过做这个功能的同事了  他说这块确实有点问题 近期修复掉 谢谢你的issue

**Comment by bailibaili** [comment]
> > ```
> > 机型是：mate20   android 9
> > 打开并设置模拟位置嘉兴市坐标120.750865,30.762653，但是还是输出北京
> > //高德client
> > AMapLocationClient client = LocationUtils.getDefaultClient(getApplicationContext());
> > client.setLocationListener(aMapLocation -> {
> >                     Log.e("位置", aMapLocation.getLatitude() + "---" + aMapLocation.getLongitude());
> >                 });
> > client.startLocation();
> > ```
> > 
> > 
> > demo中只有这一句错误
> > `com.didichuxing.doraemondemo E/LocationManager: thread is not runable, msg ignore, state:TIMED_WAITING, pkg:com.didichuxing.doraemondemo`
> 
> 我问过做这个功能的同事了 他说这块确实有点问题 近期修复掉 谢谢你的issue

好的，非常感谢，辛苦

**Comment by jtsky** [comment]
> > > ```
> > > 机型是：mate20   android 9
> > > 打开并设置模拟位置嘉兴市坐标120.750865,30.762653，但是还是输出北京
> > > //高德client
> > > AMapLocationClient client = LocationUtils.getDefaultClient(getApplicationContext());
> > > client.setLocationListener(aMapLocation -> {
> > >                     Log.e("位置", aMapLocation.getLatitude() + "---" + aMapLocation.getLongitude());
> > >                 });
> > > client.startLocation();
> > > ```
> > > 
> > > 
> > > demo中只有这一句错误
> > > `com.didichuxing.doraemondemo E/LocationManager: thread is not runable, msg ignore, state:TIMED_WAITING, pkg:com.didichuxing.doraemondemo`
> > 
> > 
> > 我问过做这个功能的同事了 他说这块确实有点问题 近期修复掉 谢谢你的issue
> 
> 好的，非常感谢，辛苦

dokit 最新2.2.1已经支持高德定位 请及时更新sdk
