### ISSUE TITLE
iOS会导致UIMenuController无法显示，比如系统自带的复制、粘贴

### ISSUE THREAD

**Issue by lilong7676** [didi/DoraemonKit#337]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
iOS 13.2.3 iPhone7plus
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

**Comment by ydlsl** [comment]
您的问题，现在还存在吗？

**Comment by lilong7676** [comment]
> 您的问题，现在还存在吗？

还是存在哦。

**Comment by danjiang** [comment]
什么狗屁玩意，也要开源

**Comment by yixiangboy** [comment]
问题已修复 3月中旬会对外发布一个新版本解决。

**Comment by jeckCai** [comment]
ios13.3 还是无法复制，粘贴等。

**Comment by yixiangboy** [comment]
代码还没发版

**Comment by yixiangboy** [comment]
欢迎更新到3.0beta1版本 ，已经解决，接入手册详见 http://www.dokit.cn/ 试用中心
