### ISSUE TITLE
"模拟弱网"在你们的Demo上面有效，但是在我的应用里面无效

### ISSUE THREAD

**Issue by Qiwang-CHEN** [didi/DoraemonKit#345]
其他的功能基本有效，但是"模拟弱网"在你们的Demo上面有效，但是在我的应用里面无效，设备为Honor 8C，HUAWEI M6，在配置的时候只加了这一句
“ 
 DoraemonKit.install(getApplication());  
”，
与这些
“
debugImplementation 'com.didichuxing.doraemonkit:doraemonkit:2.0.1'
releaseImplementation 'com.didichuxing.doraemonkit:doraemonkit-no-op:2.0.2'
implementation 'com.squareup.okhttp3:okhttp:3.12.1'

“，
配置应该没问题吧！

**Comment by jtsky** [comment]
> 其他的功能基本有效，但是"模拟弱网"在你们的Demo上面有效，但是在我的应用里面无效，设备为Honor 8C，HUAWEI M6，在配置的时候只加了这一句
> “
> DoraemonKit.install(getApplication());
> ”，
> 与这些
> “
> debugImplementation 'com.didichuxing.doraemonkit:doraemonkit:2.0.1'
> releaseImplementation 'com.didichuxing.doraemonkit:doraemonkit-no-op:2.0.2'
> implementation 'com.squareup.okhttp3:okhttp:3.12.1'
> 
> “，
> 配置应该没问题吧！

所有的网络监控都需要apo 模块的支持  请接入aop模块以后再试一下

**Comment by Qiwang-CHEN** [comment]
@jtsky 何为“apo 模块”，“aop模块”？(⊙_⊙)？

**Comment by xiandanin** [comment]
网络相关的需要AspectJ插件，参考文档 [3. 流量监控功能（可选）](https://github.com/didi/DoraemonKit/blob/master/Doc/android_cn_guide.md#3-%E6%B5%81%E9%87%8F%E7%9B%91%E6%8E%A7%E5%8A%9F%E8%83%BD%E5%8F%AF%E9%80%89)

也可以在创建okhttp的时候，手动添加弱网的拦截器
```
new OkHttpClient.Builder().addInterceptor(new DoraemonWeakNetworkInterceptor())
```

**Comment by Qiwang-CHEN** [comment]
@xiandanin 感谢，我没看仔细😂
