### ISSUE TITLE
TencentLBSLocationManager 无法正常 Mock GPS 信息

### ISSUE THREAD

**Issue by EyreFree** [didi/DoraemonKit#35]
### 1. 期望的表现和实际的表现。（如有）

正常 Mock GPS 信息

### 2. 问题重现的步骤。（如有）

使用腾讯云 SDK 的 pod 库 `QCloudCOSXML` 后，初始化 `TencentLBSLocationManager` 时，挂在 ` CLLocationManager+Doraemon.m` 的第 28 行：

```objc
NSAssert(NO, @"你在Delegate %@ 中所使用的SEL %@，暂不支持，请联系DoraemonKit开发者",delegate,sel);
```

delegate 类型为 `TencentLBSLocationManager`。

### 3. Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）

iOS / 任意型号

### 4. 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

![](https://upload-images.jianshu.io/upload_images/1018190-05a1de53e5c7d7b2.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by EyreFree** [comment]
临时解决方案：暂时移除 GPS Mock 模块

参见 GPS 模块独立为 subspec 的 PR：[https://github.com/didi/DoraemonKit/pull/37](https://github.com/didi/DoraemonKit/pull/37)

**Comment by yixiangboy** [comment]
是有可能发生的，这种mockGPS方案是把所有的定位回调都传给DoraemonGPSMocker，然后DoraemonGPSMocker再做一次分发。你的这种错误就是你实现的回调，DoraemonGPSMocker没有实现而导致的。如果 有解决方案的话 ， 我们会在这里同步。多谢您的提醒

**Comment by yixiangboy** [comment]
请更新到1.1.7版本
