### ISSUE TITLE
react native 项目如何进行使用DoraemonKit，求接入的方法。

### ISSUE THREAD

**Issue by Double517** [didi/DoraemonKit#351]
目前在使用 react native 项目在进行开发，想要使用DoraemonKit进行性能的监控分析，请问目前是否支持，如果支持改如何进行接入呢

**Comment by jtsky** [comment]
> 目前在使用 react native 项目在进行开发，想要使用DoraemonKit进行性能的监控分析，请问目前是否支持，如果支持改如何进行接入呢

你可以按照文档接入试一下  按照我的理解 react native 的UI也是用过原生的方式去渲染的  所以大部分功能都是可以用的 但是网络那快估计不行
