### ISSUE TITLE
android 日志log

### ISSUE THREAD

**Issue by yezihengok** [didi/DoraemonKit#352]
希望优化一下android 日志log显示功能  ，这么实用的日志log功能 问题很明显啊 更新不及时，感觉只有打开新页面日志才会刷一下。
比如进入了某个页面，调用了接口打印log，这个时候日志log是有的。 接着我点击了按钮调用接口 打印log。DoraemonKit 里log根本不会记录显示。

**Comment by jtsky** [comment]
> 希望优化一下android 日志log显示功能 ，这么实用的日志log功能 问题很明显啊 更新不及时，感觉只有打开新页面日志才会刷一下。
> 比如进入了某个页面，调用了接口打印log，这个时候日志log是有的。 接着我点击了按钮调用接口 打印log。DoraemonKit 里log根本不会记录显示。

好的  近期我看能不能优化下

**Comment by jtsky** [comment]
> 希望优化一下android 日志log显示功能 ，这么实用的日志log功能 问题很明显啊 更新不及时，感觉只有打开新页面日志才会刷一下。
> 比如进入了某个页面，调用了接口打印log，这个时候日志log是有的。 接着我点击了按钮调用接口 打印log。DoraemonKit 里log根本不会记录显示。

“欢迎更新到3.0_beta1版本 ，已经解决，接入手册详见 http://www.dokit.cn/ 使用中心
