### ISSUE TITLE
macCatalyst Support

### ISSUE THREAD

**Issue by Co2333** [didi/DoraemonKit#353]
DoKit GPSMocker.m - Line 148

not available on macCatalyst :P you know what I did.

'''
- (void)locationManager:(CLLocationManager *)manager
        didRangeBeacons:(NSArray<CLBeacon *> *)beacons inRegion:(CLBeaconRegion *)region{
    [self enumDelegate:manager block:^(id<CLLocationManagerDelegate> delegate) {
        if ([delegate respondsToSelector:@selector(locationManager:didRangeBeacons:inRegion:)]) {
            [delegate locationManager:manager didRangeBeacons:beacons inRegion:region];
        }
    }];
}

- (void)locationManager:(CLLocationManager *)manager rangingBeaconsDidFailForRegion:(CLBeaconRegion *)region
              withError:(NSError *)error{
    [self enumDelegate:manager block:^(id<CLLocationManagerDelegate> delegate) {
        if ([delegate respondsToSelector:@selector(locationManager:rangingBeaconsDidFailForRegion:withError:)]) {
            [delegate locationManager:manager rangingBeaconsDidFailForRegion:region withError:error];
        }
    }];
}
'''

**Comment by Co2333** [comment]
好像对macOS的处理不止这一处很麻烦啊

emmmm 如果用空的话还请todo...

**Comment by yixiangboy** [comment]
暂时我们团队这边没有mac App的使用场景和人力，暂不解决。
