### ISSUE TITLE
XCode 11.2 创建新项目集成DoraemonKit后崩溃

### ISSUE THREAD

**Issue by xueminlee** [didi/DoraemonKit#354]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

**Comment by xueminlee** [comment]
2019-12-16 14:06:59.915730+0800 Deleteit[6355:1170712] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AppDelegate window]: unrecognized selector sent to instance 0x6000022c0250'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c4f02e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50b97b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c6ff94 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   UIKitCore                           0x00007fff4787df39 -[UIResponder doesNotRecognizeSelector:] + 302
	4   CoreFoundation                      0x00007fff23c53b56 ___forwarding___ + 838
	5   CoreFoundation                      0x00007fff23c55f38 _CF_forwarding_prep_0 + 120
	6   DoraemonKit                         0x000000010d320797 -[DoraemonEntryView becomeKeyWindow] + 103
	7   UIKitCore                           0x00007fff4789a7f1 -[UIWindow _makeKeyWindowIgnoringOldKeyWindow:] + 515
	8   DoraemonKit                         0x000000010d339168 -[DoraemonManager initEntry:] + 200
	9   DoraemonKit                         0x000000010d3382cd -[DoraemonManager installWithCustomBlock:] + 413
	10  DoraemonKit                         0x000000010d338114 -[DoraemonManager installWithStartingPosition:] + 84
	11  DoraemonKit                         0x000000010d33807a -[DoraemonManager install] + 410
	12  Deleteit                            0x000000010cf48f9c -[AppDelegate application:didFinishLaunchingWithOptions:] + 124
	13  UIKitCore                           0x00007fff47846788 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 232
	14  UIKitCore                           0x00007fff47848197 -[UIApplication _callInitializationDelegatesWithActions:forCanvas:payload:fromOriginatingProcess:] + 3980
	15  UIKitCore                           0x00007fff4784dce6 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1281
	16  UIKitCore                           0x00007fff46f84402 -[_UISceneLifecycleMultiplexer completeApplicationLaunchWithFBSScene:transitionContext:] + 179
	17  UIKitCore                           0x00007fff4784a286 -[UIApplication _compellApplicationLaunchToCompleteUnconditionally] + 59
	18  UIKitCore                           0x00007fff4784a585 -[UIApplication _run] + 754
	19  UIKitCore                           0x00007fff4784fb48 UIApplicationMain + 1621
	20  Deleteit                            0x000000010cf491e4 main + 116
	21  libdyld.dylib                       0x00007fff51a1dc25 start + 1
	22  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by lijie121210** [comment]
iOS 13及以上如果支持了`UIWindowSceneDelegate`，就不能使用 `UIWindow *appWindow = [[UIApplication sharedApplication].delegate window];` 等相关的API操作 `window` 了。

这个帖子也许有帮助:
https://stackoverflow.com/questions/57009283/how-get-current-keywindow-equivalent-for-multi-window-scenedelegate-xcode-11

**Comment by yixiangboy** [comment]
已修复，下个版本三月中旬发布。

**Comment by yixiangboy** [comment]
欢迎更新到3.0beta1版本 ，已经解决，接入手册详见 http://www.dokit.cn/ 试用中心
