### ISSUE TITLE
android版demo无法跑起来

### ISSUE THREAD

**Issue by HQLIE2018** [didi/DoraemonKit#358]
ERROR: Failed to resolve: com.didichuxing.foundation:http:2.1.0.74
ERROR: Failed to resolve: com.didichuxing.foundation:rpc:2.1.0.74

**Comment by KaelInvoker** [comment]
我的也是报这个错误..

**Comment by xiandanin** [comment]
在`doraemonkit-rpc`把这两行注掉
![image](https://user-images.githubusercontent.com/17588779/71140855-6c1eb780-224d-11ea-819d-bbac097c88ef.png)

**Comment by yanchenling** [comment]
注释了就报缺文件，你们都是怎么跑起来的

**Comment by xiandanin** [comment]
@yanchenling rpc没有在主Module引入，所以注掉rpc工程里的依赖不会有问题，我就是这样跑的
你可能需要`Clean`一下或者重新`Make Project`

**Comment by KaelInvoker** [comment]
@xiandanin 感谢！编译通过了

**Comment by HQLIE2018** [comment]
> 在根目录`build.gradle`把这行注掉
> 
> ```
> // maven { url 'http://artifactory.intra.xiaojukeji.com/artifactory/public/' }
> ```
> 
> 在`doraemonkit-rpc/build.gradle`把这两行注掉
> 
> ```
> //compileOnly rootProject.ext.dependencies["didi_http"]
> //compileOnly rootProject.ext.dependencies["didi_rpc"]
> ```

我全部注释了，重新clean了项目，还是跑不起来

**Comment by jtsky** [comment]
代码已更新  建议大家升级到最新代码
