### ISSUE TITLE
怎么关闭 DoraemonKit 在控制台的日志打印

### ISSUE THREAD

**Issue by lks6123** [didi/DoraemonKit#359]
请补充如下信息。
期望可以添加控制是否在控制台打印log的功能。现在调试的时候，DoraemonKit的日志打印刷的太多，导致app自己的日志都不好找。

Android 系统

**Comment by jtsky** [comment]
> 请补充如下信息。
> 期望可以添加控制是否在控制台打印log的功能。现在调试的时候，DoraemonKit的日志打印刷的太多，导致app自己的日志都不好找。
> 
> Android 系统

其实有预留api设置的DoraemonKit.setDebug 我刚看了一下不知道被谁关掉了  我下个版本把开关打开 感谢提醒

**Comment by jtsky** [comment]
> 请补充如下信息。
> 期望可以添加控制是否在控制台打印log的功能。现在调试的时候，DoraemonKit的日志打印刷的太多，导致app自己的日志都不好找。
> 
> Android 系统

新版 DoraemonKit.setDebug(false); api已生效 建议升级
