### ISSUE TITLE
Android隐藏入口无效

### ISSUE THREAD

**Issue by xiandanin** [didi/DoraemonKit#361]
### 期望的表现和实际的表现
默认隐藏入口，需要的时候再手动显示，之前的版本可以通过下面的代码默认隐藏，新版本不行了

### 问题重现的步骤
```
DoraemonKit.install(application)
DoraemonKit.hide()
```

**Comment by jtsky** [comment]
> ### 期望的表现和实际的表现
> 默认隐藏入口，需要的时候再手动显示，之前的版本可以通过下面的代码默认隐藏，新版本不行了
> 
> ### 问题重现的步骤
> ```
> DoraemonKit.install(application)
> DoraemonKit.hide()
> ```
> 
> ### Android 7.1

我在demo上测试是可以的，估计是兼容性问题 你在入口activity的resume中调用hide看下可以吗？

**Comment by xiandanin** [comment]
在`onResume`可以隐藏，在Application里不行，但是放到onResume不合适吧

<img src="https://user-images.githubusercontent.com/17588779/71152737-33450980-2272-11ea-90ef-89009abd1f6f.png"  width="300"/>

<img src="https://user-images.githubusercontent.com/17588779/71152719-26c0b100-2272-11ea-8844-fb4bdd4f3e01.png"  width="200"/>

**Comment by xiandanin** [comment]
换到2.0.2后解决

文档该更新了

**Comment by jtsky** [comment]
> 在`onResume`可以隐藏，在Application里不行，但是放到onResume不合适吧
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/17588779/71152737-33450980-2272-11ea-90ef-89009abd1f6f.png">
> 
> <img alt="" width="200" src="https://user-images.githubusercontent.com/17588779/71152719-26c0b100-2272-11ea-8844-fb4bdd4f3e01.png">

新版本增加了DoraemonKit.setAwaysShowMianIcon(false) api 建议升级体验
