### ISSUE TITLE
卡顿检测的阈值是多少耗时算卡顿？

### ISSUE THREAD

**Issue by lixiangkai1987** [didi/DoraemonKit#362]
卡顿检测的阈值是多少耗时算卡顿？
能否开发接口自己设置卡顿的阈值，我打开了卡顿检测开关，在滑动页面的时候能看到有偶尔的页面卡顿，但是看卡顿记录里没任何信息

**Comment by zanyfly** [comment]
看看源码有

**Comment by jtsky** [comment]
> 卡顿检测的阈值是多少耗时算卡顿？
> 能否开发接口自己设置卡顿的阈值，我打开了卡顿检测开关，在滑动页面的时候能看到有偶尔的页面卡顿，但是看卡顿记录里没任何信息

安卓 ios统一改成了200ms
