### ISSUE TITLE
华为 Mate 30 Pro 内存监控无变化

### ISSUE THREAD

**Issue by zzmingo** [didi/DoraemonKit#366]
> 问题重现的步骤

第一打开内存监控后

> Android 还是 iOS？系统版本是多少？手机品牌是什么？

Android 华为 Mate 30 Pro 

> 其他的错误信息和堆栈信息如果有也可以一并提供出来

监控内存，切换各种Activity，但是内存一直显示183M没变化。
重启之后再试是另一恒定的数值。

**Comment by jtsky** [comment]
> > 问题重现的步骤
> 
> 第一打开内存监控后
> 
> > Android 还是 iOS？系统版本是多少？手机品牌是什么？
> 
> Android 华为 Mate 30 Pro
> 
> > 其他的错误信息和堆栈信息如果有也可以一并提供出来
> 
> 监控内存，切换各种Activity，但是内存一直显示183M没变化。
> 重启之后再试是另一恒定的数值。

![image](https://user-images.githubusercontent.com/4486497/71340686-94325180-2592-11ea-832d-f769f6f97252.png)
Android Q 限制了API的调用频率  我看看有没有办法兼容下
