### ISSUE TITLE
LeakCanary 弹好多 DoraemonKit 内存泄漏警告框

### ISSUE THREAD

**Issue by zYoungTang** [didi/DoraemonKit#367]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
希望把 DoraemonKit 内存泄漏以另外一种方式显示,比如log, LeakCanary 只提醒本 APP 即可.
> 问题重现的步骤。（如有）
集成 LeakCanary 对应依赖后随便点几个功能都会内存泄漏.
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
小米5S MIUI10.2
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

**Comment by jtsky** [comment]
> Please complete the following informations.
> 
> > Expected behavior and actual behavior.
> > Steps to reproduce the problem.
> > Android or iOS? OS version? Brand?
> > More informations such as error messages and stack traces are welcomed.
> 
> 请补充如下信息。
> 
> > 期望的表现和实际的表现。（如有）
> > 希望把 DoraemonKit 内存泄漏以另外一种方式显示,比如log, LeakCanary 只提醒本 APP 即可.
> > 问题重现的步骤。（如有）
> > 集成 LeakCanary 对应依赖后随便点几个功能都会内存泄漏.
> > Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> > 小米5S MIUI10.2
> > 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

好的  我这边看看能不修复掉 或者你们把他们给过滤掉
