### ISSUE TITLE
一直报找不到指定文件，给位老哥 看看啥原因呢

### ISSUE THREAD

**Issue by 1173859245** [didi/DoraemonKit#369]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

**Comment by 1173859245** [comment]
CreateProcess error=2, 系统找不到指定的文件。 <a href="openFile:F:\DoraemonKit-master\Android\doraemonkit-leakcanary\build.gradle">Open File</a>

**Comment by jtsky** [comment]
> CreateProcess error=2, 系统找不到指定的文件。 Open File

最后的问题是windows 和mac下文件格式不一致导致的 已解决
