### ISSUE TITLE
android buildTypes beta

### ISSUE THREAD

**Issue by wangyao5018** [didi/DoraemonKit#370]
我buildTypes里添加了一个beta类型,在打包beta类型的apk,安装成功,但是打开App直接闪退.

`
    dependencies {
        classpath 'com.didichuxing.doraemonkit:doraemonkit-plugin:1.0.0'
    }`

` buildTypes {
        debug {
             apply plugin: 'com.didi.dokit'
       }
        beta {
       }
        release {
       }
}
`

`dependencies {
    debugImplementation 'com.didichuxing.doraemonkit:doraemonkit:2.2.1'
    betaImplementation 'com.didichuxing.doraemonkit:doraemonkit-no-op:2.2.1'
    releaseImplementation 'com.didichuxing.doraemonkit:doraemonkit-no-op:2.2.1'
}`

**Comment by wangyao5018** [comment]
# main(1)

java.lang.ClassCastException

t5.a cannot be cast to n4.a

**Comment by jtsky** [comment]
> 我buildTypes里添加了一个beta类型,在打包beta类型的apk,安装成功,但是打开App直接闪退.
> 
> ` dependencies { classpath 'com.didichuxing.doraemonkit:doraemonkit-plugin:1.0.0' }`
> 
> `buildTypes { debug { apply plugin: 'com.didi.dokit' } beta { } release { } }`
> 
> `dependencies { debugImplementation 'com.didichuxing.doraemonkit:doraemonkit:2.2.1' betaImplementation 'com.didichuxing.doraemonkit:doraemonkit-no-op:2.2.1' releaseImplementation 'com.didichuxing.doraemonkit:doraemonkit-no-op:2.2.1' }`

我感觉你的应用方式错了
正确的引用方式是
apply plugin: 'com.didi.dokit' 需要和apply plugin: 'com.android.application'放在一起

**Comment by wangyao5018** [comment]
@jtsky 我懂你的意思,你说的这种方式我也试过了,也是不行的,
`
dependencies { classpath 'com.didichuxing.doraemonkit:doraemonkit-plugin:1.0.0' }

apply plugin: 'com.android.application'
apply plugin: 'com.didi.dokit' 

android {
       buildTypes { debug { } beta { } release { } }
}

dependencies { 
debugImplementation 'com.didichuxing.doraemonkit:doraemonkit:2.2.1' 

betaImplementation 'com.didichuxing.doraemonkit:doraemonkit-no-op:2.2.1' 

releaseImplementation 'com.didichuxing.doraemonkit:doraemonkit-no-op:2.2.1' 
}

`

**Comment by wangyao5018** [comment]
或者beta版本加入lib也不行,
`betaImplementation 'com.didichuxing.doraemonkit:doraemonkit:2.2.1'`

**Comment by wangyao5018** [comment]
可能和这个库没关系,我单独写了一个demo就没问题,可能是和其他lib一起用出现了问题.我再查查原因
