### ISSUE TITLE
Could not find com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.50.

### ISSUE THREAD

**Issue by coolchengc** [didi/DoraemonKit#374]
编译时报错：
Could not find com.github.CymChad:BaseRecyclerViewAdapterHelper:2.9.50.
Searched in the following locations:
  - https://repo.maven.apache.org/maven2/com/github/CymChad/BaseRecyclerViewAdapterHelper/2.9.50/BaseRecyclerViewAdapterHelper-2.9.50.pom
  - https://repo.maven.apache.org/maven2/com/github/CymChad/BaseRecyclerViewAdapterHelper/2.9.50/BaseRecyclerViewAdapterHelper-2.9.50.jar
  - https://maven.google.com/com/github/CymChad/BaseRecyclerViewAdapterHelper/2.9.50/BaseRecyclerViewAdapterHelper-2.9.50.pom
  - https://maven.google.com/com/github/CymChad/BaseRecyclerViewAdapterHelper/2.9.50/BaseRecyclerViewAdapterHelper-2.9.50.jar
  - https://dl.google.com/dl/android/maven2/com/github/CymChad/BaseRecyclerViewAdapterHelper/2.9.50/BaseRecyclerViewAdapterHelper-2.9.50.pom
  - https://dl.google.com/dl/android/maven2/com/github/CymChad/BaseRecyclerViewAdapterHelper/2.9.50/BaseRecyclerViewAdapterHelper-2.9.50.jar
  - https://jcenter.bintray.com/com/github/CymChad/BaseRecyclerViewAdapterHelper/2.9.50/BaseRecyclerViewAdapterHelper-2.9.50.pom
  - https://jcenter.bintray.com/com/github/CymChad/BaseRecyclerViewAdapterHelper/2.9.50/BaseRecyclerViewAdapterHelper-2.9.50.jar
  - https://dl.bintray.com/drummer-aidan/maven/com/github/CymChad/BaseRecyclerViewAdapterHelper/2.9.50/BaseRecyclerViewAdapterHelper-2.9.50.pom
  - https://dl.bintray.com/drummer-aidan/maven/com/github/CymChad/BaseRecyclerViewAdapterHelper/2.9.50/BaseRecyclerViewAdapterHelper-2.9.50.jar
Required by:
    project :app > com.didichuxing.doraemonkit:doraemonkit:2.2.1

**Comment by jhwsx** [comment]
Very curious problem.
