### ISSUE TITLE
无法访问ListenableFuture

### ISSUE THREAD

**Issue by xiagea** [didi/DoraemonKit#375]
添加完
debugImplementation 'com.didichuxing.doraemonkit:doraemonkit:2.2.1'
releaseImplementation 'com.didichuxing.doraemonkit:doraemonkit-no-op:2.2.1'
后，运行提示
错误: 无法访问ListenableFuture
找不到com.google.common.util.concurrent.ListenableFuture的类文件

androidx.work.Worker类下有用到

**Comment by jtsky** [comment]
> 添加完
> debugImplementation 'com.didichuxing.doraemonkit:doraemonkit:2.2.1'
> releaseImplementation 'com.didichuxing.doraemonkit:doraemonkit-no-op:2.2.1'
> 后，运行提示
> 错误: 无法访问ListenableFuture
> 找不到com.google.common.util.concurrent.ListenableFuture的类文件
> 
> androidx.work.Worker类下有用到

androidx是你那边引入的吧？dokit这边还没有进行androidx的迁移

**Comment by jtsky** [comment]
> 添加完
> debugImplementation 'com.didichuxing.doraemonkit:doraemonkit:2.2.1'
> releaseImplementation 'com.didichuxing.doraemonkit:doraemonkit-no-op:2.2.1'
> 后，运行提示
> 错误: 无法访问ListenableFuture
> 找不到com.google.common.util.concurrent.ListenableFuture的类文件
> 
> androidx.work.Worker类下有用到

欢迎更新到3.0_beta1版本 ，应该已经解决，接入手册详见 http://www.dokit.cn/ 使用中心
