### ISSUE TITLE
测试循环应用 崩在了多啦A梦的代码里

### ISSUE THREAD

**Issue by lxlnihao** [didi/DoraemonKit#376]
If we failed, we probably have C++ and ObjC cannot get it's size and alignment. We are skipping.
         If we would like to support it, we would need to derive size and alignment of type from the string.
         C++ does not have reflection so we can't really do that unless we create the mapping ourselves

FBClassStrongLayout.h
50行 
请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 测试循环引用的时候改了一个弱引用
> iOS系统版本是12.1（如有）

**Comment by lxlnihao** [comment]
循环引用

**Comment by yixiangboy** [comment]
貌似是FB那个库的bug，不要开启全局异常断点即可
