### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/didichuxing/doraemonkit/kit/timecounter/TimeCounterManager;         at com.taobao.sophix.SophixApplication.onCreate(Unknown Source:0)         at com.sibu.futurebazaar.patch.SophixStubApplication.onCreate(SophixStubApplication.java:68)

### ISSUE THREAD

**Issue by reancool** [didi/DoraemonKit#377]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/didichuxing/doraemonkit/kit/timecounter/TimeCounterManager;
        at com.taobao.sophix.SophixApplication.onCreate(Unknown Source:0)
        at com.sibu.futurebazaar.patch.SophixStubApplication.onCreate(SophixStubApplication.java:68)

**Comment by reancool** [comment]
debug的没问题,可以使用
构建正式包有这个问题,正式已经是 
  releaseImplementation 'com.didichuxing.doraemonkit:doraemonkit-no-op:2.2.1'

**Comment by jtsky** [comment]
> debug的没问题,可以使用
> 构建正式包有这个问题,正式已经是
> releaseImplementation 'com.didichuxing.doraemonkit:doraemonkit-no-op:2.2.1'

你进我们的QQ群了吗 在QQ群里找下我 我叫金台

**Comment by zhanglinlovejava** [comment]
我也遇到了这个问题，请问怎么解决

**Comment by reancool** [comment]
> 我也遇到了这个问题，请问怎么解决
我终究也是没解决，使用另外一个方法，只有在 测试版，才会依赖 ，doraemonkit。正式版，完全不会依赖 doraemonkit。
1.使用组件化 application https://www.jianshu.com/p/763928f7582d

`public class DebugApplicationImpl extends BaseApplicationImpl {


    @Override
    protected void asynCreate(IApplication application) {

    }

    @Override
    public void init(IApplication application) {
        DoraemonKit.install(application.getApp());
    }

    @Override
    public void attachBaseContext(Application app) {

    }

    @Override
    public void onMainCreate(IApplication application) {

    }

}`
在上面的这个moudle里初始化 doraemonkit
2.添加一个标记 “IS_DEBUG_TOOLS” 在 gradle.properties里面
`IS_DEBUG_TOOLS=false`
通过控制这个true 或者false来打包
```
if ("true".equals(IS_DEBUG_TOOLS)) {
            classpath 'com.didichuxing.doraemonkit:doraemonkit-plugin:1.0.0'
        }
//app/build.gradle
if ("true".equals(IS_DEBUG_TOOLS)) {
    apply plugin: 'com.didi.dokit'
}
if ("true".equals(IS_DEBUG_TOOLS)) {
        api project(':debug_tools')
    }

//setting.gradle
if ("true".equals(IS_DEBUG_TOOLS)) {
    include ':debug_tools'
}
//这个根据你自己的情况修改，我使用的libraryVariants，你要是在 application中可以使用 applicationVariants
  libraryVariants.all { variant ->
        variant.outputs.all {
            variant.buildConfigField "Boolean", "IS_DEBUG_TOOLS",  IS_DEBUG_TOOLS
        }
    }

//// 初始化模块配置时根据标志是否添加
if (BuildConfig.IS_DEBUG_TOOLS) {
            moudlesList.add("com.×××××.DebugApplicationImpl");
        }
```
例如：
./gradlew iD -PIS_DEBUG_TOOLS=true
