### ISSUE TITLE
NSLog日志记录查看界面 界面适配问题

### ISSUE THREAD

**Issue by caoyunxiao** [didi/DoraemonKit#378]
NSLog日志记录查看界面 界面适配问题

**Comment by yixiangboy** [comment]
可以截个图吗？

**Comment by caoyunxiao** [comment]
![image](https://user-images.githubusercontent.com/15682437/71615407-2a4a2580-2bec-11ea-8e2d-ebfb67a11fbe.png)

**Comment by yixiangboy** [comment]
已复现，下个版本解决
