### ISSUE TITLE
kotlin项目引入后，编译失败Class 'XXX' is not abstract and does not implement abstract base class member

### ISSUE THREAD

**Issue by zhaoyong1989** [didi/DoraemonKit#379]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

**Comment by jtsky** [comment]
> Please complete the following informations.
> 
> > Expected behavior and actual behavior.
> > Steps to reproduce the problem.
> > Android or iOS? OS version? Brand?
> > More informations such as error messages and stack traces are welcomed.
> 
> 请补充如下信息。
> 
> > 期望的表现和实际的表现。（如有）
> > 问题重现的步骤。（如有）
> > Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> > 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

还有其他信息吗  这样我看不出是什么问题

**Comment by jtsky** [comment]
> Please complete the following informations.
> 
> > Expected behavior and actual behavior.
> > Steps to reproduce the problem.
> > Android or iOS? OS version? Brand?
> > More informations such as error messages and stack traces are welcomed.
> 
> 请补充如下信息。
> 
> > 期望的表现和实际的表现。（如有）
> > 问题重现的步骤。（如有）
> > Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> > 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

 欢迎更新到3.0beta1版本 ,接入手册详见 http://www.dokit.cn/ 使用中心

**Comment by jtsky** [comment]
dokit 新版本已发布 请参考以下文档升级:http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide
注意:
插件配置模块的配置和以前有所区别，请重点关注下。
