### ISSUE TITLE
包含 DoraemonLoadAnalyze.framework 后无法正常 Archive

### ISSUE THREAD

**Issue by EyreFree** [didi/DoraemonKit#38]
### 1. 期望的表现和实际的表现。（如有）

正常使用 Load 耗时模块的同时能够正常打包

### 2. 问题重现的步骤。（如有）

工程中引入 DoraemonKit 库后，Aarchive 时挂掉：

![](https://upload-images.jianshu.io/upload_images/1018190-ba6da24d422f5349.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

看起来像是 `DoraemonLoadAnalyze.framework` 没有提供 `armv7` 对应的版本

### 3. Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）

iOS / 任意型号

### 4. 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

```
ld: warning: ignoring file /Users/eyrefree/Documents/XXX/Pods/DoraemonKit/iOS/DoraemonKit/Framework/DoraemonLoadAnalyze.framework/DoraemonLoadAnalyze, missing required architecture armv7 in file /Users/eyrefree/Documents/XXX/Pods/DoraemonKit/iOS/DoraemonKit/Framework/DoraemonLoadAnalyze.framework/DoraemonLoadAnalyze (2 slices)
Undefined symbols for architecture armv7:
  "_dlaLoadModels", referenced from:
      -[DoraemonMethodUseTimeListViewController viewDidLoad] in DoraemonMethodUseTimeListViewController.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by EyreFree** [comment]
临时解决方案：暂时移除 MethodUseTime 模块

参见 MethodUseTime 模块独立为 subspec 的 PR：[https://github.com/didi/DoraemonKit/pull/37](https://github.com/didi/DoraemonKit/pull/37)

**Comment by yixiangboy** [comment]
1.1.5版本已经解决
