### ISSUE TITLE
Could not resolve com.didichuxing.foundation:http:2.1.0.74

### ISSUE THREAD

**Issue by seraphzxz87** [didi/DoraemonKit#382]
ERROR: Unable to resolve dependency for ':doraemonkit-rpc@debug/compileClasspath': Could not resolve com.didichuxing.foundation:http:2.1.0.74.
Show Details
Affected Modules: doraemonkit-rpc

ERROR: Unable to resolve dependency for ':doraemonkit-rpc@debug/compileClasspath': Could not resolve com.didichuxing.foundation:rpc:2.1.0.74.
Show Details
Affected Modules: doraemonkit-rpc

**Comment by jtsky** [comment]
> ERROR: Unable to resolve dependency for ':doraemonkit-rpc@debug/compileClasspath': Could not resolve com.didichuxing.foundation:http:2.1.0.74.
> Show Details
> Affected Modules: doraemonkit-rpc
> 
> ERROR: Unable to resolve dependency for ':doraemonkit-rpc@debug/compileClasspath': Could not resolve com.didichuxing.foundation:rpc:2.1.0.74.
> Show Details
> Affected Modules: doraemonkit-rpc

这是滴滴内部的网络库 外部无法访问 建议在demo的setting中注释掉rpc moudle
