### ISSUE TITLE
Unknown type name 'uint64_t'

### ISSUE THREAD

**Issue by vicky1221** [didi/DoraemonKit#383]
编译报错

请补充如下信息。
> 期望编译通过
> pod install 之后
> iOS
<img width="1154" alt="屏幕快照 2020-01-07 下午6 18 25" src="https://user-images.githubusercontent.com/5127480/71889563-5d0c9480-317d-11ea-89f6-9fbd93e6ea6b.png">

**Comment by yixiangboy** [comment]
解决了吗？应该是你的工程配置问题

**Comment by mqlsq** [comment]
这个问题怎么解决的

**Comment by jumpingfrog0** [comment]
我也遇到这个问题，怎么解决？？

**Comment by jumpingfrog0** [comment]
搞到最后实在没办法，直接改源码，加了个头文件

**Comment by whpanda** [comment]
有点坑
