### ISSUE TITLE
能否支持androidX?

### ISSUE THREAD

**Issue by SheepYang1993** [didi/DoraemonKit#384]
能否支持androidX?能给个预计时间吗？

**Comment by jtsky** [comment]
> 能否支持androidX?能给个预计时间吗？

关于是否支持androidX，我们内部讨论过，因为我们dokit是针对线下的开发工具，所有的实现都不会带到线上，即所有dokit里的support也不会编译进去，所以支持androidX的意义不是很大，如果后期我们要做线上的话，到时候肯定会支持。
