### ISSUE TITLE
android debug和release环境 okhttp interceptor 包名不一致

### ISSUE THREAD

**Issue by JesseWo** [didi/DoraemonKit#385]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
android
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

2.2.1 no-op 没有同步修改
```
DoraemonWeakNetworkInterceptor
DoraemonInterceptor
```

**Comment by jtsky** [comment]
> DoraemonWeakNetworkInterceptor

感谢你的issue  这边已经修改会随着下个版本发布
