### ISSUE TITLE
iOS 2.0.0 版本打开流量检测开关，警告 UI 在非主线程发生操作

### ISSUE THREAD

**Issue by YiYiZheng** [didi/DoraemonKit#387]
iOS 2.0.0 版本 在 iOS 12.2 iPhone 7 、iOS 13.3 iPad mini4 上出现，是必现的

打开流量检测开关，随后进行网络请求，Main Thread Checker 会报许多 UI 在非主线程发生。是否能统一修改一下。

**Comment by yixiangboy** [comment]
好的 下个版本修复

**Comment by zhaojijin** [comment]
请问这个现在修改好了吗？

**Comment by yixiangboy** [comment]
分支上修改好了 暂时还没对外发布新版本

**Comment by zhaojijin** [comment]
什么时候可以对外发布呢？

**Comment by yixiangboy** [comment]
暂定3月中旬，会对外发一个比较大的版本。

**Comment by yixiangboy** [comment]
欢迎更新到3.0beta1版本 ，已经解决，接入手册详见 http://www.dokit.cn/ 试用中心
