### ISSUE TITLE
增加启动时间记录？

### ISSUE THREAD

**Issue by kekeYezi** [didi/DoraemonKit#39]
先给大佬们 手动点赞👍
提个小需求 记录下启动时间 帮助优化App。
最好能定位耗时过程，虽然 Instruments已经很详细 但是集成版本有的话就更方便了。

**Comment by yixiangboy** [comment]
好的，我们接下来安排调研 研究一下。

**Comment by birdmichael** [comment]
> 好的，我们接下来安排调研 研究一下。

老大真的事什么需求都接的么？哈哈哈~

**Comment by LinJZong** [comment]
Android 1.1.2版本提供App 启动时长，页面跳转时长统计功能
