### ISSUE TITLE
是否支持指定某个页面不显示 DoraemonKit 的悬浮 icon？

### ISSUE THREAD

**Issue by YuYongzhi** [didi/DoraemonKit#390]
是否支持指定某个页面不显示 DoraemonKit 的悬浮 icon？

**Comment by yixiangboy** [comment]
可以自己主动调用show或者hidden方法

**Comment by YuYongzhi** [comment]
DoraemonKit会在所有页面添加悬浮 icon，如果一个 activity是在 SDK 中，就无法添加代码实现隐藏或显示，请问怎么操作？

**Comment by xiandanin** [comment]
@YuYongzhi 
```
registerActivityLifecycleCallbacks(new ActivityLifecycleCallbacks() {

    @Override
    public void onActivityResumed(Activity activity) {
        if (activity.getClass().getName().equals(MainActivity.class.getName())) {
            DoraemonKit.hide();
        } else {
            DoraemonKit.show();
        }
    }
    ...
});
```

**Comment by jtsky** [comment]
> @YuYongzhi
> 
> ```
> registerActivityLifecycleCallbacks(new ActivityLifecycleCallbacks() {
> 
>     @Override
>     public void onActivityResumed(Activity activity) {
>         if (activity.getClass().getName().equals(MainActivity.class.getName())) {
>             DoraemonKit.hide();
>         } else {
>             DoraemonKit.show();
>         }
>     }
>     ...
> });
> ```

感谢你的解答
