### ISSUE TITLE
进入某个列表界面后，崩溃

### ISSUE THREAD

**Issue by xjh093** [didi/DoraemonKit#392]
<img width="1458" alt="截屏2020-01-15下午3 19 45" src="https://user-images.githubusercontent.com/7610880/72413346-9612bd80-37aa-11ea-9176-344a5b5d390a.png">

**Comment by xjh093** [comment]
<img width="394" alt="截屏2020-01-15下午3 23 07" src="https://user-images.githubusercontent.com/7610880/72413530-f43fa080-37aa-11ea-9374-9587a2b090ce.png">

**Comment by xjh093** [comment]
是这句代码造成的
[_button.layer.sublayers makeObjectsPerformSelector:@selector(removeFromSuperlayer)];

po _useButton.layer.sublayers
<CALayerArray 0x2815ae430>(
<_UILabelLayer:0x2838d9d60; position = CGPoint (0 0); bounds = CGRect (0 0; 0 0); delegate = <UIButtonLabel: 0x106b081c0; frame = (0 0; 0 0); hidden = YES; opaque = NO; userInteractionEnabled = NO; layer = <_UILabelLayer: 0x2838d9d60>>; hidden = YES; allowsGroupOpacity = YES; contentsMultiplyColor = (null); rasterizationScale = 3; contentsScale = 3>
)

**Comment by yixiangboy** [comment]
可以更新到最新版本再试一下

**Comment by xjh093** [comment]
已经处理好了？

**Comment by yixiangboy** [comment]
你是用的2.0.0的版本吗？

**Comment by xjh093** [comment]
1.1.9

**Comment by yixiangboy** [comment]
更新一下试试

**Comment by xjh093** [comment]
好的

**Comment by yixiangboy** [comment]
欢迎更新到3.0beta1版本 ，已经解决，接入手册详见 http://www.dokit.cn/ 试用中心
