### ISSUE TITLE
Android10使用取色器功能后崩溃

### ISSUE THREAD

**Issue by ijays7** [didi/DoraemonKit#394]
**出现问题的设备**

测试了荣耀v10，一加6 两款设备，系统均为 Android10

**DoraemonKit 版本**

```groovy
 debugImplementation 'com.didichuxing.doraemonkit:doraemonkit:2.2.2'
 releaseImplementation 'com.didichuxing.doraemonkit:doraemonkit-no-op:2.2.2'
```

**复现步骤**

1. 选中 UI 工具中的拾色器工具
2. 弹出隐私提示弹窗，选中立即开始
3. 页面中只有底部显示一个白条，点击白条上的叉按钮，程序 crash

**错误日志**

```java
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.ImageReader.close()' on a null object reference
        at com.didichuxing.doraemonkit.kit.colorpick.ImageCapture.destroy(ImageCapture.java:98)
        at com.didichuxing.doraemonkit.kit.colorpick.ColorPickerDokitView.onDestroy(ColorPickerDokitView.java:79)
        at com.didichuxing.doraemonkit.ui.base.AbsDokitView.performDestroy(AbsDokitView.java:195)
        at com.didichuxing.doraemonkit.ui.base.NormalDokitViewManager.detach(NormalDokitViewManager.java:356)
        at com.didichuxing.doraemonkit.ui.base.DokitViewManager.detach(DokitViewManager.java:170)
        at com.didichuxing.doraemonkit.kit.colorpick.ColorPickerInfoDokitView$1.onClick(ColorPickerInfoDokitView.java:62)
        at android.view.View.performClick(View.java:7192)
        at android.view.View.performClickInternal(View.java:7166)
        at android.view.View.access$3500(View.java:824)
        at android.view.View$PerformClick.run(View.java:27592)
        at android.os.Handler.handleCallback(Handler.java:888)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8169)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```

**Comment by jtsky** [comment]
> **出现问题的设备**
> 
> 测试了荣耀v10，一加6 两款设备，系统均为 Android10
> 
> **DoraemonKit 版本**
> 
> ```groovy
>  debugImplementation 'com.didichuxing.doraemonkit:doraemonkit:2.2.2'
>  releaseImplementation 'com.didichuxing.doraemonkit:doraemonkit-no-op:2.2.2'
> ```
> 
> **复现步骤**
> 
> 1. 选中 UI 工具中的拾色器工具
> 2. 弹出隐私提示弹窗，选中立即开始
> 3. 页面中只有底部显示一个白条，点击白条上的叉按钮，程序 crash
> 
> **错误日志**
> 
> ```java
> java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.ImageReader.close()' on a null object reference
>         at com.didichuxing.doraemonkit.kit.colorpick.ImageCapture.destroy(ImageCapture.java:98)
>         at com.didichuxing.doraemonkit.kit.colorpick.ColorPickerDokitView.onDestroy(ColorPickerDokitView.java:79)
>         at com.didichuxing.doraemonkit.ui.base.AbsDokitView.performDestroy(AbsDokitView.java:195)
>         at com.didichuxing.doraemonkit.ui.base.NormalDokitViewManager.detach(NormalDokitViewManager.java:356)
>         at com.didichuxing.doraemonkit.ui.base.DokitViewManager.detach(DokitViewManager.java:170)
>         at com.didichuxing.doraemonkit.kit.colorpick.ColorPickerInfoDokitView$1.onClick(ColorPickerInfoDokitView.java:62)
>         at android.view.View.performClick(View.java:7192)
>         at android.view.View.performClickInternal(View.java:7166)
>         at android.view.View.access$3500(View.java:824)
>         at android.view.View$PerformClick.run(View.java:27592)
>         at android.os.Handler.handleCallback(Handler.java:888)
>         at android.os.Handler.dispatchMessage(Handler.java:100)
>         at android.os.Looper.loop(Looper.java:213)
>         at android.app.ActivityThread.main(ActivityThread.java:8169)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
> ```

好的  我平时开发的时候是在emui10.0的机子上测试的  我这边加一下判空

**Comment by jtsky** [comment]
> **出现问题的设备**
> 
> 测试了荣耀v10，一加6 两款设备，系统均为 Android10
> 
> **DoraemonKit 版本**
> 
> ```groovy
>  debugImplementation 'com.didichuxing.doraemonkit:doraemonkit:2.2.2'
>  releaseImplementation 'com.didichuxing.doraemonkit:doraemonkit-no-op:2.2.2'
> ```
> 
> **复现步骤**
> 
> 1. 选中 UI 工具中的拾色器工具
> 2. 弹出隐私提示弹窗，选中立即开始
> 3. 页面中只有底部显示一个白条，点击白条上的叉按钮，程序 crash
> 
> **错误日志**
> 
> ```java
> java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.ImageReader.close()' on a null object reference
>         at com.didichuxing.doraemonkit.kit.colorpick.ImageCapture.destroy(ImageCapture.java:98)
>         at com.didichuxing.doraemonkit.kit.colorpick.ColorPickerDokitView.onDestroy(ColorPickerDokitView.java:79)
>         at com.didichuxing.doraemonkit.ui.base.AbsDokitView.performDestroy(AbsDokitView.java:195)
>         at com.didichuxing.doraemonkit.ui.base.NormalDokitViewManager.detach(NormalDokitViewManager.java:356)
>         at com.didichuxing.doraemonkit.ui.base.DokitViewManager.detach(DokitViewManager.java:170)
>         at com.didichuxing.doraemonkit.kit.colorpick.ColorPickerInfoDokitView$1.onClick(ColorPickerInfoDokitView.java:62)
>         at android.view.View.performClick(View.java:7192)
>         at android.view.View.performClickInternal(View.java:7166)
>         at android.view.View.access$3500(View.java:824)
>         at android.view.View$PerformClick.run(View.java:27592)
>         at android.os.Handler.handleCallback(Handler.java:888)
>         at android.os.Handler.dispatchMessage(Handler.java:100)
>         at android.os.Looper.loop(Looper.java:213)
>         at android.app.ActivityThread.main(ActivityThread.java:8169)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
> ```

你好 我这边测试了一下  发现是Android Q升级了屏幕截屏的权限 我估计你项目的targetSdkVersion是29  可以考虑改成28或者其他低版本试下 我这边近期也会兼容一下

**Comment by ijays7** [comment]
好的  我们项目target 就是29

**Comment by ijays7** [comment]
好的👌 我们项目target 就是29
辛苦了

**Comment by jtsky** [comment]
> 好的👌 我们项目target 就是29
> 辛苦了

你好 该issues 我已经进行修复，将会在最期发布更新，敬请期待。

**Comment by jtsky** [comment]
> 好的👌 我们项目target 就是29
> 辛苦了

我这边已经在新版本中针对这个问题进行了修复 随着下个版本发布 大概时间在3月中旬左右 请关注升级sdk 谢谢
