### ISSUE TITLE
iOS 固定竖屏且未锁屏的状态下，旋转设备，会因为 Doraemon 小窗口导致状态栏变成横屏

### ISSUE THREAD

**Issue by YiYiZheng** [didi/DoraemonKit#396]
如果不使用 Doraemon，则状态栏不会变回横屏。

iPad 和 大屏 iPhone 手机，会有这个现象

**Comment by yixiangboy** [comment]
iOS 固定竖屏 ，你是怎么旋转屏幕的？能给我们发一个有问题的demo吗？或者自己找到问题，给我们提交PR，我们下个版本合并。

**Comment by YiYiZheng** [comment]
是否有联系方式，我已经有可复现的 demo

**Comment by yixiangboy** [comment]
919727170@qq.com

**Comment by YiYiZheng** [comment]
已发送，谢谢

**Comment by YiYiZheng** [comment]
请问在你那边是否复现，然后有没有方法能暂时解决我的这个问题？谢谢。我想暂时修改源码，规避这个问题。

**Comment by yixiangboy** [comment]
你已经找到原因了吗？欢迎给我们提PR

**Comment by YiYiZheng** [comment]
我暂时也没找到原因，现在你那边是处于已经复现，但不知道如何解决的状态，是吗？

**Comment by yixiangboy** [comment]
你给我们的demo可以复现，暂时没有找到解决方案

**Comment by wizardch** [comment]
这个可能的原因应该是在 DoraemonEntryWindow中初始化 rootViewController 的时候，直接使用了UIViewController，而UIViewController的shouldAutorotate默认是返回YES的，这样其他的window上的控制器就会可能因为判断了statusBar的orientation出现了问题，只要自定义一个控制器，在其中的- (BOOL)shouldAutorotate方法中返回NO，就不会影响嵌入的App，虽然这样哆啦A梦也不能自动旋转。

我的这个回答能获得滴滴文化衫不？:)
@yixiangboy

**Comment by YiYiZheng** [comment]
> 这个可能的原因应该是在 DoraemonEntryWindow中初始化 rootViewController 的时候，直接使用了UIViewController，而UIViewController的shouldAutorotate默认是返回YES的，这样其他的window上的控制器就会可能因为判断了statusBar的orientation出现了问题，只要自定义一个控制器，在其中的- (BOOL)shouldAutorotate方法中返回NO，就不会影响嵌入的App，虽然这样哆啦A梦也不能自动旋转。
> 
> 我的这个回答能获得滴滴文化衫不？:)
> @yixiangboy

试了一下，顶上的状态栏还是会跑到横屏上去

**Comment by wizardch** [comment]
> > 这个可能的原因应该是在 DoraemonEntryWindow中初始化 rootViewController 的时候，直接使用了UIViewController，而UIViewController的shouldAutorotate默认是返回YES的，这样其他的window上的控制器就会可能因为判断了statusBar的orientation出现了问题，只要自定义一个控制器，在其中的- (BOOL)shouldAutorotate方法中返回NO，就不会影响嵌入的App，虽然这样哆啦A梦也不能自动旋转。
> > 我的这个回答能获得滴滴文化衫不？:)
> > @yixiangboy
> 
> 试了一下，状态栏还是会跑来跑去。Doraemon 的那个小按钮确实不转了。

那您可能要看看自己的应用工程了，查看各控制器对旋转支持的情况

**Comment by YiYiZheng** [comment]
> > > 这个可能的原因应该是在 DoraemonEntryWindow中初始化 rootViewController 的时候，直接使用了UIViewController，而UIViewController的shouldAutorotate默认是返回YES的，这样其他的window上的控制器就会可能因为判断了statusBar的orientation出现了问题，只要自定义一个控制器，在其中的- (BOOL)shouldAutorotate方法中返回NO，就不会影响嵌入的App，虽然这样哆啦A梦也不能自动旋转。
> > > 我的这个回答能获得滴滴文化衫不？:)
> > > @yixiangboy
> > 
> > 
> > 试了一下，状态栏还是会跑来跑去。Doraemon 的那个小按钮确实不转了。
> 
> 那您可能要看看自己的应用工程了，查看各控制器对旋转支持的情况

没加 Doraemon 之前全部好的，加了就出问题了。

**Comment by wizardch** [comment]
> > > > 这个可能的原因应该是在 DoraemonEntryWindow中初始化 rootViewController 的时候，直接使用了UIViewController，而UIViewController的shouldAutorotate默认是返回YES的，这样其他的window上的控制器就会可能因为判断了statusBar的orientation出现了问题，只要自定义一个控制器，在其中的- (BOOL)shouldAutorotate方法中返回NO，就不会影响嵌入的App，虽然这样哆啦A梦也不能自动旋转。
> > > > 我的这个回答能获得滴滴文化衫不？:)
> > > > @yixiangboy
> > > 
> > > 
> > > 试了一下，状态栏还是会跑来跑去。Doraemon 的那个小按钮确实不转了。
> > 
> > 
> > 那您可能要看看自己的应用工程了，查看各控制器对旋转支持的情况
> 
> 没加 Doraemon 之前全部好的，加了就出问题了。

是的，我的工程也是之前没有问题，加了哆啦A梦后影响了屏幕的旋转控制，

**Comment by Cyandnow** [comment]
> > > > > 这个可能的原因应该是在 DoraemonEntryWindow中初始化 rootViewController 的时候，直接使用了UIViewController，而UIViewController的shouldAutorotate默认是返回YES的，这样其他的window上的控制器就会可能因为判断了statusBar的orientation出现了问题，只要自定义一个控制器，在其中的- (BOOL)shouldAutorotate方法中返回NO，就不会影响嵌入的App，虽然这样哆啦A梦也不能自动旋转。
> > > > > 我的这个回答能获得滴滴文化衫不？:)
> > > > > @yixiangboy
> > > > 
> > > > 
> > > > 试了一下，状态栏还是会跑来跑去。Doraemon 的那个小按钮确实不转了。
> > > 
> > > 
> > > 那您可能要看看自己的应用工程了，查看各控制器对旋转支持的情况
> > 
> > 
> > 没加 Doraemon 之前全部好的，加了就出问题了。
> 
> 是的，我的工程也是之前没有问题，加了哆啦A梦后影响了屏幕的旋转控制，

我解决了这个问题, 稍后提 PR

**Comment by Cyandnow** [comment]
> iOS 固定竖屏 ，你是怎么旋转屏幕的？能给我们发一个有问题的demo吗？或者自己找到问题，给我们提交PR，我们下个版本合并。

您好, 我已经修改了这个问题, [PR 链接](https://github.com/didi/DoraemonKit/pull/620)

**Comment by wm219** [comment]
问题已经修复
https://github.com/didi/DoraemonKit/pull/620
