### ISSUE TITLE
开启流量拦截后某些图片无法下载报错

### ISSUE THREAD

**Issue by zyallday** [didi/DoraemonKit#398]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）开启抓包功能可以下载图片
> 问题重现的步骤。（如有）
开启抓包流程后，发现某些图片无法下载，最后定位到RealInterceptorChain中抛出了异常
如图
![download](https://user-images.githubusercontent.com/3699784/75136635-410a8580-5720-11ea-9fa1-81cb8001c717.png)

> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
Android
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

下载图片使用的是 HttpUrlConnection 我看到开启抓包后使用了 ObsoleteUrlFactory里面注入的 okhttp实现的HttpUrlConnection

**Comment by zyallday** [comment]
感觉跟注入的 Interceper  类型有关 是不是应该用Application Intercepter 而不是 NetworkInterceptor?

**Comment by jtsky** [comment]
> 感觉跟注入的 Interceper 类型有关 是不是应该用Application Intercepter 而不是 NetworkInterceptor?

方便给一下你的图片url吗，我这边用HttpUrlConnection去加载图片的时候没有出现你说得问题

**Comment by zyallday** [comment]
嗯 我的也是大部分没有出现问题（包括一些图片和视频都没有出现问题） 我们的场景是这样的 公司内部有一个下载框架是基于 HttpUrlConnection的，当使用了流量监控之后，被插件改写成了ObsoleteUrlFactory里面实现，这个时候下载突然到某一步就不动了 后来我跟踪发现定位到 okhttp 的RealInterceptorChain里面报异常了 

这里有有问题的图片链接：
http://videostream.iqiyi.com/v2/imageback/i/20e6f53c376747099c61fc379005b186
第一次302之后就不动了

**Comment by jtsky** [comment]
> 嗯 我的也是大部分没有出现问题（包括一些图片和视频都没有出现问题） 我们的场景是这样的 公司内部有一个下载框架是基于 HttpUrlConnection的，当使用了流量监控之后，被插件改写成了ObsoleteUrlFactory里面实现，这个时候下载突然到某一步就不动了 后来我跟踪发现定位到 okhttp 的RealInterceptorChain里面报异常了
> 
> 这里有有问题的图片链接：
> http://videostream.iqiyi.com/v2/imageback/i/20e6f53c376747099c61fc379005b186
> 第一次302之后就不动了

我在demo中通过以下代码进行测试 没有复现你的问题
`private void requestImage(String urlStr) {
        try {
            //
            URL url = new URL(urlStr);
            // http    https
            // ftp
            HttpURLConnection urlConnection = (HttpURLConnection) url.openConnection();
            //http get post
            urlConnection.setRequestMethod("GET");


            urlConnection.setConnectTimeout(5000);
            urlConnection.setReadTimeout(5000);

            int responseCode = urlConnection.getResponseCode();
            if (responseCode == 200) {
                Bitmap bitmap = BitmapFactory.decodeStream(urlConnection.getInputStream());
                //更新 ui
                mHandler.sendMessage(mHandler.obtainMessage(UPDATE_UI, bitmap));
            }
        } catch (MalformedURLException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }`

也有可能是我在开发的新版本中修复了，你到时候可以等我们的新版本发布了更新试一下 大概三月中旬左右 感谢你的反馈

**Comment by jtsky** [comment]
> 嗯 我的也是大部分没有出现问题（包括一些图片和视频都没有出现问题） 我们的场景是这样的 公司内部有一个下载框架是基于 HttpUrlConnection的，当使用了流量监控之后，被插件改写成了ObsoleteUrlFactory里面实现，这个时候下载突然到某一步就不动了 后来我跟踪发现定位到 okhttp 的RealInterceptorChain里面报异常了
> 
> 这里有有问题的图片链接：
> http://videostream.iqiyi.com/v2/imageback/i/20e6f53c376747099c61fc379005b186
> 第一次302之后就不动了

哦 对了 我新版本中还新增了针对图片的过滤

**Comment by zyallday** [comment]
好的 多谢回复
这个情况确实确实，加载图片没有问题只有这里的下载报错了
等我有时间我再去追查一下原因，因为其他的下载链接也有302的地址 但是没有报错 但是我当时没有追踪，等我有结论了再来看下

**Comment by jtsky** [comment]
> 好的 多谢回复
> 这个情况确实确实，加载图片没有问题只有这里的下载报错了
> 等我有时间我再去追查一下原因，因为其他的下载链接也有302的地址 但是没有报错 但是我当时没有追踪，等我有结论了再来看下

好的  也欢迎你到我们的QQ群里直接跟我交流 这样效率也会高点 再次感谢你的使用

**Comment by zyallday** [comment]
好的 我已经添加了 还没通过
