### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by vagrant1991** [didi/DoraemonKit#400]
ClassCastException: com.didichuxing.doraemonkit.ui.d.a cannot be cast to com.didichuxing.doraemonkit.kit.timecounter.a

**Comment by jtsky** [comment]
> ClassCastException: com.didichuxing.doraemonkit.ui.d.a cannot be cast to com.didichuxing.doraemonkit.kit.timecounter.a

你是不是把dokit的代码带到线上去了？线上环境需要对接no-op的库的
