### ISSUE TITLE
卡顿检测日志怎么导出

### ISSUE THREAD

**Issue by fanfanxiaozu** [didi/DoraemonKit#402]
如题

**Comment by yixiangboy** [comment]
现在可以通过沙盒浏览器找到Library/Caches/ANR中进行导出。

感谢反馈，后面我们在卡顿检测结果页 也增加一个可以导出的入口。

下个版本大概三月10旬发布

**Comment by yixiangboy** [comment]
欢迎更新到3.0beta1版本 ，已经解决，接入手册详见 http://www.dokit.cn/ 试用中心
