### ISSUE TITLE
注册多个NSURLProtocol时只有排第一的可以拿到post body

### ISSUE THREAD

**Issue by xilin** [didi/DoraemonKit#403]
* 期望的表现和实际的表现
项目中有多个NSURLProtocol子类时，即在NSURLSessionConfiguration的protocolClasses里返回的数组长度大于1时，期望每一个NSURLProtocol的子类在stopLoading时都能获取到http post body内容。实际上只有第一个可以取得。

* 问题重现的步骤
加载DoraemonKit，开启流量功能。同时项目中再注册一个NSURLProtocol子类。排在第二的类中无法获得post body。

* Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
iOS 13.3。

猜想是HTTPBodyStream只能被顺序读取一次？

**Comment by yixiangboy** [comment]
我本地也复现了，用NSURLSession做分发就会有这个问题，用NSURLConnection分发就是好的，有点奇怪，你找到原因了吗？

**Comment by xilin** [comment]
> 我本地也复现了，用NSURLSession做分发就会有这个问题，用NSURLConnection分发就是好的，有点奇怪，你找到原因了吗？

我猜是bodyStream不能rewind导致的

**Comment by yFeii** [comment]
本来 所有注册到 protocol中的子类， 系统只会选择一个来进行url加载系统的流程。详见 swift foundation中的NSURLProtocol 实现

**Comment by Haisens** [comment]
现有方案设计如此  问题已经录  后续会升级
