### ISSUE TITLE
PerformanceDataManager中在android O以上通过“top -n 1”获取cpu值的方法在编译的Realease包下解析不到进程信息

### ISSUE THREAD

**Issue by staylifer** [didi/DoraemonKit#405]
PerformanceDataManager中在Android O以上通过“top -n 1”获取cpu值的方法在编译的Realease包下解析不到进程信息，Debug包正常

**Comment by jtsky** [comment]
> PerformanceDataManager中在Android O以上通过“top -n 1”获取cpu值的方法在编译的Realease包下解析不到进程信息，Debug包正常

dokit的所有功能都不建议在release 包下使用 而且有些功能是依赖Debug环境的 因为内部调用了系统的Debug对象
