### ISSUE TITLE
Android 10系统上 通过ActivityManager.getProcessMemoryInfo 获取的内存信息更新不及时

### ISSUE THREAD

**Issue by gogoclb** [didi/DoraemonKit#406]
目前在两个华为 10.0系统上表现都有问题，基本上稳定后，内存的折线图就是一根直线，不带变化的，mate30 pro 5g, 和 nova6。

在另外一个9.0的系统的华为手机上表现良好。
我估计是系统API有bug了。

有没有方案了， 或者类似的issue.

**Comment by jtsky** [comment]
> 目前在两个华为 10.0系统上表现都有问题，基本上稳定后，内存的折线图就是一根直线，不带变化的，mate30 pro 5g, 和 nova6。
> 
> 在另外一个9.0的系统的华为手机上表现良好。
> 我估计是系统API有bug了。
> 
> 有没有方案了， 或者类似的issue.

请看下这个issues:https://github.com/didi/DoraemonKit/issues/366  我们近期会发布新版本 到时候你可以接入新版本再看下

**Comment by jtsky** [comment]
> 目前在两个华为 10.0系统上表现都有问题，基本上稳定后，内存的折线图就是一根直线，不带变化的，mate30 pro 5g, 和 nova6。
> 
> 在另外一个9.0的系统的华为手机上表现良好。
> 我估计是系统API有bug了。
> 
> 有没有方案了， 或者类似的issue.

“ 欢迎更新到3.0_beta1版本 ，已经解决，接入手册详见 http://www.dokit.cn/ 使用中心“
