### ISSUE TITLE
检测内存泄漏，同时开启了检测开关和弹框提醒，崩溃了

### ISSUE THREAD

**Issue by christhoper** [didi/DoraemonKit#408]
![截屏2020-03-09下午2 16 06](https://user-images.githubusercontent.com/16463773/76187611-c148e480-6210-11ea-8ff4-f1eb5436172a.png)

**Comment by yixiangboy** [comment]
pod 'FBRetainCycleDetector', :git => 'git@github.com:facebook/FBRetainCycleDetector.git', :configurations => ['Debug'] 强制升级到最新版本试试

**Comment by SilenceLove** [comment]
> 

没有用，还是崩溃

**Comment by SilenceLove** [comment]
![image](https://user-images.githubusercontent.com/18083149/150109240-99607317-838d-48ec-9ca8-661380f2eeb4.png)

**Comment by mqlsq** [comment]
> ![image](https://user-images.githubusercontent.com/18083149/150109240-99607317-838d-48ec-9ca8-661380f2eeb4.png)



> ![image](https://user-images.githubusercontent.com/18083149/150109240-99607317-838d-48ec-9ca8-661380f2eeb4.png)

我也是这个地方崩溃, 不知道如何解决的
