### ISSUE TITLE
android 帧率 cpu 内存 无法查看 miui10 android8.1 未root

### ISSUE THREAD

**Issue by manondidi** [didi/DoraemonKit#41]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
android 帧率 cpu 内存无法查看
> 问题重现的步骤。（如有）
按文档进行下列步骤接入sdk
```
dependencies {
	
    debugImplementation 'com.didichuxing.doraemonkit:doraemonkit:1.0.5'
    releaseImplementation 'com.didichuxing.doraemonkit:doraemonkit-no-op:1.0.5'
  
}

    DoraemonKit.install(application)

```

进入具体某个页面点击悬浮窗开启 cpu ram 帧率 这三个 按返回键 ,

内存cpu frame始终是0

> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）

android 红米5plus miui10 android8.1

> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

**Comment by manondidi** [comment]
kotlin工程 androidX控件

**Comment by LinJZong** [comment]
目前的cpu内存功能是通过解析/proc目录文件实现的，但是android 8.0开始系统收紧了权限，不允许读取读取/proc目录文件。目前实现了使用adb命令来获取性能参数，不过操作有点繁琐。正在调研是否有替代方案。

**Comment by manondidi** [comment]
gt可以看
https://github.com/Tencent/GT

**Comment by LinJZong** [comment]
1.1.0版本已增加8.0设备支持

**Comment by wholegale39** [comment]
1.1.0版本之前是使用cat /proc/PID/stat方式获取CPU信息的吗？1.1.0是改为adb shell top命令获取了？

**Comment by LinJZong** [comment]
> 1.1.0版本之前是使用cat /proc/PID/stat方式获取CPU信息的吗？1.1.0是改为adb shell top命令获取了？

是的

**Comment by wytiger** [comment]
小米6   android9不能看，top命令拿到的也一直是0
