### ISSUE TITLE
Android系统 在设置界面打开悬浮窗，然后再返回其他页面会崩溃

### ISSUE THREAD

**Issue by harveyandroid** [didi/DoraemonKit#411]
4 Caused by:
--
5 java.lang.NullPointerException:Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
6 com.didichuxing.doraemonkit.ui.base.NormalDokitViewManager.onActivityResume(NormalDokitViewManager.java:226)
7 com.didichuxing.doraemonkit.ui.base.NormalDokitViewManager.resumeAndAttachDokitViews(NormalDokitViewManager.java:118)
8 com.didichuxing.doraemonkit.ui.base.DokitViewManager.resumeAndAttachDokitViews(DokitViewManager.java:153)
9 com.didichuxing.doraemonkit.DokitActivityLifecycleCallbacks.resumeAndAttachDokitViews(DokitActivityLifecycleCallbacks.java:166)
10 com.didichuxing.doraemonkit.DokitActivityLifecycleCallbacks.onActivityResumed(DokitActivityLifecycleCallbacks.java:87)
11 android.app.Application.dispatchActivityResumed(Application.java:208)

**Comment by jtsky** [comment]
> onActivityResume

已在3.0_beta2中修复 欢迎到我们的www.dokit.cn的使用中心中查看升级

**Comment by harveyandroid** [comment]
您好，我用3.0_beta2版本测试了一下还存在。操作步骤： 默认不显示悬浮入口，在APP设置界面打开显示悬浮入口， 然后再返回其他页面操作 会报空指针错误 mActivityDokitViews没有取到值
