### ISSUE TITLE
iOS 复制功能

### ISSUE THREAD

**Issue by ctl0809** [didi/DoraemonKit#412]
iOS 3.0 版本还没有解决复制功能吗？楼主

**Comment by yixiangboy** [comment]
已解决，目前最新版本3.0deta3，接入文章www.dokit.cn

**Comment by ctl0809** [comment]
好的，谢谢楼主


| |
13692453073
邮箱：13692453073@163.com
|

Signature is customized by Netease Mail Master

在2020年03月19日 09:56，yixiangboy 写道：

Closed #412.
