### ISSUE TITLE
fishhook crash

### ISSUE THREAD

**Issue by UKenn** [didi/DoraemonKit#413]
#fishhook Crash修复
# fishhook.c[104]改为:
#if (i < (sizeof(indirect_symbol_bindings) /sizeof(indirect_symbol_bindings[0]))) {
#  indirect_symbol_bindings[i] = cur->rebindings[j].replacement;
#}

**Comment by yixiangboy** [comment]
请问一下 什么场景下 会crash？

**Comment by yixiangboy** [comment]
目前最新代码已经更新到官方最新版本，你可以再试一下。我们本地暂无复现。

**Comment by l1Dan** [comment]
只要打开“启动耗时”就会奔溃

**Comment by robinmo** [comment]
打开NSLog后crash
3.0.4版本
@yixiangboy 

![image](https://github.com/didi/DoKit/assets/6276950/dad96dff-d549-438b-bfb1-8358fdf399cc)

**Comment by iCloudys** [comment]
![WX20240727-201515@2x](https://github.com/user-attachments/assets/fce8afbb-f4ae-49ee-8be8-dd2cc46017a1)
发生了同样的问题
