### ISSUE TITLE
和SwifterSwift有冲突

### ISSUE THREAD

**Issue by enxibaba** [didi/DoraemonKit#414]
版本DoraemonKit (2.0.0):

SwifterSwift.UIImage:2:24: note: found this candidate
    public convenience init(color: UIColor, size: CGSize)
                       ^
DoraemonKit.UIImage:9:30: note: found this candidate
    public /*not inherited*/ init?(color: UIColor!, size: CGSize)

**Comment by yixiangboy** [comment]
欢迎升级到3.0.0正式版本，已经修复
