### ISSUE TITLE
特定场景下会引发 dispatch_once 死锁

### ISSUE THREAD

**Issue by MoLice** [didi/DoraemonKit#416]
假设有如下代码：
```objc
@interface TestVC : UIViewController
@end

@implementation TestVC

+ (void)initialize {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        [TestVC.alloc init];// 这里会触发 -[UIViewController (DoraemonVCProfiler) createAndHookKVOClass]，后者会调用 addObserver:forKeyPath:，而 addObserver:forKeyPath: 会重新触发该 class 的 +initialize，由于同一个 dispatch_once 的前一次调用还未结束就执行第二次调用，引发死锁
    });
}

@end
```

在引入 DoraemonKit 3.0beta3 时启动会产生死锁，具体原因在上述代码的注释里有写。

![image](https://user-images.githubusercontent.com/1190261/77400005-779df380-6de5-11ea-8206-69bbb17fc14c.png)

下面是可复现的 Demo：

[TestDoraemonKit.zip](https://github.com/didi/DoraemonKit/files/4373751/TestDoraemonKit.zip)

相关信息：
- 模拟器 iOS 13.3
- DoraemonKit 版本：3.0beta3

**Comment by SWING1993** [comment]
+1

**Comment by xiwuxisheng** [comment]
+1

**Comment by yixiangboy** [comment]
你们先更新到最新版本3.0.0，然后不要使用健康体检，暂时可以规避这个问题。
目前我这边也没有很好的彻底这种情况的思路，下个版本先加一个黑名单的功能让业务方主动进行规避。
也欢迎社区有好的方案进行解决。

**Comment by yixiangboy** [comment]
欢迎升级到3.0.1，可以通过设置黑名单的方式，规避该问题
