### ISSUE TITLE
ios Demo跑不了

### ISSUE THREAD

**Issue by Oklahomawhore** [didi/DoraemonKit#425]
DoraemonKitDemo.xcworkspace 打开里面没有东西。
DoraemonKitDemo.xcproj 无法运行报错：
`
Showing All Messages
/Users/wangshuzhu/Documents/Test&Demo Projects/DoraemonKit/iOS/DoraemonKitDemo/Pods/Target Support Files/Pods-DoraemonKitDemo/Pods-DoraemonKitDemo.debug.xcconfig: unable to open file (in target "DoraemonKitDemo" in project "DoraemonKitDemo")

`
Xcode Version 11.3.1 (11C505)
Mac Version Catalina 10.15.3 (19D76)
pod version 1.8.4

# Pod install报以下错误

[!] Error installing FBRetainCycleDetector
[!] Failed to download 'FBRetainCycleDetector': [!] /usr/bin/git clone git@github.com:facebook/FBRetainCycleDetector.git /var/folders/40/xh5_7grd7n50qd6vqjrg0p4c0000gn/T/d20200331-3700-9zvlc8 --template= --single-branch --depth 1

Cloning into '/var/folders/40/xh5_7grd7n50qd6vqjrg0p4c0000gn/T/d20200331-3700-9zvlc8'...
Warning: Permanently added the RSA host key for IP address '13.250.177.223' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by yixiangboy** [comment]
通过git@github.com:facebook/FBRetainCycleDetector.git需要设置sshkey才能访问

**Comment by yixiangboy** [comment]
第一种方法 ，你设置一下你的sshkey，第二分钟方法把git@的方式改成https：的方式

**Comment by Oklahomawhore** [comment]
OK 了 ， 感谢！
