### ISSUE TITLE
内部使用的EasyRefreshLayout库在jcenter仓库已经找不到了，无法编译

### ISSUE THREAD

**Issue by qq8803128** [didi/DoraemonKit#426]
刚刚导入debugImplementation ('com.didichuxing.doraemonkit:doraemonkit:3.0.0')
![image](https://user-images.githubusercontent.com/15795651/78025308-66785800-738c-11ea-8833-4dfa95661473.png)
然后发现EasyRefreshLayout在各大仓库已经找不到了  包括jcenter和aliyun

**Comment by jtsky** [comment]
> 刚刚导入debugImplementation ('com.didichuxing.doraemonkit:doraemonkit:3.0.0')
> ![image](https://user-images.githubusercontent.com/15795651/78025308-66785800-738c-11ea-8833-4dfa95661473.png)
> 然后发现EasyRefreshLayout在各大仓库已经找不到了 包括jcenter和aliyun

请添加maven { url "https://jitpack.io" }仓库再试一下

**Comment by qq8803128** [comment]
> > 刚刚导入debugImplementation ('com.didichuxing.doraemonkit:doraemonkit:3.0.0')
> > ![image](https://user-images.githubusercontent.com/15795651/78025308-66785800-738c-11ea-8833-4dfa95661473.png)
> > 然后发现EasyRefreshLayout在各大仓库已经找不到了 包括jcenter和aliyun
> 
> 请添加maven { url "https://jitpack.io" }仓库再试一下

感谢，已经修复这个问题，但是出现了新的问题，
![image](https://user-images.githubusercontent.com/15795651/78094474-35893900-7407-11ea-8baf-5442f49bf0ad.png)
现在不知道如何处理这个问题，我集成这个插件主要是想要使用弱网调试功能，如果不集成这个插件是否可以使用弱网调试，我项目用的http不是okhttp和httpUrlConnect

**Comment by jtsky** [comment]
> > > 刚刚导入debugImplementation ('com.didichuxing.doraemonkit:doraemonkit:3.0.0')
> > > ![image](https://user-images.githubusercontent.com/15795651/78025308-66785800-738c-11ea-8833-4dfa95661473.png)
> > > 然后发现EasyRefreshLayout在各大仓库已经找不到了 包括jcenter和aliyun
> > 
> > 
> > 请添加maven { url "https://jitpack.io" }仓库再试一下
> 
> 感谢，已经修复这个问题，但是出现了新的问题，
> ![image](https://user-images.githubusercontent.com/15795651/78094474-35893900-7407-11ea-8baf-5442f49bf0ad.png)
> 现在不知道如何处理这个问题，我集成这个插件主要是想要使用弱网调试功能，如果不集成这个插件是否可以使用弱网调试，我项目用的http不是okhttp和httpUrlConnect

弱网调试功能是需要依赖插件注入字节码的，而且我们现在只针对okhttp和httpUrlConnect暂时还没有支持HttpClient
