### ISSUE TITLE
iOS组件检查功能希望能展示出对应的属性名

### ISSUE THREAD

**Issue by jozdee** [didi/DoraemonKit#427]
用以检查命名规范的需求

**Comment by jozdee** [comment]
那个最简单的h5任意门有个bug，不能收起键盘没办法点击点击到点击跳转

**Comment by yixiangboy** [comment]
有没有兴趣解决一下 给我们提交PR， 我们有活动正在进行中 https://github.com/didi/DoraemonKit/issues/423

**Comment by yixiangboy** [comment]
> 那个最简单的h5任意门有个bug，不能收起键盘没办法点击点击到点击跳转

你可以通过点击标题栏 收回键盘，下期我们也会优化键盘操作

**Comment by yixiangboy** [comment]
已解决，下个版本3.0.1四月中旬发布

**Comment by songxing10000** [comment]
我也有同样的需求，自己修改源码实现了下
![image](https://user-images.githubusercontent.com/10040131/78364900-d7b84500-75f0-11ea-905c-5dd4c1c3a117.png)

**Comment by yixiangboy** [comment]
> 我也有同样的需求，自己修改源码实现了下
> ![image](https://user-images.githubusercontent.com/10040131/78364900-d7b84500-75f0-11ea-905c-5dd4c1c3a117.png)

欢迎给我们提交PR

**Comment by yixiangboy** [comment]
欢迎升级到3.0.1版本，已经解决这个issues提出的所有问题
