### ISSUE TITLE
Android系统 在设置界面打开悬浮窗，返回主页后崩溃，报的是空异常

### ISSUE THREAD

**Issue by qtybpg** [didi/DoraemonKit#429]
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
	at com.didichuxing.doraemonkit.ui.base.NormalDokitViewManager.onActivityResume(NormalDokitViewManager.java:229)
	at com.didichuxing.doraemonkit.ui.base.NormalDokitViewManager.resumeAndAttachDokitViews(NormalDokitViewManager.java:118)
	at com.didichuxing.doraemonkit.ui.base.DokitViewManager.resumeAndAttachDokitViews(DokitViewManager.java:153)
	at com.didichuxing.doraemonkit.DokitActivityLifecycleCallbacks.resumeAndAttachDokitViews(DokitActivityLifecycleCallbacks.java:166)
	at com.didichuxing.doraemonkit.DokitActivityLifecycleCallbacks.onActivityResumed(DokitActivityLifecycleCallbacks.java:87)
	at android.app.Application.dispatchActivityResumed(Application.java:238)
	at android.app.Activity.onResume(Activity.java:1372)
	at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:514)
请补充如下信息。
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
Android samsung note4 ，华为畅玩8plus
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）
先调用DoraemonKit.show();
再调用setAwaysShowMainIcon（true）会出现这种情况

只保留调用DoraemonKit.show();也会这样

**Comment by jtsky** [comment]
> java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
> at com.didichuxing.doraemonkit.ui.base.NormalDokitViewManager.onActivityResume(NormalDokitViewManager.java:229)
> at com.didichuxing.doraemonkit.ui.base.NormalDokitViewManager.resumeAndAttachDokitViews(NormalDokitViewManager.java:118)
> at com.didichuxing.doraemonkit.ui.base.DokitViewManager.resumeAndAttachDokitViews(DokitViewManager.java:153)
> at com.didichuxing.doraemonkit.DokitActivityLifecycleCallbacks.resumeAndAttachDokitViews(DokitActivityLifecycleCallbacks.java:166)
> at com.didichuxing.doraemonkit.DokitActivityLifecycleCallbacks.onActivityResumed(DokitActivityLifecycleCallbacks.java:87)
> at android.app.Application.dispatchActivityResumed(Application.java:238)
> at android.app.Activity.onResume(Activity.java:1372)
> at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:514)
> 请补充如下信息。
> 
> > Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> > Android samsung note4 ，华为畅玩8plus
> > 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）
> > 先调用DoraemonKit.show();
> > 再调用setAwaysShowMainIcon（true）会出现这种情况
> 
> 只保留调用DoraemonKit.show();也会这样

该问题确实存在，已在新版本中解决，将于近期发布更新

**Comment by jtsky** [comment]
> java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
> at com.didichuxing.doraemonkit.ui.base.NormalDokitViewManager.onActivityResume(NormalDokitViewManager.java:229)
> at com.didichuxing.doraemonkit.ui.base.NormalDokitViewManager.resumeAndAttachDokitViews(NormalDokitViewManager.java:118)
> at com.didichuxing.doraemonkit.ui.base.DokitViewManager.resumeAndAttachDokitViews(DokitViewManager.java:153)
> at com.didichuxing.doraemonkit.DokitActivityLifecycleCallbacks.resumeAndAttachDokitViews(DokitActivityLifecycleCallbacks.java:166)
> at com.didichuxing.doraemonkit.DokitActivityLifecycleCallbacks.onActivityResumed(DokitActivityLifecycleCallbacks.java:87)
> at android.app.Application.dispatchActivityResumed(Application.java:238)
> at android.app.Activity.onResume(Activity.java:1372)
> at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:514)
> 请补充如下信息。
> 
> > Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> > Android samsung note4 ，华为畅玩8plus
> > 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）
> > 先调用DoraemonKit.show();
> > 再调用setAwaysShowMainIcon（true）会出现这种情况
> 
> 只保留调用DoraemonKit.show();也会这样

当前dokit3.0.1版本已经修复 建议升级看下
