### ISSUE TITLE
数据Mock功能，Dokit网站的接口参数只是作用于get请求的参数?  

### ISSUE THREAD

**Issue by lihuixingbj** [didi/DoraemonKit#432]
看了代码，如果网站填了参数，app接口请求URL后面必须有参数才行，不管网站上选的上post还是get。如果选择的是post，按道理和url后面的参数就没必然关系了才对。 如果post不支持参数，选择post后，参数选项是不是可以隐藏？

**Comment by jtsky** [comment]
> 看了代码，如果网站填了参数，app接口请求URL后面必须有参数才行，不管网站上选的上post还是get。如果选择的是post，按道理和url后面的参数就没必然关系了才对。 如果post不支持参数，选择post后，参数选项是不是可以隐藏？

是的 当前我们的dokit只支持path+query的匹配 你的这个提议我会反馈给我们的平台端人员 感谢你的反馈

**Comment by jtsky** [comment]
> 看了代码，如果网站填了参数，app接口请求URL后面必须有参数才行，不管网站上选的上post还是get。如果选择的是post，按道理和url后面的参数就没必然关系了才对。 如果post不支持参数，选择post后，参数选项是不是可以隐藏？

是的 当前我们的dokit只支持path+query的匹配 因为post的body有多中mediaType 假如是form的话还好做 json的话就不好做了 我们后期考虑能不能兼容一下 你的这个提议我会反馈给我们的平台端人员 感谢你的反馈

**Comment by lihuixingbj** [comment]
嗯，我觉得如果要区分body，是不是可以让用户自己填post接口唯一标识字段和值到网站作为接口区分，这样你们适配起来也方便，不管form和json也都是健值对，或者可以像postman那样，提供参数的上传规则，那样取值就更直接了。上面只是我的一点浅见，作为一个开源项目，考虑的肯定更全面，需要适配的场景肯定也更多

**Comment by jtsky** [comment]
> 嗯，我觉得如果要区分body，是不是可以让用户自己填post接口唯一标识字段和值到网站作为接口区分，这样你们适配起来也方便，不管form和json也都是健值对，或者可以像postman那样，提供参数的上传规则，那样取值就更直接了。上面只是我的一点浅见，作为一个开源项目，考虑的肯定更全面，需要适配的场景肯定也更多

新版本v3.1.3和v3.0.5已发布 并且已经支持post匹配 请升级试用
具体请参考文档:http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide
