### ISSUE TITLE
Android编译不过

### ISSUE THREAD

**Issue by stayinxing** [didi/DoraemonKit#433]
> Failed to list versions for com.amap.api:location.
         > Unable to load Maven meta-data from http://artifactory.intra.xiaojukeji.com/artifactory/public/com/amap/api/location/maven-metadata.xml.
            > Could not get resource 'http://artifactory.intra.xiaojukeji.com/artifactory/public/com/amap/api/location/maven-metadata.xml'.
               > Could not GET 'http://artifactory.intra.xiaojukeji.com/artifactory/public/com/amap/api/location/maven-metadata.xml'.
                  > Read timed out

**Comment by jtsky** [comment]
这是demo包吗？

**Comment by stayinxing** [comment]
> 这是demo包吗？

嗯

**Comment by jtsky** [comment]
> > 这是demo包吗？
> 
> 嗯

请拉取最新的demo代码试下 遇到问题可以参考：http://xingyun.xiaojukeji.com/docs/dokit#/SDKProblems
