### ISSUE TITLE
我觉得应该多用一些原生的控件来做

### ISSUE THREAD

**Issue by OnClickListener2048** [didi/DoraemonKit#435]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

这个项目依赖的第三方有点多，导致其他人如果版本和这个项目的不同就无法编译通过，而且导致项目编译时间加长，我觉得应该多用原生控件来做，保证项目的大小

**Comment by yixiangboy** [comment]
iOS 还是 android？

**Comment by OnClickListener2048** [comment]
android

**Comment by jtsky** [comment]
> Please complete the following informations.
> 
> > Expected behavior and actual behavior.
> > Steps to reproduce the problem.
> > Android or iOS? OS version? Brand?
> > More informations such as error messages and stack traces are welcomed.
> 
> 这个项目依赖的第三方有点多，导致其他人如果版本和这个项目的不同就无法编译通过，而且导致项目编译时间加长，我觉得应该多用原生控件来做，保证项目的大小

恩  我最近已经在迁移代码到项目中了 尽量做到都用android原生的库 感谢你的反馈
