### ISSUE TITLE
记录Android编译遇到的问题

### ISSUE THREAD

**Issue by wangfengye** [didi/DoraemonKit#436]
* This version of Android Studio cannot open this project, please retry with Android Studio 3.6 or newer.
  * 问题原因.'com.android.tools.build:gradle:3.6.2'无法再3.6一下的AS上运行.
  * 处理: 尝试降低 `build` 版本.又出现新问题,kotlin代码找不到Androidx下面的viewbinding,3.6才开始支持viewbinding,因此只能升级AS去编译源码

**Comment by wangfengye** [comment]
* 部分依赖无法下载
  * 处理:屏蔽rpc模块,rpc模块存在滴滴内网的依赖

  Android/settting.gradle
``` 
//3行  include ':doraemonkit-rpc'

```
 Android/build.gradle
``` 
//38行  tasks.getByPath(":doraemonkit-rpc:javadocRelease").enabled = false
```

**Comment by jtsky** [comment]
> * 部分依赖无法下载
>   
>   * 处理:屏蔽rpc模块,rpc模块存在滴滴内网的依赖
>   
>   Android/settting.gradle
> 
> ```
> //3行  include ':doraemonkit-rpc'
> ```
> 
> Android/build.gradle
> 
> ```
> //38行  tasks.getByPath(":doraemonkit-rpc:javadocRelease").enabled = false
> ```

感谢你的分享

**Comment by jtsky** [comment]
遇到问题可以参考:http://xingyun.xiaojukeji.com/docs/dokit#/SDKProblems
