### ISSUE TITLE
接口mock失败？

### ISSUE THREAD

**Issue by qtybpg** [didi/DoraemonKit#437]
请补充如下信息。
> 期望的表现和实际的表现。（如有）
已经添加产品和新建接口，有两个场景且规定好json格式数据
但好像没有拦截成功，插件已经映入了
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
Android
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）
> 最好给我们提供可以复现问题的Demo

**Comment by yixiangboy** [comment]
麻烦提供详细的信息，以便我们查询问题所在

**Comment by qtybpg** [comment]
https://www.tianqiapi.com/api 这是我用的天气接口，但是好像没有成功拦截




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yixiangboy"<notifications@github.com&gt;; 
发送时间: 2020年4月8日(星期三) 晚上7:50
收件人: "didi/DoraemonKit"<DoraemonKit@noreply.github.com&gt;; 
抄送: "弃天永不破格"<1004903043@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [didi/DoraemonKit] 接口mock失败？ (#437)





 
麻烦提供详细的信息，以便我们查询问题所在

**Comment by qtybpg** [comment]
而且选择上传模板这个功能也并没有像你们的实例一样可以查看数据模板，显示的是本地不存在mock数据模板

**Comment by yixiangboy** [comment]
android还是iOS？

**Comment by qtybpg** [comment]
Android

**Comment by yixiangboy** [comment]
你加一个qq群，找@didi_Android_金台 看一下

**Comment by yixiangboy** [comment]
qq群在首页文档下面有

**Comment by jtsky** [comment]
已解决
dokit常见问题请参考http://xingyun.xiaojukeji.com/docs/dokit#/SDKProblems
