### ISSUE TITLE
3.1.1-MethodCostUtil 扫描Application 增加计时引起的崩溃

### ISSUE THREAD

**Issue by yangsk94** [didi/DoraemonKit#439]
> Android or iOS? android 9 小米note8
项目中使用了热更新 hotfix，会导致崩溃
  java.lang.NoSuchMethodError: No virtual method recodeMethodCostStart(Ljava/lang/String;)V in class Lcom/didichuxing/doraemonkit/aop/MethodCostUtil; or its super classes (declaration of 'com.didichuxing.doraemonkit.aop.MethodCostUtil' appears in /data/app/com.**-rLD7UHE3_y325eRpdrg==/base.apk)
        at com.*.*.HotfixApp.attachBaseContext(Unknown Source:6)
        at android.app.Application.attach(Application.java:215)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1122)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1065)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5974)
        at android.app.ActivityThread.access$1200(ActivityThread.java:201)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1679)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6864)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Ru

**Comment by jtsky** [comment]
> > Android or iOS? android 9 小米note8
> > 项目中使用了热更新 hotfix，会导致崩溃
> > java.lang.NoSuchMethodError: No virtual method recodeMethodCostStart(Ljava/lang/String;)V in class Lcom/didichuxing/doraemonkit/aop/MethodCostUtil; or its super classes (declaration of 'com.didichuxing.doraemonkit.aop.MethodCostUtil' appears in /data/app/com.**-rLD7UHE3_y325eRpdrg==/base.apk)
> > at com._._.HotfixApp.attachBaseContext(Unknown Source:6)
> > at android.app.Application.attach(Application.java:215)
> > at android.app.Instrumentation.newApplication(Instrumentation.java:1122)
> > at android.app.LoadedApk.makeApplication(LoadedApk.java:1065)
> > at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5974)
> > at android.app.ActivityThread.access$1200(ActivityThread.java:201)
> > at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1679)
> > at android.os.Handler.dispatchMessage(Handler.java:106)
> > at android.os.Looper.loop(Looper.java:201)
> > at android.app.ActivityThread.main(ActivityThread.java:6864)
> > at java.lang.reflect.Method.invoke(Native Method)
> > at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Ru

可以考虑关闭dokit的慢函数
dokitExt {
    dokitPluginSwitch = true
    slowMethodSwitch = true
    bigImgSwitch = true
    //单位为ms 1000ms = 1s
    thresholdTime = 200
    packageNames = ["com.didichuxing.doraemondemo"]
//    packageNames = ["com.didichuxing.doraemondemo","com.didichuxing.doraemonkit"]
}

**Comment by jtsky** [comment]
> > Android or iOS? android 9 小米note8
> > 项目中使用了热更新 hotfix，会导致崩溃
> > java.lang.NoSuchMethodError: No virtual method recodeMethodCostStart(Ljava/lang/String;)V in class Lcom/didichuxing/doraemonkit/aop/MethodCostUtil; or its super classes (declaration of 'com.didichuxing.doraemonkit.aop.MethodCostUtil' appears in /data/app/com.**-rLD7UHE3_y325eRpdrg==/base.apk)
> > at com._._.HotfixApp.attachBaseContext(Unknown Source:6)
> > at android.app.Application.attach(Application.java:215)
> > at android.app.Instrumentation.newApplication(Instrumentation.java:1122)
> > at android.app.LoadedApk.makeApplication(LoadedApk.java:1065)
> > at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5974)
> > at android.app.ActivityThread.access$1200(ActivityThread.java:201)
> > at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1679)
> > at android.os.Handler.dispatchMessage(Handler.java:106)
> > at android.os.Looper.loop(Looper.java:201)
> > at android.app.ActivityThread.main(ActivityThread.java:6864)
> > at java.lang.reflect.Method.invoke(Native Method)
> > at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Ru

暂时的解决方案为关闭dokit的慢函数
dokitExt {
dokitPluginSwitch = true
slowMethodSwitch = true
//单位为ms 1000ms = 1s
thresholdTime = 200
packageNames = ["com.didichuxing.doraemondemo"]
// packageNames = ["com.didichuxing.doraemondemo","com.didichuxing.doraemonkit"]
}


我这边会尽快兼容

**Comment by jtsky** [comment]
> > Android or iOS? android 9 小米note8
> > 项目中使用了热更新 hotfix，会导致崩溃
> > java.lang.NoSuchMethodError: No virtual method recodeMethodCostStart(Ljava/lang/String;)V in class Lcom/didichuxing/doraemonkit/aop/MethodCostUtil; or its super classes (declaration of 'com.didichuxing.doraemonkit.aop.MethodCostUtil' appears in /data/app/com.**-rLD7UHE3_y325eRpdrg==/base.apk)
> > at com._._.HotfixApp.attachBaseContext(Unknown Source:6)
> > at android.app.Application.attach(Application.java:215)
> > at android.app.Instrumentation.newApplication(Instrumentation.java:1122)
> > at android.app.LoadedApk.makeApplication(LoadedApk.java:1065)
> > at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5974)
> > at android.app.ActivityThread.access$1200(ActivityThread.java:201)
> > at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1679)
> > at android.os.Handler.dispatchMessage(Handler.java:106)
> > at android.os.Looper.loop(Looper.java:201)
> > at android.app.ActivityThread.main(ActivityThread.java:6864)
> > at java.lang.reflect.Method.invoke(Native Method)
> > at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Ru

新版本v3.1.3和v3.0.5已发布
具体请参考文档:http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide
dokitExt {
    //整个dokit的插件开关
    dokitPluginSwitch = true
    //函数耗时的开关
    slowMethodSwitch = true
    //大图检测的开关
    bigImgSwitch = true
    //函数耗时的自定义阈值 单位为ms 1000ms = 1s
    thresholdTime = 200
    //在指定的包名业务代码下插入代码
    packageNames = ["com.didichuxing.doraemondemo"]
    //慢函数 黑名单 可以是包名 也可以是全路径的类名
    methodBlacklist = ["com.didichuxing.doraemondemo.dokit"]
}

可以试用methodBlacklist配置排除特定的类和包名下的类
