### ISSUE TITLE
无法显示悬浮窗入口

### ISSUE THREAD

**Issue by apiaoa** [didi/DoraemonKit#440]
确认已经打开悬浮窗权限,集成版本3.1.2
机型:iqoo 
系统版本:Android Q
手动调用 DoraemonKit.showToolPanel()后报错:
System.err: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f090703
System.err:     at android.content.res.ResourcesImpl.getResourceEntryName(ResourcesImpl.java:341)
System.err:     at android.content.res.Resources.getResourceEntryName(Resources.java:2213)
System.err:     at com.blankj.utilcode.util.BarUtils.isNavBarVisible(BarUtils.java:560)
System.err:     at com.blankj.utilcode.util.BarUtils.isNavBarVisible(BarUtils.java:543)
System.err:     at com.didichuxing.doraemonkit.ui.base.NormalDokitViewManager.getDokitRootContentView(NormalDokitViewManager.java:417)
System.err:     at com.didichuxing.doraemonkit.ui.base.NormalDokitViewManager.attach(NormalDokitViewManager.java:353)
System.err:     at com.didichuxing.doraemonkit.ui.base.DokitViewManager.attach(DokitViewManager.java:205)
System.err:     at com.didichuxing.doraemonkit.DoraemonKitReal.showToolPanel(DoraemonKitReal.java:544)
System.err:     at com.didichuxing.doraemonkit.DoraemonKit.showToolPanel(DoraemonKit.java:56)

**Comment by jtsky** [comment]
> 确认已经打开悬浮窗权限,集成版本3.1.2
> 机型:iqoo
> 系统版本:Android Q
> 手动调用 DoraemonKit.showToolPanel()后报错:
> System.err: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f090703
> System.err: at android.content.res.ResourcesImpl.getResourceEntryName(ResourcesImpl.java:341)
> System.err: at android.content.res.Resources.getResourceEntryName(Resources.java:2213)
> System.err: at com.blankj.utilcode.util.BarUtils.isNavBarVisible(BarUtils.java:560)
> System.err: at com.blankj.utilcode.util.BarUtils.isNavBarVisible(BarUtils.java:543)
> System.err: at com.didichuxing.doraemonkit.ui.base.NormalDokitViewManager.getDokitRootContentView(NormalDokitViewManager.java:417)
> System.err: at com.didichuxing.doraemonkit.ui.base.NormalDokitViewManager.attach(NormalDokitViewManager.java:353)
> System.err: at com.didichuxing.doraemonkit.ui.base.DokitViewManager.attach(DokitViewManager.java:205)
> System.err: at com.didichuxing.doraemonkit.DoraemonKitReal.showToolPanel(DoraemonKitReal.java:544)
> System.err: at com.didichuxing.doraemonkit.DoraemonKit.showToolPanel(DoraemonKit.java:56)

新版本v3.1.3版本已经发布 请升级试下 
具体可以参考:http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide
如果还是不行可以加下我们的QQ群在群里@金台

**Comment by apiaoa** [comment]
> > 确认已经打开悬浮窗权限,集成版本3.1.2
> > 机型:iqoo
> > 系统版本:Android Q
> > 手动调用 DoraemonKit.showToolPanel()后报错:
> > System.err: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f090703
> > System.err: at android.content.res.ResourcesImpl.getResourceEntryName(ResourcesImpl.java:341)
> > System.err: at android.content.res.Resources.getResourceEntryName(Resources.java:2213)
> > System.err: at com.blankj.utilcode.util.BarUtils.isNavBarVisible(BarUtils.java:560)
> > System.err: at com.blankj.utilcode.util.BarUtils.isNavBarVisible(BarUtils.java:543)
> > System.err: at com.didichuxing.doraemonkit.ui.base.NormalDokitViewManager.getDokitRootContentView(NormalDokitViewManager.java:417)
> > System.err: at com.didichuxing.doraemonkit.ui.base.NormalDokitViewManager.attach(NormalDokitViewManager.java:353)
> > System.err: at com.didichuxing.doraemonkit.ui.base.DokitViewManager.attach(DokitViewManager.java:205)
> > System.err: at com.didichuxing.doraemonkit.DoraemonKitReal.showToolPanel(DoraemonKitReal.java:544)
> > System.err: at com.didichuxing.doraemonkit.DoraemonKit.showToolPanel(DoraemonKit.java:56)
> 
> 新版本v3.1.3版本已经发布 请升级试下
> 具体可以参考:http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide
> 如果还是不行可以加下我们的QQ群在群里@金台

我的手机测试还是不可以的,报一样的错误,我用模拟器试了下是可以正常显示入口的...
