### ISSUE TITLE
Glide加载图片的File文件时出现java.io.File cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by caiyoufei** [didi/DoraemonKit#441]
![image](https://user-images.githubusercontent.com/11989916/78969758-f018ea00-7b31-11ea-8190-f3f35c4dd5c0.png)

**Comment by caiyoufei** [comment]
使用版本为3.0.2

**Comment by jtsky** [comment]
请升级到3.0.3试下 已经处理了异常

**Comment by jtsky** [comment]
dokitExt {
    //整个dokit的插件开关
    dokitPluginSwitch = true
    //函数耗时的开关
    slowMethodSwitch = true
    //大图检测的开关
    bigImgSwitch = true
    //函数耗时的自定义阈值 单位为ms 1000ms = 1s
    thresholdTime = 200
    //在指定的包名业务代码下插入代码
    packageNames = ["com.didichuxing.doraemondemo"]
}
可以通过以上配置进行字节码插装的开和关。
具体请参考:http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide
