### ISSUE TITLE
以Protocol的方式自定义测试面板，pluginDidLoad方法不回调

### ISSUE THREAD

**Issue by rainedAllNight** [didi/DoraemonKit#442]
以Protocol的方式自定义测试面板，pluginDidLoad方法不回调.
语言： Swift

````
#if DEBUG
import DoraemonKit

class DoKitUserInfoPlugin: NSObject, DoraemonPluginProtocol {
    func pluginDidLoad() {
        print("tap")
    }
    
}
#endif

初始化

#if DEBUG
        DoraemonManager.shareInstance().addPlugin(withTitle: "哈哈", icon: "doraemon_default", desc: "doraemon_default", pluginName: "", atModule: "业务专区") { (data) in
            print("hahah")
        }
        DoraemonManager.shareInstance().addPlugin(withTitle: "用户信息", icon: "doraemon_default", desc: "用户信息查看", pluginName: "DoKitUserInfoPlugin", atModule: "业务专区")
        DoraemonManager.shareInstance().install(withPid: "****")
        
       #endif
````
试了block的方式是可以的，Class+Protocol的方式不回调

**Comment by yixiangboy** [comment]
需要把swift的类和方法，暴露给OC，你试试下面的代码
import DoraemonKit

@objc(DoraemonSwiftPlugin)
class DoraemonSwiftPlugin : NSObject,DoraemonPluginProtocol{
    @objc func pluginDidLoad(){
        print("pluginDidLoad")
    }
}

**Comment by SeongBrave** [comment]
`public class DoraemonSwiftPlugin : NSObject , DoraemonPluginProtocol {
    @objc
    public func pluginDidLoad() {
        "appenvconfig".routePage()
    }
}
`

@yixiangboy 类似这样的，好像没有回调
