### ISSUE TITLE
最新3.1.2版本不支持https://github.com/jeasonlzy/NineGridView

### ISSUE THREAD

**Issue by huanghaoming** [didi/DoraemonKit#444]
你好，我使用了最新的版本（android）3.1.2后，发现不支持一个库。。
https://github.com/jeasonlzy/NineGridView
这个库是一个九宫格的图片库，我通过分析后确认是因为用了dokit的3.1.2版本。。（2.2.1版本可以）
根据后台日志，里面有个requestLayout函数在疯狂调用。。

虽然无法提供完整代码，，不过请开发团队能否联想一下是否改动了什么地方而导致glide加载不出来。。。。

**Comment by jtsky** [comment]
> 你好，我使用了最新的版本（android）3.1.2后，发现不支持一个库。。
> https://github.com/jeasonlzy/NineGridView
> 这个库是一个九宫格的图片库，我通过分析后确认是因为用了dokit的3.1.2版本。。（2.2.1版本可以）
> 根据后台日志，里面有个requestLayout函数在疯狂调用。。
> 
> 虽然无法提供完整代码，，不过请开发团队能否联想一下是否改动了什么地方而导致glide加载不出来。。。。

这个问题我大概知道是什么问题了 应该是我插入的Transformation有问题，当前的解决方案是关掉大图监测的开关，代码如下:
dokitExt {
    //整个dokit的插件开关
    dokitPluginSwitch = true
    //函数耗时的开关
    slowMethodSwitch = true
    //大图检测的开关
    bigImgSwitch = true
    //函数耗时的自定义阈值 单位为ms 1000ms = 1s
    thresholdTime = 200
    //在指定的包名业务代码下插入代码
    packageNames = ["com.didichuxing.doraemondemo"]
}
将bigImgSwitch改成false并clean重新运行即可。然后我近期会发布新版本，到时候可以升级看下。
详细文档:http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide

**Comment by huanghaoming** [comment]
我用你的方式试了一下。。。（一定要clean才行），，是可行的。。。。

**Comment by jtsky** [comment]
> 我用你的方式试了一下。。。（一定要clean才行），，是可行的。。。。

恩 是的 修改dokitExt的值以后一定要clean一下 因为这是gradle编译缓存导致的
