### ISSUE TITLE
最新版本3.1.2.。。。java.lang.NoClassDefFoundError: com.didichuxing.doraemonkit.kit.largepicture.LargePictureManager$Holder

### ISSUE THREAD

**Issue by huanghaoming** [didi/DoraemonKit#445]
我关闭了大图检测
bigImgSwitch=false。。。。然后偶尔会出现这个奔溃

**Comment by jtsky** [comment]
> 我关闭了大图检测
> bigImgSwitch=false。。。。然后偶尔会出现这个奔溃

有具体的操作行为路径吗 你的图片库是哪个

**Comment by huanghaoming** [comment]
> > 我关闭了大图检测
> 
> > bigImgSwitch=false。。。。然后偶尔会出现这个奔溃
> 
> 
> 
> 有具体的操作行为路径吗 你的图片库是哪个

用的glide，都是加载图片的时候奔溃的，明明没有启用大图检测啊

**Comment by jtsky** [comment]
> > > 我关闭了大图检测
> > 
> > 
> > > bigImgSwitch=false。。。。然后偶尔会出现这个奔溃
> > 
> > 
> > 有具体的操作行为路径吗 你的图片库是哪个
> 
> 用的glide，都是加载图片的时候奔溃的，明明没有启用大图检测啊

新版本v3.1.3和v3.0.5已发布 请升级试一下
具体请参考文档:http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide
