### ISSUE TITLE
使用picasoo加载本地图片Crash

### ISSUE THREAD

**Issue by z2wenfa** [didi/DoraemonKit#446]
使用的Android模拟器

java.lang.RuntimeException: Transformation Dokit&Picasso&LargeBitmapTransformation crashed with exception.

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference

  Picasso.Builder(this).memoryCache(lruCache!!).build().load(R.drawable.login_bg)
            .memoryPolicy(MemoryPolicy.NO_CACHE).into(ivBg)

**Comment by jtsky** [comment]
> 使用的Android模拟器
> 
> java.lang.RuntimeException: Transformation Dokit&Picasso&LargeBitmapTransformation crashed with exception.
> 
> java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
> 
> Picasso.Builder(this).memoryCache(lruCache!!).build().load(R.drawable.login_bg)
> .memoryPolicy(MemoryPolicy.NO_CACHE).into(ivBg)

用的是哪个版本的dokit

**Comment by z2wenfa** [comment]
> > 使用的Android模拟器
> > java.lang.RuntimeException: Transformation Dokit&Picasso&LargeBitmapTransformation crashed with exception.
> > java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
> > Picasso.Builder(this).memoryCache(lruCache!!).build().load(R.drawable.login_bg)
> > .memoryPolicy(MemoryPolicy.NO_CACHE).into(ivBg)
> 
> 用的是哪个版本的dokit



> > 使用的Android模拟器
> > java.lang.RuntimeException: Transformation Dokit&Picasso&LargeBitmapTransformation crashed with exception.
> > java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
> > Picasso.Builder(this).memoryCache(lruCache!!).build().load(R.drawable.login_bg)
> > .memoryPolicy(MemoryPolicy.NO_CACHE).into(ivBg)
> 
> 用的是哪个版本的dokit

3.1.1

**Comment by z2wenfa** [comment]
使用最新的3.1.2版本发现这个问题不存在了
