### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by wankey** [didi/DoraemonKit#447]
3.1.2
build.gradle(:app)中加入apply plugin: 'com.didi.dokit'后，报：
`
Caused by: java.lang.NullPointerException
	at com.didichuxing.doraemonkit.plugin.DokitExtUtil.init(DokitExtUtil.java:88)
	at com.didichuxing.doraemonkit.plugin.DoKitPlugin$1.execute(DoKitPlugin.java:45)
`

**Comment by jtsky** [comment]
> 3.1.2
> build.gradle(:app)中加入apply plugin: 'com.didi.dokit'后，报：
> `Caused by: java.lang.NullPointerException at com.didichuxing.doraemonkit.plugin.DokitExtUtil.init(DokitExtUtil.java:88) at com.didichuxing.doraemonkit.plugin.DoKitPlugin$1.execute(DoKitPlugin.java:45)`

请问你是怎么接入的 可以参考下demo的接入方式

**Comment by wankey** [comment]
就按照demo来的，不应用插件没问题，一用就报错，但是新建的空项目就正常。不确定插件与项目中的什么产生了冲突

**Comment by jtsky** [comment]
> 就按照demo来的，不应用插件没问题，一用就报错，但是新建的空项目就正常。不确定插件与项目中的什么产生了冲突

新版本v3.1.3和v3.0.5已发布
具体请参考文档:http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide
请升级到新版本试下

**Comment by Even201314** [comment]
3.1.4 也有报错。
app build.gradle 加上 `apply plugin: 'com.didi.dokit'
`后，报`> java.lang.NullPointerException (no error message)`
```groovy
apply plugin: 'com.android.application'
apply plugin: 'com.didi.dokit'
```
报错信息
```
Caused by: java.lang.NullPointerException
	at com.didichuxing.doraemonkit.plugin.DokitExtUtil.init(DokitExtUtil.java:102)
	at com.didichuxing.doraemonkit.plugin.DoKitPlugin$1.execute(DoKitPlugin.java:45)
	at com.didichuxing.doraemonkit.plugin.DoKitPlugin$1.execute(DoKitPlugin.java:40)
```

如果不添加`apply plugin: 'com.didi.dokit`，也会报`找不到com.google.common.util.concurrent.ListenableFuture的类文件`，应该是由于项目使用了`Worker`
```groovy
  implementation 'androidx.appcompat:appcompat:1.2.0-beta01'

  def work_version = "2.3.4"
  implementation "androidx.work:work-runtime:$work_version"
  implementation "androidx.work:work-rxjava2:$work_version"

  debugImplementation "com.didichuxing.doraemonkit:doraemonkit:3.1.4"
  releaseImplementation "com.didichuxing.doraemonkit:doraemonkit-no-op:3.1.4"
```

**Comment by jtsky** [comment]
> 3.1.4 也有报错。
> app build.gradle 加上 `apply plugin: 'com.didi.dokit' `后，报`> java.lang.NullPointerException (no error message)`
> 
> ```groovy
> ### project build.gradle
>   dependencies {
>     classpath 'com.android.tools.build:gradle:3.5.3'
>     classpath 'com.didichuxing.doraemonkit:doraemonkit-plugin:3.1.4'
>   }
> 
> ###   app build.gradle
> apply plugin: 'com.android.application'
> apply plugin: 'com.didi.dokit'
> ```
> 
> 报错信息
> 
> ```
> Caused by: java.lang.NullPointerException
> 	at com.didichuxing.doraemonkit.plugin.DokitExtUtil.init(DokitExtUtil.java:102)
> 	at com.didichuxing.doraemonkit.plugin.DoKitPlugin$1.execute(DoKitPlugin.java:45)
> 	at com.didichuxing.doraemonkit.plugin.DoKitPlugin$1.execute(DoKitPlugin.java:40)
> ```
> 
> 如果不添加`apply plugin: 'com.didi.dokit`，也会报`找不到com.google.common.util.concurrent.ListenableFuture的类文件`，应该是由于项目使用了`Worker`
> 
> ```groovy
>   implementation 'androidx.appcompat:appcompat:1.2.0-beta01'
> 
>   def work_version = "2.3.4"
>   implementation "androidx.work:work-runtime:$work_version"
>   implementation "androidx.work:work-rxjava2:$work_version"
> 
>   debugImplementation "com.didichuxing.doraemonkit:doraemonkit:3.1.4"
>   releaseImplementation "com.didichuxing.doraemonkit:doraemonkit-no-op:3.1.4"
> ```

你的项目配置了ApplicationId吗？ 报的应该是ApplicationId为空

**Comment by jtsky** [comment]
> 3.1.4 也有报错。
> app build.gradle 加上 `apply plugin: 'com.didi.dokit' `后，报`> java.lang.NullPointerException (no error message)`
> 
> ```groovy
> ### project build.gradle
>   dependencies {
>     classpath 'com.android.tools.build:gradle:3.5.3'
>     classpath 'com.didichuxing.doraemonkit:doraemonkit-plugin:3.1.4'
>   }
> 
> ###   app build.gradle
> apply plugin: 'com.android.application'
> apply plugin: 'com.didi.dokit'
> ```
> 
> 报错信息
> 
> ```
> Caused by: java.lang.NullPointerException
> 	at com.didichuxing.doraemonkit.plugin.DokitExtUtil.init(DokitExtUtil.java:102)
> 	at com.didichuxing.doraemonkit.plugin.DoKitPlugin$1.execute(DoKitPlugin.java:45)
> 	at com.didichuxing.doraemonkit.plugin.DoKitPlugin$1.execute(DoKitPlugin.java:40)
> ```
> 
> 如果不添加`apply plugin: 'com.didi.dokit`，也会报`找不到com.google.common.util.concurrent.ListenableFuture的类文件`，应该是由于项目使用了`Worker`
> 
> ```groovy
>   implementation 'androidx.appcompat:appcompat:1.2.0-beta01'
> 
>   def work_version = "2.3.4"
>   implementation "androidx.work:work-runtime:$work_version"
>   implementation "androidx.work:work-rxjava2:$work_version"
> 
>   debugImplementation "com.didichuxing.doraemonkit:doraemonkit:3.1.4"
>   releaseImplementation "com.didichuxing.doraemonkit:doraemonkit-no-op:3.1.4"
> ```

dokit 新版本已发布 请参考以下文档升级:http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide
注意:
插件配置模块的配置和以前有所区别，请重点关注下。

假如新的版本已经解决你的问题，可以选择自己关闭此issues或者回复此条信息由我来关闭。

**Comment by wankey** [comment]
已可使用，根源在于我的项目因为配置了productFlavors，所以default里没有配置applicationId导致
