### ISSUE TITLE
java.lang.ClassCastException: android.support.v7.widget.ContentFrameLayout cannot be cast to androidx.appcompat.widget.ContentFrameLayout

### ISSUE THREAD

**Issue by qcxu2** [didi/DoraemonKit#448]
java.lang.ClassCastException: android.support.v7.widget.ContentFrameLayout cannot be cast to androidx.appcompat.widget.ContentFrameLayout

异常退出。机器是Android8.0

**Comment by jtsky** [comment]
> java.lang.ClassCastException: android.support.v7.widget.ContentFrameLayout cannot be cast to androidx.appcompat.widget.ContentFrameLayout
> 
> 异常退出。机器是Android8.0

请确认你的项目是否已经升级androidx。
![image](https://user-images.githubusercontent.com/4486497/79541377-4949c600-80bc-11ea-9dee-0abe6493010f.png)

**Comment by qcxu2** [comment]
历史项目无法升级X。请问还有其他办法解决吗？

From: 金台
Date: 2020-04-17 15:01
To: didi/DoraemonKit
CC: qcxu2; Author
Subject: Re: [didi/DoraemonKit] java.lang.ClassCastException: android.support.v7.widget.ContentFrameLayout cannot be cast to androidx.appcompat.widget.ContentFrameLayout (#448)
java.lang.ClassCastException: android.support.v7.widget.ContentFrameLayout cannot be cast to androidx.appcompat.widget.ContentFrameLayout
异常退出。机器是Android8.0
请确认你的项目是否已经升级androidx。

**Comment by jtsky** [comment]
> 历史项目无法升级X。请问还有其他办法解决吗？ From: 金台 Date: 2020-04-17 15:01 To: didi/DoraemonKit CC: qcxu2; Author Subject: Re: [didi/DoraemonKit] java.lang.ClassCastException: android.support.v7.widget.ContentFrameLayout cannot be cast to androidx.appcompat.widget.ContentFrameLayout (#448) java.lang.ClassCastException: android.support.v7.widget.ContentFrameLayout cannot be cast to androidx.appcompat.widget.ContentFrameLayout 异常退出。机器是Android8.0 请确认你的项目是否已经升级androidx。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

新版本v3.1.3和v3.0.5已发布
具体请参考文档:http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide

请接入3.0.5版本
