### ISSUE TITLE
编译时java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by tingban** [didi/DoraemonKit#451]
Execution failed for task ':k-router:transformClassesWithDokitCommTransformForXxxxDebug'.
> java.lang.IllegalArgumentException
多渠道多module下引入时编译不通过，报了上面的异常。

**Comment by jtsky** [comment]
> Execution failed for task ':k-router:transformClassesWithDokitCommTransformForXxxxDebug'.
> 
> > java.lang.IllegalArgumentException
> > 多渠道多module下引入时编译不通过，报了上面的异常。

如果是多渠道包的话需要加指定的渠道前缀 比如你的渠道为xxx 引入的时候需要使用xxxImplementation

**Comment by tingban** [comment]
并不好使，尝试了xxxDebugImplementation和xxxImplementation都是报同样的错误

**Comment by tingban** [comment]
> > Execution failed for task ':k-router:transformClassesWithDokitCommTransformForXxxxDebug'.
> > > java.lang.IllegalArgumentException
> > > 多渠道多module下引入时编译不通过，报了上面的异常。
> 
> 如果是多渠道包的话需要加指定的渠道前缀 比如你的渠道为xxx 引入的时候需要使用xxxImplementation

并不好使，尝试了xxxDebugImplementation和xxxImplementation都是报同样的错误

**Comment by jtsky** [comment]
> > > Execution failed for task ':k-router:transformClassesWithDokitCommTransformForXxxxDebug'.
> > > > java.lang.IllegalArgumentException
> > > > 多渠道多module下引入时编译不通过，报了上面的异常。
> > 
> > 
> > 如果是多渠道包的话需要加指定的渠道前缀 比如你的渠道为xxx 引入的时候需要使用xxxImplementation
> 
> 并不好使，尝试了xxxDebugImplementation和xxxImplementation都是报同样的错误

你可以加下我们的QQ群  并在群里@金台
