### ISSUE TITLE
3.1.3 okhttp  interceptors 重复添加拦截器

### ISSUE THREAD

**Issue by Aracoix** [didi/DoraemonKit#453]
在 获取 builder.interceptors()时
class com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DoraemonInterceptor
class com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.LargePictureInterceptor
 class com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.MockInterceptor
以上三个interceptor会注册两次

**Comment by jtsky** [comment]
> 在 获取 builder.interceptors()时
> class com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DoraemonInterceptor
> class com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.LargePictureInterceptor
> class com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.MockInterceptor
> 以上三个interceptor会注册两次

你好可以加一下我们的QQ群详细交流一下吗 可以在群里@金台

> 在 获取 builder.interceptors()时
> class com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.DoraemonInterceptor
> class com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.LargePictureInterceptor
> class com.didichuxing.doraemonkit.kit.network.okhttp.interceptor.MockInterceptor
> 以上三个interceptor会注册两次

该问题已被定位和修复将会在下个版本v3.1.4中发布
