### ISSUE TITLE
iOS UIWebView 会移除吗

### ISSUE THREAD

**Issue by d553296416** [didi/DoraemonKit#454]
UIWebview apple 会在今年正式禁止。目前DoraemonKit  还存在UIWebview 。 如果配置configurations 只在debug 环境下生效。未来是否可以规避掉apple 的审核呢

**Comment by yixiangboy** [comment]
如果配置configurations = debug，线上的安装包是不包含任何dokit的代码的，放心。
同时我们也会在下个版本3.0.2中，去掉UIWebView的相关代码。感谢反馈。

**Comment by d553296416** [comment]
谢谢回复
