### ISSUE TITLE
建议可以删除UIWebView啦，有拒审风险的哦

### ISSUE THREAD

**Issue by jozdee** [didi/DoraemonKit#456]
Apple will no longer accept submissions of new apps that use UIWebView as of April 30, 2020 and app updates that use UIWebView as of December 2020. Instead, use WKWebView for improved security and reliability. Learn more.

**Comment by yixiangboy** [comment]
下个版本去掉。

**Comment by mnz12138** [comment]
什么时候可以去掉，提交被拒了😟

**Comment by yixiangboy** [comment]
> 什么时候可以去掉，提交被拒了😟

下个版本去掉。但是请用户注意 我们DoKit请在debug环境下集成，不会带到线上去的，显然也不会被苹果审核，请查看你的接入方式是否正确。

**Comment by yixiangboy** [comment]
升级到3.0.2，已经去掉了
