### ISSUE TITLE
Android的release编译插件不生效

### ISSUE THREAD

**Issue by svenjung** [didi/DoraemonKit#460]
hunter是支持指定build的Variant的，到dokit里面就一刀切了，release直接过滤掉

希望把Plugin里面的限制去掉
//如果task包含release 则不进行字节码替换
        for (String taskName : taskNames) {
            if (taskName.contains("Release")) {
                return;
            }
        }

**Comment by jtsky** [comment]
> hunter是支持指定build的Variant的，到dokit里面就一刀切了，release直接过滤掉
> 
> 希望把Plugin里面的限制去掉
> //如果task包含release 则不进行字节码替换
>         for (String taskName : taskNames) {
>             if (taskName.contains("Release")) {
>                 return;
>             }
>         }
> 
> 

可以查看一下首页说明 dokit当前的定位就是协助线下开发的 所有的功能都没有在线上得到拱验证 所以为了避免功能带到线上造成线上问题 所以特意加了这个判断

**Comment by svenjung** [comment]
问题是，并不是release就是线上包

**Comment by svenjung** [comment]
> > hunter是支持指定build的Variant的，到dokit里面就一刀切了，release直接过滤掉
> > 希望把Plugin里面的限制去掉
> > //如果task包含release 则不进行字节码替换
> > for (String taskName : taskNames) {
> > if (taskName.contains("Release")) {
> > return;
> > }
> > }
> 
> 可以查看一下首页说明 dokit当前的定位就是协助线下开发的 所有的功能都没有在线上得到拱验证 所以为了避免功能带到线上造成线上问题 所以特意加了这个判断
问题是，并不是release就是线上包
