### ISSUE TITLE
减少/关闭在编译时的日志

### ISSUE THREAD

**Issue by YuYongzhi** [didi/DoraemonKit#467]
在命令行编译项目时，会有很多DoKit相关的日志，对开发者是没有用的，能否关闭，或通过参数控制关闭在编译时的显示
![image](https://user-images.githubusercontent.com/6104276/81470156-d98ead00-921b-11ea-80ee-9b7430fe2d42.png)

**Comment by jtsky** [comment]
> 在命令行编译项目时，会有很多DoKit相关的日志，对开发者是没有用的，能否关闭，或通过参数控制关闭在编译时的显示
> ![image](https://user-images.githubusercontent.com/6104276/81470156-d98ead00-921b-11ea-80ee-9b7430fe2d42.png)

可以的 我增加个开关

**Comment by jtsky** [comment]
> 在命令行编译项目时，会有很多DoKit相关的日志，对开发者是没有用的，能否关闭，或通过参数控制关闭在编译时的显示
> ![image](https://user-images.githubusercontent.com/6104276/81470156-d98ead00-921b-11ea-80ee-9b7430fe2d42.png)

dokit 新版本已发布 请参考以下文档升级:http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide
注意:
插件配置模块的配置和以前有所区别，请重点关注下。

假如新的版本已经解决你的问题，可以选择自己关闭此issues或者回复此条信息由我来关闭。
