### ISSUE TITLE
release task 用不了

### ISSUE THREAD

**Issue by ValuesFeng** [didi/DoraemonKit#468]
DoKitExt 能都新增isDebug 让开发者自己传入

CI 出发默认打的是release包，我们有自己开发配置的debug设定
plugin中根据task name判定release，这个硬编码是不是有点不友好

**Comment by jtsky** [comment]
> DoKitExt 能都新增isDebug 让开发者自己传入
> 
> CI 出发默认打的是release包，我们有自己开发配置的debug设定
> plugin中根据task name判定release，这个硬编码是不是有点不友好

这个主要还是出于绝大部分的项目安全考虑的  如果要是根据用户自定义传入万一漏掉关闭就会影响release包的代码 那造成的影响很大  看社区反馈吧  如果大家对于这个有强烈需要的话 我会考虑增加个开关

**Comment by ValuesFeng** [comment]
@jtsky  那我只能fork 一个自己改了。给几个提示呗，哪些地方需要注意下的

**Comment by jtsky** [comment]
> @jtsky  那我只能fork 一个自己改了。给几个提示呗，哪些地方需要注意下的

因为我们的功能没有经过线上验证 所以在性能检测这方面你得看下兼容性而且得经过充分的测试。如果上线以后效果可以的话，麻烦可以在群里说一下，我们看看后期是不是可以做到线上去
