### ISSUE TITLE
android 开启流量检测开关会导致网络请求进行两次

### ISSUE THREAD

**Issue by Aracoix** [didi/DoraemonKit#469]
通过抓包发现，项目源码也会导致请求两次

**Comment by Aracoix** [comment]
android 端

**Comment by jtsky** [comment]
> android 端

已定位到问题，下个版本会修复

**Comment by huizai0613** [comment]
我也 发现了 ，修复了 ，麻烦告知 一下 谢谢

**Comment by jtsky** [comment]
> 我也 发现了 ，修复了 ，麻烦告知 一下 谢谢

你可以把你发现的代码添一下 看是不是同一块代码 应该是同一个 request请求了两次

**Comment by huizai0613** [comment]
你能贴一下 哪个 地方  request请求了两次 我这边 也看下

**Comment by huizai0613** [comment]
![image](https://user-images.githubusercontent.com/5644264/82109544-6fb95a80-9769-11ea-9b60-cb76e4e219e6.png)
我看了 是這裏

**Comment by jtsky** [comment]
> ![image](https://user-images.githubusercontent.com/5644264/82109544-6fb95a80-9769-11ea-9b60-cb76e4e219e6.png)
> 我看了 是這裏

是的 就是这里  多proceed了一次

**Comment by jtsky** [comment]
> ![image](https://user-images.githubusercontent.com/5644264/82109544-6fb95a80-9769-11ea-9b60-cb76e4e219e6.png)
> 我看了 是這裏

dokit 新版本已发布 请参考以下文档升级:http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide
注意:
插件配置模块的配置和以前有所区别，请重点关注下。

假如新的版本已经解决你的问题，可以选择自己关闭此issues或者回复此条信息由我来关闭。
