### ISSUE TITLE
NotFoundException:Unable to find resource ID #0x7f0900b6

### ISSUE THREAD

**Issue by SheepYang1993** [didi/DoraemonKit#470]
android DoraemonKit 2.0.2版本
```
android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f0900b6
    at android.content.res.ResourcesImpl.getResourceEntryName(ResourcesImpl.java:302)
    at android.content.res.Resources.getResourceEntryName(Resources.java:2140)
    at com.blankj.utilcode.util.BarUtils.isNavBarVisible(BarUtils.java:559)
com.didichuxing.doraemonkit.DoraemonKit.resumeAndAttachDokitViews(DoraemonKit.java:491)
    at com.didichuxing.doraemonkit.DoraemonKit.access$300(DoraemonKit.java:74)
    at com.didichuxing.doraemonkit.DoraemonKit$2.onActivityResumed(DoraemonKit.java:211)
```
![image](https://user-images.githubusercontent.com/15150244/81671048-199f9b00-947b-11ea-8da8-eb351653c20b.png)
![image](https://user-images.githubusercontent.com/15150244/81671060-1f957c00-947b-11ea-9d16-e5ee4a9bf8a1.png)

**Comment by jtsky** [comment]
> android DoraemonKit 2.0.2版本
> 
> ```
> android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f0900b6
>     at android.content.res.ResourcesImpl.getResourceEntryName(ResourcesImpl.java:302)
>     at android.content.res.Resources.getResourceEntryName(Resources.java:2140)
>     at com.blankj.utilcode.util.BarUtils.isNavBarVisible(BarUtils.java:559)
> com.didichuxing.doraemonkit.DoraemonKit.resumeAndAttachDokitViews(DoraemonKit.java:491)
>     at com.didichuxing.doraemonkit.DoraemonKit.access$300(DoraemonKit.java:74)
>     at com.didichuxing.doraemonkit.DoraemonKit$2.onActivityResumed(DoraemonKit.java:211)
> ```
> 
> ![image](https://user-images.githubusercontent.com/15150244/81671048-199f9b00-947b-11ea-8da8-eb351653c20b.png)
> ![image](https://user-images.githubusercontent.com/15150244/81671060-1f957c00-947b-11ea-9d16-e5ee4a9bf8a1.png)

请按照文档http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide 升级到最新版本试下

**Comment by SheepYang1993** [comment]
部分项目还没升级androidx，所以暂时还是用的support版本
