### ISSUE TITLE
取色器截图服务未提供，Manifest未配置，是还没有适配好吗

### ISSUE THREAD

**Issue by ljf1239848066** [didi/DoraemonKit#472]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）
> 最好给我们提供可以复现问题的Demo

**Comment by jtsky** [comment]
dokit版本是多少  系统版本是多少？

**Comment by ljf1239848066** [comment]
文档中无说明，我看 demo AndroidManifest 服务中有截图服务 service 的配置，自己 APP 加了后正常了，建议文档中增加一下说明。
