### ISSUE TITLE
Android 官方文档错误,及初始化错误

### ISSUE THREAD

**Issue by tangwanchao** [didi/DoraemonKit#475]
版本:3.1.5
查看文档地址:http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide

问题 1:官方文档有误
依照官方文档的初始化方法:
DoraemonKit.install(application,null,"productId") 报错

问题2:初始化后没有 Doraemonkit  内置工具
尝试了如下两个方法,均没有内置工具
1.DoraemonKit.install(application)
2.DoraemonKit.install(application,"productId")

**Comment by jtsky** [comment]
> 版本:3.1.5
> 查看文档地址:http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide
> 
> 问题 1:官方文档有误
> 依照官方文档的初始化方法:
> DoraemonKit.install(application,null,"productId") 报错
> 
> 问题2:初始化后没有 Doraemonkit 内置工具
> 尝试了如下两个方法,均没有内置工具
> 1.DoraemonKit.install(application)
> 2.DoraemonKit.install(application,"productId")

为了兼容原先的老的api,dokit这边提供了多个初始化方案，一个是默认分组一个是自定义分组。请自主选择接入。
第二个问题，没有内置工具的具体表现是什么样的。可以在群里找下我吗？我叫金台
