### ISSUE TITLE
流量监控抓不到数据

### ISSUE THREAD

**Issue by JesseWo** [didi/DoraemonKit#477]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
Android10，miui
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）
> 最好给我们提供可以复现问题的Demo

okhttp:3.12.0，doraemonkit 3.1.5，流量监控一直抓不到数据。（早期使用的手动添加interceptor这种方式，是可以抓到数据的）

**Comment by jtsky** [comment]
> Please complete the following informations.
> 
> > Expected behavior and actual behavior.
> > Steps to reproduce the problem.
> > Android or iOS? OS version? Brand?
> > More informations such as error messages and stack traces are welcomed.
> 
> 请补充如下信息。
> 
> > 期望的表现和实际的表现。（如有）
> > 问题重现的步骤。（如有）
> > Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> > Android10，miui
> > 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）
> > 最好给我们提供可以复现问题的Demo
> 
> okhttp:3.12.0，doraemonkit 3.1.5，流量监控一直抓不到数据。（早期使用的手动添加interceptor这种方式，是可以抓到数据的）

dokit 新版本已发布 请参考以下文档升级:http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide
或者把okhttp版本升级到3.12.1试试。
注意:
插件配置模块的配置和以前有所区别，请重点关注下。

假如新的版本已经解决你的问题，可以选择自己关闭此issues或者回复此条信息由我来关闭。
