### ISSUE TITLE
第一次接入DoraemonKit，构建时的问题

### ISSUE THREAD

**Issue by feiyang1235** [didi/DoraemonKit#482]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）
> 最好给我们提供可以复现问题的Demo

在app模块加入 apply plugin: 'com.didi.dokit'代码时。得到构建错误
![image](https://user-images.githubusercontent.com/20432997/82191058-8f48b280-9924-11ea-9f47-598912b16f59.png)
我的gradle版本是
![image](https://user-images.githubusercontent.com/20432997/82191123-a4bddc80-9924-11ea-92d7-e96b86fd2e8d.png)

**Comment by jtsky** [comment]
> Please complete the following informations.
> 
> > Expected behavior and actual behavior.
> > Steps to reproduce the problem.
> > Android or iOS? OS version? Brand?
> > More informations such as error messages and stack traces are welcomed.
> 
> 请补充如下信息。
> 
> > 期望的表现和实际的表现。（如有）
> > 问题重现的步骤。（如有）
> > Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> > 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）
> > 最好给我们提供可以复现问题的Demo
> 
> 在app模块加入 apply plugin: 'com.didi.dokit'代码时。得到构建错误
> ![image](https://user-images.githubusercontent.com/20432997/82191058-8f48b280-9924-11ea-9f47-598912b16f59.png)
> 我的gradle版本是
> ![image](https://user-images.githubusercontent.com/20432997/82191123-a4bddc80-9924-11ea-92d7-e96b86fd2e8d.png)

可以考虑升级一下gradle 到3.4.+以上试试

**Comment by feiyang1235** [comment]
项目中集成了bugly的tinker热修复，貌似gradle 到3.4.+以上，tinker那边又有问题~   
传说中的鱼与熊掌不可兼得？

**Comment by jtsky** [comment]
> 项目中集成了bugly的tinker热修复，貌似gradle 到3.4.+以上，tinker那边又有问题~
> 传说中的鱼与熊掌不可兼得？

dokit 新版本已发布 请参考以下文档升级:http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide
同时gradle版本可以选择3.3.0试试
注意:
插件配置模块的配置和以前有所区别，请重点关注下。

假如新的版本已经解决你的问题，可以选择自己关闭此issues或者回复此条信息由我来关闭。

**Comment by feiyang1235** [comment]
已解决，在gradle3.2.1版本上正常运行

**Comment by wxyjevol** [comment]
> 已解决，在gradle3.2.1版本上正常运行

你好，请问下上述的问题是怎样解决的呢，我也碰到了相同的问题。

**Comment by liuleshuai** [comment]
tinker是不支持java1.8的，请问楼主是怎么解决这个问题的呢
