### ISSUE TITLE
集成安卓3.0.6 弹出框中工具清单是空的。

### ISSUE THREAD

**Issue by BlockCanary** [didi/DoraemonKit#483]
集成安卓3.0.6 弹出框中工具清单是空的。没有任何一个工具展示出来。 在Application中初始化 DoraemonKit.install(application,null,"pId");。第二个参数传null 会报错；Ambiguous method call;

**Comment by jtsky** [comment]
参考文档:http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide
