### ISSUE TITLE
关于将query定义成了NSDictionary

### ISSUE THREAD

**Issue by miyazaki2048** [didi/DoraemonKit#484]
### 问题描述

iOS端定义Mock地址的query属性使用了`key-value`结构，虽然一般很少会遇到query中含有重名的`key`，但理论上[RFC](https://tools.ietf.org/html/rfc3986#page-23)中并没有要求限制重复的`key`。为了避免少数场景出现问题，建议还是定义成String。

> Android端的做法是正确的。参考NSURL、NSURLComponents也是如此。

```objc

@interface DoraemonMockBaseModel : NSObject
...
@property (nonatomic, copy) NSDictionary *query; 
...

```

**Comment by mizikoi53** [comment]
关于这个问题：
1.使用重复的key本身含有歧义，会造成意料之外的结果，不建议这么使用；
2.咨询了安卓同学，虽然他们使用了string，单最终会转换成map，重复的key也是无意义的；
所以这个问题暂不修复，多谢反馈
