### ISSUE TITLE
默认方式集成，编译速度太慢了

### ISSUE THREAD

**Issue by ljf1239848066** [didi/DoraemonKit#485]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。编译太耗时了, 建议优化一下编译性能问题，如下 gradle 比较耗时的 TASK:

> Task :app-testing:transformClassesWithDokitBigImageTransformForDebug
DokitBigImageTransform isIncremental = false, runVariant = DEBUG, emptyRun = false, inDuplcatedClassSafeMode = false
DokitBigImageTransform costed 1169ms

> Task :app-testing:mergeDebugJavaResource

> Task :app-testing:transformClassesWithDokitMethodStack0TransformForDebug
DokitMethodStack0Transform isIncremental = false, runVariant = DEBUG, emptyRun = false, inDuplcatedClassSafeMode = false
DokitMethodStack0Transform costed 949ms

> Task :app-testing:transformClassesWithDokitMethodStack1TransformForDebug
DokitMethodStack1Transform isIncremental = false, runVariant = DEBUG, emptyRun = false, inDuplcatedClassSafeMode = false
DokitMethodStack1Transform costed 1220ms

> Task :app-testing:transformClassesWithDokitMethodStack2TransformForDebug
DokitMethodStack2Transform isIncremental = false, runVariant = DEBUG, emptyRun = false, inDuplcatedClassSafeMode = false
DokitMethodStack2Transform costed 785ms

> Task :app-testing:transformClassesWithDokitMethodStack3TransformForDebug
DokitMethodStack3Transform isIncremental = false, runVariant = DEBUG, emptyRun = false, inDuplcatedClassSafeMode = false
DokitMethodStack3Transform costed 1262ms

> Task :app-testing:transformClassesWithDokitMethodStack4TransformForDebug
DokitMethodStack4Transform isIncremental = false, runVariant = DEBUG, emptyRun = false, inDuplcatedClassSafeMode = false
DokitMethodStack4Transform costed 1300ms

> Task :app-testing:transformClassesWithDokitSlowMethodTransformForDebug
DokitSlowMethodTransform isIncremental = false, runVariant = DEBUG, emptyRun = false, inDuplcatedClassSafeMode = false
DokitSlowMethodTransform costed 845ms

> 问题重现的步骤。切换 debug 与 release 编译方式后会重新编译，性能较差，相同编译方式重新编译还好。

> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）Android 端，Windows 10 
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）
> 最好给我们提供可以复现问题的Demo

**Comment by jtsky** [comment]
> Please complete the following informations.
> 
> > Expected behavior and actual behavior.
> > Steps to reproduce the problem.
> > Android or iOS? OS version? Brand?
> > More informations such as error messages and stack traces are welcomed.
> 
> 请补充如下信息。
> 
> > 期望的表现和实际的表现。编译太耗时了, 建议优化一下编译性能问题，如下 gradle 比较耗时的 TASK:
> 
> > Task :app-testing:transformClassesWithDokitBigImageTransformForDebug
> > DokitBigImageTransform isIncremental = false, runVariant = DEBUG, emptyRun = false, inDuplcatedClassSafeMode = false
> > DokitBigImageTransform costed 1169ms
> 
> > Task :app-testing:mergeDebugJavaResource
> 
> > Task :app-testing:transformClassesWithDokitMethodStack0TransformForDebug
> > DokitMethodStack0Transform isIncremental = false, runVariant = DEBUG, emptyRun = false, inDuplcatedClassSafeMode = false
> > DokitMethodStack0Transform costed 949ms
> 
> > Task :app-testing:transformClassesWithDokitMethodStack1TransformForDebug
> > DokitMethodStack1Transform isIncremental = false, runVariant = DEBUG, emptyRun = false, inDuplcatedClassSafeMode = false
> > DokitMethodStack1Transform costed 1220ms
> 
> > Task :app-testing:transformClassesWithDokitMethodStack2TransformForDebug
> > DokitMethodStack2Transform isIncremental = false, runVariant = DEBUG, emptyRun = false, inDuplcatedClassSafeMode = false
> > DokitMethodStack2Transform costed 785ms
> 
> > Task :app-testing:transformClassesWithDokitMethodStack3TransformForDebug
> > DokitMethodStack3Transform isIncremental = false, runVariant = DEBUG, emptyRun = false, inDuplcatedClassSafeMode = false
> > DokitMethodStack3Transform costed 1262ms
> 
> > Task :app-testing:transformClassesWithDokitMethodStack4TransformForDebug
> > DokitMethodStack4Transform isIncremental = false, runVariant = DEBUG, emptyRun = false, inDuplcatedClassSafeMode = false
> > DokitMethodStack4Transform costed 1300ms
> 
> > Task :app-testing:transformClassesWithDokitSlowMethodTransformForDebug
> > DokitSlowMethodTransform isIncremental = false, runVariant = DEBUG, emptyRun = false, inDuplcatedClassSafeMode = false
> > DokitSlowMethodTransform costed 845ms
> 
> > 问题重现的步骤。切换 debug 与 release 编译方式后会重新编译，性能较差，相同编译方式重新编译还好。
> 
> > Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）Android 端，Windows 10
> > 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）
> > 最好给我们提供可以复现问题的Demo
恩 由于插件在编译期会进行字节码插装  所以如果你的项目比较大  遍历所有的字节码就会比较慢  你可以参考Android接入文档 将某些不需要每次都用到的插件功能关闭  我也会考虑在下个版本是否将某些耗时transform默认状态改为false 感谢你的反馈
