### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by KElli0t** [didi/DoraemonKit#487]
Android 3.1.5版本 报ArrayIndexOutOfBoundsException ，把doraemonkit去掉就好了，确定为doraemonkit的问题

**Comment by KElli0t** [comment]
编译时期

**Comment by jtsky** [comment]
> gradle编译时报的

dokit 新版本已发布 请参考以下文档升级:http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide
注意:
插件配置模块的配置和以前有所区别，请重点关注下。

假如新的版本已经解决你的问题，可以选择自己关闭此issues或者回复此条信息由我来关闭。
