### ISSUE TITLE
Android应用gradle插件后，Fresco（Ver.2.1.0）图片会闪烁

### ISSUE THREAD

**Issue by hellojuly** [didi/DoraemonKit#489]
Android应用gradle插件apply plugin: 'com.didi.dokit'后，
app 中Fresco（Ver.2.1.0）图片每次加载都会闪烁

**Comment by jtsky** [comment]
> Android应用gradle插件apply plugin: 'com.didi.dokit'后，
> app 中Fresco（Ver.2.1.0）图片每次加载都会闪烁

是在列表中吗？如果对功能有影响的话，可以考虑将大图的插件开关关闭。参考:http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide 插件配置选项中关闭大图开关

**Comment by hellojuly** [comment]
是的，关闭大图功能设置为false可以解决了。Fresco对中调用setImageUri方法图片就会重新加载，导致闪烁，无论是否在列表。
