### ISSUE TITLE
Dokit 3.0.6版本问题反馈

### ISSUE THREAD

**Issue by qcgithub** [didi/DoraemonKit#491]
1.Android10系统不展示内存泄露，导致无法监测，crash，网络，模拟弱网不显示开关按钮，导致开关无法打开
2.Weex 专项工具中的缓存功能，信息功能，devTool功能crash无法使用

**Comment by jtsky** [comment]
> 1.Android10系统不展示内存泄露，导致无法监测，crash，网络，模拟弱网不显示开关按钮，导致开关无法打开
> 2.Weex 专项工具中的缓存功能，信息功能，devTool功能crash无法使用

1、Android 10 是哪个厂商的系统？ 
2、你那边的weex版本是多少？

**Comment by qcgithub** [comment]
1.Android 10华为和小米都试了，都不展示。
2.weex版本3.0.5，因为3.0.6版本无法监测内存泄露，我们只能用3.0.5版本




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "金台"<notifications@github.com&gt;; 
发送时间: 2020年5月26日(星期二) 下午5:13
收件人: "didi/DoraemonKit"<DoraemonKit@noreply.github.com&gt;; 
抄送: "诸子百家"<1666086427@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [didi/DoraemonKit] Dokit 3.0.6版本问题反馈 (#491)





  
1.Android10系统不展示内存泄露，导致无法监测，crash，网络，模拟弱网不显示开关按钮，导致开关无法打开
 2.Weex 专项工具中的缓存功能，信息功能，devTool功能crash无法使用
  
1、Android 10 是哪个厂商的系统？
 2、你那边的weex版本是多少？

**Comment by qcgithub** [comment]
3.0.6版本插件配置无法引入一直报错，导致网络，模拟弱网功能无法使用






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "金台"<notifications@github.com&gt;; 
发送时间: 2020年5月26日(星期二) 下午5:13
收件人: "didi/DoraemonKit"<DoraemonKit@noreply.github.com&gt;; 
抄送: "诸子百家"<1666086427@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [didi/DoraemonKit] Dokit 3.0.6版本问题反馈 (#491)





  
1.Android10系统不展示内存泄露，导致无法监测，crash，网络，模拟弱网不显示开关按钮，导致开关无法打开
 2.Weex 专项工具中的缓存功能，信息功能，devTool功能crash无法使用
  
1、Android 10 是哪个厂商的系统？
 2、你那边的weex版本是多少？

**Comment by jtsky** [comment]
> 3.0.6版本插件配置无法引入一直报错，导致网络，模拟弱网功能无法使用
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "金台"<notifications@github.com&gt;; 发送时间: 2020年5月26日(星期二) 下午5:13 收件人: "didi/DoraemonKit"<DoraemonKit@noreply.github.com&gt;; 抄送: "诸子百家"<1666086427@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [didi/DoraemonKit] Dokit 3.0.6版本问题反馈 (#491) 1.Android10系统不展示内存泄露，导致无法监测，crash，网络，模拟弱网不显示开关按钮，导致开关无法打开 2.Weex 专项工具中的缓存功能，信息功能，devTool功能crash无法使用 1、Android 10 是哪个厂商的系统？ 2、你那边的weex版本是多少？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

有具体的编译报错信息吗  现在support版本由于人手问题 无法及时进行问题修复

**Comment by qcgithub** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"金台"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月29日(星期五) 下午5:31
收件人:&nbsp;"didi/DoraemonKit"<DoraemonKit@noreply.github.com&gt;;
抄送:&nbsp;"诸子百家"<1666086427@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [didi/DoraemonKit] Dokit 3.0.6版本问题反馈 (#491)





  
3.0.6版本插件配置无法引入一直报错，导致网络，模拟弱网功能无法使用
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "金台"<notifications@github.com&gt;; 发送时间: 2020年5月26日(星期二) 下午5:13 收件人: "didi/DoraemonKit"<DoraemonKit@noreply.github.com&gt;; 抄送: "诸子百家"<1666086427@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [didi/DoraemonKit] Dokit 3.0.6版本问题反馈 (#491) 1.Android10系统不展示内存泄露，导致无法监测，crash，网络，模拟弱网不显示开关按钮，导致开关无法打开 2.Weex 专项工具中的缓存功能，信息功能，devTool功能crash无法使用 1、Android 10 是哪个厂商的系统？ 2、你那边的weex版本是多少？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
有具体的编译报错信息吗  现在support版本由于人手问题 无法及时进行问题修复

**Comment by jtsky** [comment]
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"金台"<notifications@github.com&gt;; 发送时间:&nbsp;2020年5月29日(星期五) 下午5:31 收件人:&nbsp;"didi/DoraemonKit"<DoraemonKit@noreply.github.com&gt;; 抄送:&nbsp;"诸子百家"<1666086427@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [didi/DoraemonKit] Dokit 3.0.6版本问题反馈 (#491) 3.0.6版本插件配置无法引入一直报错，导致网络，模拟弱网功能无法使用 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "金台"<notifications@github.com&gt;; 发送时间: 2020年5月26日(星期二) 下午5:13 收件人: "didi/DoraemonKit"<DoraemonKit@noreply.github.com&gt;; 抄送: "诸子百家"<1666086427@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [didi/DoraemonKit] Dokit 3.0.6版本问题反馈 (#491) 1.Android10系统不展示内存泄露，导致无法监测，crash，网络，模拟弱网不显示开关按钮，导致开关无法打开 2.Weex 专项工具中的缓存功能，信息功能，devTool功能crash无法使用 1、Android 10 是哪个厂商的系统？ 2、你那边的weex版本是多少？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 有具体的编译报错信息吗 现在support版本由于人手问题 无法及时进行问题修复 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

dokit 新版本已发布 请参考以下文档升级:http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide
注意:
插件配置模块的配置和以前有所区别，请重点关注下。

假如新的版本已经解决你的问题，可以选择自己关闭此issues或者回复此条信息由我来关闭。

**Comment by qcgithub** [comment]
你好！
非常感谢你们的配合，现在集成3.0.7.1版本，之前提到的问题都已经解决，但Weex专项工具里面的三个功能会crash，下面是crash日志的截图，辛苦看一下。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"金台"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月4日(星期四) 上午10:09
收件人:&nbsp;"didi/DoraemonKit"<DoraemonKit@noreply.github.com&gt;;
抄送:&nbsp;"诸子百家"<1666086427@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [didi/DoraemonKit] Dokit 3.0.6版本问题反馈 (#491)





  
------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"金台"<notifications@github.com&gt;; 发送时间:&nbsp;2020年5月29日(星期五) 下午5:31 收件人:&nbsp;"didi/DoraemonKit"<DoraemonKit@noreply.github.com&gt;; 抄送:&nbsp;"诸子百家"<1666086427@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [didi/DoraemonKit] Dokit 3.0.6版本问题反馈 (#491) 3.0.6版本插件配置无法引入一直报错，导致网络，模拟弱网功能无法使用 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "金台"<notifications@github.com&gt;; 发送时间: 2020年5月26日(星期二) 下午5:13 收件人: "didi/DoraemonKit"<DoraemonKit@noreply.github.com&gt;; 抄送: "诸子百家"<1666086427@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [didi/DoraemonKit] Dokit 3.0.6版本问题反馈 (#491) 1.Android10系统不展示内存泄露，导致无法监测，crash，网络，模拟弱网不显示开关按钮，导致开关无法打开 2.Weex 专项工具中的缓存功能，信息功能，devTool功能crash无法使用 1、Android 10 是哪个厂商的系统？ 2、你那边的weex版本是多少？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 有具体的编译报错信息吗 现在support版本由于人手问题 无法及时进行问题修复 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
dokit 新版本已发布 请参考以下文档升级:http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide
 注意:
 插件配置模块的配置和以前有所区别，请重点关注下。
 
假如新的版本已经解决你的问题，可以选择自己关闭此issues或者回复此条信息由我来关闭。

**Comment by qcgithub** [comment]
你好！
如果不引入doraemonkit-weex插件，页面展示空白。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"金台"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月4日(星期四) 上午10:09
收件人:&nbsp;"didi/DoraemonKit"<DoraemonKit@noreply.github.com&gt;;
抄送:&nbsp;"诸子百家"<1666086427@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [didi/DoraemonKit] Dokit 3.0.6版本问题反馈 (#491)





  
------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"金台"<notifications@github.com&gt;; 发送时间:&nbsp;2020年5月29日(星期五) 下午5:31 收件人:&nbsp;"didi/DoraemonKit"<DoraemonKit@noreply.github.com&gt;; 抄送:&nbsp;"诸子百家"<1666086427@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [didi/DoraemonKit] Dokit 3.0.6版本问题反馈 (#491) 3.0.6版本插件配置无法引入一直报错，导致网络，模拟弱网功能无法使用 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "金台"<notifications@github.com&gt;; 发送时间: 2020年5月26日(星期二) 下午5:13 收件人: "didi/DoraemonKit"<DoraemonKit@noreply.github.com&gt;; 抄送: "诸子百家"<1666086427@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [didi/DoraemonKit] Dokit 3.0.6版本问题反馈 (#491) 1.Android10系统不展示内存泄露，导致无法监测，crash，网络，模拟弱网不显示开关按钮，导致开关无法打开 2.Weex 专项工具中的缓存功能，信息功能，devTool功能crash无法使用 1、Android 10 是哪个厂商的系统？ 2、你那边的weex版本是多少？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 有具体的编译报错信息吗 现在support版本由于人手问题 无法及时进行问题修复 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
dokit 新版本已发布 请参考以下文档升级:http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide
 注意:
 插件配置模块的配置和以前有所区别，请重点关注下。
 
假如新的版本已经解决你的问题，可以选择自己关闭此issues或者回复此条信息由我来关闭。

**Comment by qcgithub** [comment]
你好！
现在release包不显示dokit的入口，这个你们能支持一下吗？无论debug包还是release包都能显示dokit的入口。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"金台"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月4日(星期四) 上午10:09
收件人:&nbsp;"didi/DoraemonKit"<DoraemonKit@noreply.github.com&gt;;
抄送:&nbsp;"诸子百家"<1666086427@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [didi/DoraemonKit] Dokit 3.0.6版本问题反馈 (#491)





  
------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"金台"<notifications@github.com&gt;; 发送时间:&nbsp;2020年5月29日(星期五) 下午5:31 收件人:&nbsp;"didi/DoraemonKit"<DoraemonKit@noreply.github.com&gt;; 抄送:&nbsp;"诸子百家"<1666086427@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [didi/DoraemonKit] Dokit 3.0.6版本问题反馈 (#491) 3.0.6版本插件配置无法引入一直报错，导致网络，模拟弱网功能无法使用 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "金台"<notifications@github.com&gt;; 发送时间: 2020年5月26日(星期二) 下午5:13 收件人: "didi/DoraemonKit"<DoraemonKit@noreply.github.com&gt;; 抄送: "诸子百家"<1666086427@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [didi/DoraemonKit] Dokit 3.0.6版本问题反馈 (#491) 1.Android10系统不展示内存泄露，导致无法监测，crash，网络，模拟弱网不显示开关按钮，导致开关无法打开 2.Weex 专项工具中的缓存功能，信息功能，devTool功能crash无法使用 1、Android 10 是哪个厂商的系统？ 2、你那边的weex版本是多少？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 有具体的编译报错信息吗 现在support版本由于人手问题 无法及时进行问题修复 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
dokit 新版本已发布 请参考以下文档升级:http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide
 注意:
 插件配置模块的配置和以前有所区别，请重点关注下。
 
假如新的版本已经解决你的问题，可以选择自己关闭此issues或者回复此条信息由我来关闭。

**Comment by jtsky** [comment]
> 你好！ 现在release包不显示dokit的入口，这个你们能支持一下吗？无论debug包还是release包都能显示dokit的入口。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"金台"<notifications@github.com&gt;; 发送时间:&nbsp;2020年6月4日(星期四) 上午10:09 收件人:&nbsp;"didi/DoraemonKit"<DoraemonKit@noreply.github.com&gt;; 抄送:&nbsp;"诸子百家"<1666086427@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [didi/DoraemonKit] Dokit 3.0.6版本问题反馈 (#491)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"金台"<notifications@github.com&gt;; 发送时间:&nbsp;2020年5月29日(星期五) 下午5:31 收件人:&nbsp;"didi/DoraemonKit"<DoraemonKit@noreply.github.com&gt;; 抄送:&nbsp;"诸子百家"<1666086427@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [didi/DoraemonKit] Dokit 3.0.6版本问题反馈 (#491) 3.0.6版本插件配置无法引入一直报错，导致网络，模拟弱网功能无法使用 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "金台"<notifications@github.com&gt;; 发送时间: 2020年5月26日(星期二) 下午5:13 收件人: "didi/DoraemonKit"<DoraemonKit@noreply.github.com&gt;; 抄送: "诸子百家"<1666086427@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [didi/DoraemonKit] Dokit 3.0.6版本问题反馈 (#491) 1.Android10系统不展示内存泄露，导致无法监测，crash，网络，模拟弱网不显示开关按钮，导致开关无法打开 2.Weex 专项工具中的缓存功能，信息功能，devTool功能crash无法使用 1、Android 10 是哪个厂商的系统？ 2、你那边的weex版本是多少？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 有具体的编译报错信息吗 现在support版本由于人手问题 无法及时进行问题修复 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. dokit 新版本已发布 请参考以下文档升级:http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide 注意: 插件配置模块的配置和以前有所区别，请重点关注下。 假如新的版本已经解决你的问题，可以选择自己关闭此issues或者回复此条信息由我来关闭。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

dokit不支持在release环境上使用，因为我们的功能没有在release环境下经过验证
