### ISSUE TITLE
iOS 打release包问题

### ISSUE THREAD

**Issue by huainanzi** [didi/DoraemonKit#492]
我在项目使用DoraemonKit的自定义模块，我打release包时候。会因为找不到继承DoraemonKit中的类，而报错。请问该如何解决

**Comment by yixiangboy** [comment]
所有的代码用Debug宏包围
#ifdef DEBUG
...yourcode...
#endif

**Comment by huainanzi** [comment]
> 所有的代码用Debug宏包围
> #ifdef DEBUG
> ...yourcode...
> #endif

thank you
