### ISSUE TITLE
招募DoKit纯Swift版本共建者，赢纪念T恤

### ISSUE THREAD

**Issue by yixiangboy** [didi/DoraemonKit#493]
* DoKit纯Kotlin版本的招募活动也即将推出，敬请期待

各位社区的朋友您们好：

Swift作为一种更加现代化、更加先进的语言，目前被越来越多的iOS开发者所接受。DoKit作为滴滴普惠出行事业部终端业务团队开发中沉淀出来的开源项目，从开始一直都是用OC进行编写，虽然目前内部业务开发依然主流是OC，但是收到多个社区同学的反馈，顺应业界发展趋势，准备提供纯Swift版本的DoKit。作者最近也抽空重新学习了一下最新版本的swift，准备打造一个纯Swift语言版本的DoKit，但是毕竟作者精力有限，在此希望开源社区的热心开发者可以跟作者一起共建，推出纯Swift版本的Dokit。

所以我们准备推出以下活动：

* 活动规则：先找作者（加入DoKit qq群，@didi_iOS_易翔）认领DoKit OC版本的一个或者多个功能，改写成Swift版本，通过PR的形式提交给我们，我们通过之后，即可获取我们的纪念T恤

* 活动时间：2020-05-27~2020-2020-06-30

* 活动奖品：DoKit纪念T恤一件；个人github账号加入到DoKit首页的贡献者榜单；对外PR稿透出贡献者github账号。

* 任务认领一览

|  功能   | 认领者  |
|  ----  | ----  |
| 应用设置  | [yixiangboy](https://github.com/yixiangboy) （已完成） |
| App信息  | [rakeyang](https://github.com/rakeyang) |
| 沙盒浏览器  | [Haisens](https://github.com/Haisens) |
| 位置模拟| [klone1127](https://github.com/klone1127) |
| H5任意门 | [DeveloperLY](https://github.com/DeveloperLY) |
| 清理缓存 | [yixiangboy](https://github.com/yixiangboy) （已完成） |
| 日志监控 | [Jadite](https://github.com/Jadite) |
| UserDefaults | [rakeyang](https://github.com/rakeyang) |
| 帧率| [hash0xd](https://github.com/hash0xd) |
| CPU |  [hash0xd](https://github.com/hash0xd) |
| 内存 |  [hash0xd](https://github.com/hash0xd) |
| 网络 | [klone1127](https://github.com/klone1127) |
| Crash | [fanglinwei](https://github.com/fanglinwei)|
| 子线程UI | [FengDeng](https://github.com/FengDeng) |
| 卡顿 | [wm219](https://github.com/wm219) |
| 大图检测 | [Channe](https://github.com/Channe) |
| 模拟弱网 | [Channe](https://github.com/Channe) |
| 启动耗时| [gangapp](github.com/gangapp) |
| UI层级| [jiaruh](https://github.com/jiaruh) |
| 函数耗时| [ShrinkLynn](https://github.com/ShrinkLynn) |
| Load耗时| [ShrinkLynn](https://github.com/ShrinkLynn) |
| 内存泄漏| [lijie121210](https://github.com/lijie121210) |
| 取色器| [fanglinwei](https://github.com/fanglinwei) |
| 组件检查 |[lixiang1994](https://github.com/lixiang1994) |
| 对齐标尺 |[lixiang1994](https://github.com/lixiang1994) |
| 布局边框 |[lixiang1994](https://github.com/lixiang1994) |
| UI结构 | [PublicJoker](https://github.com/PublicJoker) |
| Mock数据 | [timehzy](https://github.com/timehzy)|
|健康体检 | [AilsaYouCan](https://github.com/AilsaYouCan) |

当然了，也希望大家不要局限于我们现有的功能，非常欢迎大家提交Swift特有的新功能

* 代码提交规则

目前作者已经把DoKit的主体框架搭建起来了，并且完成了“应用设置”和“清理缓存”这两个功能作为演示。每一个开发者下载我们的代码，然后切换到swift分支，进入iOS/Swift/DoKitSwiftDemo目录，执行pod. install就可以看到DoKit目前的状态。具体细节问题，可以找作者进行沟通。

每次提交Pr的时候，先拉取我们最近的代码合并之后再提交，避免冲突问题

* “DoKit开源社区” 公众号，欢迎大家关注

<div align="center">    
 <img src="https://javer.oss-cn-shanghai.aliyuncs.com/2020/dokit/dokitwx.jpg" width = "200" height = "200" alt="QQ 交流群" align=left />
</div>

<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>

* “DoKit 用户交流QQ群”，欢迎大家加入

<div align="center">    
 <img src="https://javer.oss-cn-shanghai.aliyuncs.com/doraemon/github/DoraemonKitQQ.jpeg" width = "160" height = "200" alt="QQ 交流群" align=left />
</div>

<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>

* 获奖T恤款式如下：
![dokitTshirt](https://user-images.githubusercontent.com/13174496/77880261-d2749680-728e-11ea-876e-069423a9d761.png)

**Comment by wjacker** [comment]
请问这个swift的改版有任何进展吗 :-)

**Comment by lilongcnc** [comment]
这个Swift的构建还有结果吗？
