### ISSUE TITLE
Android dependency 'androidx.cardview:cardview' has different version for the compile (1.0.0-rc01) and runtime (1.0.0) classpath

### ISSUE THREAD

**Issue by hdhhdhd** [didi/DoraemonKit#509]
android  3.1.5版本 cardview依赖冲突 但app build.gradle中并没有依赖cardview

**Comment by jtsky** [comment]
> android 3.1.5版本 cardview依赖冲突 但app build.gradle中并没有依赖cardview

循环依赖了 你可以参考以下代码统一以下三方依赖:

configurations.all {
    //循环每个依赖库
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        //获取当前循环到的依赖库
        def requested = details.requested
        //如果这个依赖库群组的名字是com.android.support
        if (requested.group == 'com.squareup.okhttp3') {
            //且其名字不是以multidex开头的
            if (requested.name == "okhttp") {
                //这里指定需要统一的依赖版本 比如我的需要配置成27.1.1
                details.useVersion '3.14.7'
            }
        }
    }
}
