### ISSUE TITLE
希望能兼容一下gradle:4.0

### ISSUE THREAD

**Issue by zhaoxiuyu** [didi/DoraemonKit#513]
![JMT4PPK$WKI8R0)7QM(@`SM](https://user-images.githubusercontent.com/16554580/83232683-1f59e800-a1c0-11ea-8c38-40197dc3562e.png)

希望能兼容一下gradle:4.0

**Comment by jtsky** [comment]
> ![JMT4PPK$WKI8R0)7QM(@`SM](https://user-images.githubusercontent.com/16554580/83232683-1f59e800-a1c0-11ea-8c38-40197dc3562e.png)
> 
> 希望能兼容一下gradle:4.0

由于新版本插件内部依赖了滴滴的booster 所以在等待booster的适配

**Comment by SuperMarioBean** [comment]
可否了解下滴滴 gradle:4.0 的适配有大概的排期么，我这里也有相同的问题

**Comment by jhwsx** [comment]
同问

**Comment by jtsky** [comment]
当前v3.1.8版本已经支持AGP 4.0
