### ISSUE TITLE
项目依赖库

### ISSUE THREAD

**Issue by hidoudou** [didi/DoraemonKit#527]
请问这个项目是半开源吗？动态库的源码能提供吗？

**Comment by jtsky** [comment]
> 请问这个项目是半开源吗？动态库的源码能提供吗？

请注明是android还是ios。通过当前的描述不是很能理解你的意思

**Comment by hidoudou** [comment]
> > 请问这个项目是半开源吗？动态库的源码能提供吗？
> 
> 请注明是android还是ios。通过当前的描述不是很能理解你的意思

感谢回复。
我的意思我在项目工程中发现一些so文件和jar包，但是没有发现这些库的源码。所以想确认下该项目是否是开源部分源码。

**Comment by jtsky** [comment]
> > > 请问这个项目是半开源吗？动态库的源码能提供吗？
> > 
> > 
> > 请注明是android还是ios。通过当前的描述不是很能理解你的意思
> 
> 感谢回复。
> 我的意思我在项目工程中发现一些so文件和jar包，但是没有发现这些库的源码。所以想确认下该项目是否是开源部分源码。

项目中的jar报主要是第三方地图，是用过compileOnly的方式引入的
