### ISSUE TITLE
Build时报错：transform

### ISSUE THREAD

**Issue by shenbingkai** [didi/DoraemonKit#533]
系统：Android
doraemonkit:3.1.5

编译时报错，使用3.1.5(目前最新版)，使用了插件doraemonkit-plugin，不使用插件可以正常使用

<img width="1345" alt="屏幕快照 2020-06-02 下午7 06 20" src="https://user-images.githubusercontent.com/5211758/83513797-037a7d00-a505-11ea-89ee-4f36b682e99a.png">
<img width="1302" alt="屏幕快照 2020-06-02 下午7 05 27" src="https://user-images.githubusercontent.com/5211758/83513816-08d7c780-a505-11ea-97d1-722e7c78ff3f.png">

**Comment by jtsky** [comment]
> 系统：Android
> doraemonkit:3.1.5
> 
> 编译时报错，使用3.1.5(目前最新版)，使用了插件doraemonkit-plugin，不使用插件可以正常使用
> 
> <img alt="屏幕快照 2020-06-02 下午7 06 20" width="1345" src="https://user-images.githubusercontent.com/5211758/83513797-037a7d00-a505-11ea-89ee-4f36b682e99a.png">
> 
> <img alt="屏幕快照 2020-06-02 下午7 05 27" width="1302" src="https://user-images.githubusercontent.com/5211758/83513816-08d7c780-a505-11ea-97d1-722e7c78ff3f.png">

dokit 新版本已发布  请参考以下文档升级:http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide
**注意**:
插件配置模块的配置和以前有所区别，请重点关注下。

**Comment by jtsky** [comment]
> 系统：Android
> doraemonkit:3.1.5
> 
> 编译时报错，使用3.1.5(目前最新版)，使用了插件doraemonkit-plugin，不使用插件可以正常使用
> 
> <img alt="屏幕快照 2020-06-02 下午7 06 20" width="1345" src="https://user-images.githubusercontent.com/5211758/83513797-037a7d00-a505-11ea-89ee-4f36b682e99a.png">
> 
> <img alt="屏幕快照 2020-06-02 下午7 05 27" width="1302" src="https://user-images.githubusercontent.com/5211758/83513816-08d7c780-a505-11ea-97d1-722e7c78ff3f.png">

dokit 新版本已发布 请参考以下文档升级:http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide
注意:
插件配置模块的配置和以前有所区别，请重点关注下。

假如新的版本已经解决你的问题，可以选择自己关闭此issues或者回复此条信息由我来关闭。
