### ISSUE TITLE
是否可以提供实时检测，比如我一边操作app，一边看cpu的使用情况或者流量使用情况

### ISSUE THREAD

**Issue by nealkafuly** [didi/DoraemonKit#54]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

**Comment by yixiangboy** [comment]
是不是让CPU、帧率、内存、流量能够同时显示在屏幕上？

**Comment by nealkafuly** [comment]
是的，大牛

**Comment by nealkafuly** [comment]
我是小白，菜鸡，求哥哥帮助

**Comment by nealkafuly** [comment]
top指令，有时候比你这个更好玩，就是不用植入代码，直接写入包名后台运行就可以了，你这个方案有点low，说实话

**Comment by yixiangboy** [comment]
好的，接受批评，一步一步优化。现在刚开源不久，如果你有好的想法也可以提出来，一起完善。

**Comment by nealkafuly** [comment]
我是菜鸡，就是模块化，每一个模块实现的可以不一样，就好玩了，你们的颜色提取，我喜欢，我终于找到了，非常谢谢

**Comment by nealkafuly** [comment]
我其实没有认真看你们的代码是如何实现的，不吹牛了，我怕被打，谢谢哥哥

**Comment by yixiangboy** [comment]
android明天就会发一个新版本 就是基于top指令的。支持8.0以上

**Comment by nealkafuly** [comment]
！！！！

**Comment by nealkafuly** [comment]
你们为啥这么多热情，我最近都没性情了，情人节不过嘛

**Comment by yixiangboy** [comment]
哈哈哈 我们是热爱工作的程序猿

**Comment by weihuihuang** [comment]
帅哥@yixiangboy，关于这个问题说的流量显示，类似这种功能的可以修改下提交到你们项目么  https://github.com/weihuihuang/TrafficMonitor

**Comment by yixiangboy** [comment]
请更新到1.1.9 已经支持
