### ISSUE TITLE
DoraemonKit和glide同时使用时，很容易发生crash，异常信息：pthread_create (1040KB stack) failed: Try again

### ISSUE THREAD

**Issue by JackFung2015** [didi/DoraemonKit#544]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）
> 最好给我们提供可以复现问题的Demo

**Comment by JackFung2015** [comment]
场景：recyclerView中使用glide加载图文混排，在页面快速滑动时，经常会引起crash，异常信息：pthread_create (1040KB stack) failed: Try again，栈内存OOM了，打包release版本应用没有问题，debug版本必现，doraemonkit依赖版本：2.2.1。

**Comment by jtsky** [comment]
> 场景：recyclerView中使用glide加载图文混排，在页面快速滑动时，经常会引起crash，异常信息：pthread_create (1040KB stack) failed: Try again，栈内存OOM了，打包release版本应用没有问题，debug版本必现，doraemonkit依赖版本：2.2.1。

可以升级到最新版本试试 参考:http://xingyun.xiaojukeji.com/docs/dokit/#/androidGuide
