### ISSUE TITLE
iOS 如果能够复制抓取的流量数据就完美了

### ISSUE THREAD

**Issue by cclbj** [didi/DoraemonKit#55]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

**Comment by yixiangboy** [comment]
好的，我们下个版本会安排处理。

**Comment by yixiangboy** [comment]
1.1.5版本新增 右滑cell 新增复制功能
