### ISSUE TITLE
iOS 沙盒浏览太慢

### ISSUE THREAD

**Issue by azureplus** [didi/DoraemonKit#562]
iOS 沙盒浏览统计太慢，卡的要死，建议增加开关，可以关闭文件大小的统计

**Comment by yixiangboy** [comment]
> iOS 沙盒浏览统计太慢，卡的要死，建议增加开关，可以关闭文件大小的统计

感谢反馈，我们下个版本搞成异步统计

**Comment by azureplus** [comment]
> > iOS 沙盒浏览统计太慢，卡的要死，建议增加开关，可以关闭文件大小的统计
> 
> 感谢反馈，我们下个版本搞成异步统计

异步+快关 ？
