### ISSUE TITLE
发现使用 DoraemonKIt，会抢占控件的焦点

### ISSUE THREAD

**Issue by jhwsx** [didi/DoraemonKit#569]
> 期望的表现和实际的表现。

场景：在 debug 模式下使用 DoraemonKIt，一个页面里的`EditText` 去请求获取焦点并调起键盘，但是却获取不到。
而我把 DoraemonKIt 关掉之后，是可以获取到的。release 包也是可以获取到的。

> Android 还是 iOS？系统版本是多少？手机品牌是什么？

Android8.0 摩托罗拉 不过应该跟手机品牌无关。

**Comment by jtsky** [comment]
> > 期望的表现和实际的表现。
> 
> 场景：在 debug 模式下使用 DoraemonKIt，一个页面里的`EditText` 去请求获取焦点并调起键盘，但是却获取不到。
> 而我把 DoraemonKIt 关掉之后，是可以获取到的。release 包也是可以获取到的。
> 
> > Android 还是 iOS？系统版本是多少？手机品牌是什么？
> 
> Android8.0 摩托罗拉 不过应该跟手机品牌无关。

这个问题确实存在 dokit的控件会抢占页面上的焦点  如果需要唤起键盘等操作  是需要自己去点击的 但是不会影响线上代码

**Comment by jhwsx** [comment]
好的，谢谢。
