### ISSUE TITLE
DoraemonLoadAnalyze设计成动态库的原因

### ISSUE THREAD

**Issue by YiHuaXie** [didi/DoraemonKit#573]
在程序冷启动阶段，先进行dyld，用来装载Mach-O文件（可执行文件、动态库），DoraemonLoadAnalyze就被加进内存中，变完成了对load方法的hook。接着执行Runtime初始化，_objc_init -> _dyld_objc_notify_register -> load_images。load_images会调用所有类和分类的load方法，此时调用的load方法已经是被hook过的，所以可以实现对load方法的耗时计算。不知道是不是这样？

**Comment by yixiangboy** [comment]
是的

**Comment by YiHuaXie** [comment]
感谢
