### ISSUE TITLE
iOS13上install方法崩溃

### ISSUE THREAD

**Issue by TMMMMMS** [didi/DoraemonKit#579]
使用[[DoraemonManager shareInstance] install]初始化时，造成崩溃

![1592815452485](https://user-images.githubusercontent.com/18571410/85267339-b8baa800-b4a7-11ea-9cff-ad69983c0272.jpg)

<img width="836" alt="WX20200622-164936" src="https://user-images.githubusercontent.com/18571410/85267919-6a59d900-b4a8-11ea-9524-001084134ba3.png">

-[AppDelegate window]: unrecognized selector sent to instance 0x600003b08150

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AppDelegate window]: unrecognized selector sent to instance 0x600003b08150'

**Comment by yixiangboy** [comment]
请更新到最新版本

**Comment by TMMMMMS** [comment]
> 请更新到最新版本

已解决，谢谢
