### ISSUE TITLE
在 Xiaomi Redmi Note 8 Pro Android 9, API 28 无法退出 DoraemonKit

### ISSUE THREAD

**Issue by jhwsx** [didi/DoraemonKit#583]
请补充如下信息。
> 期望的表现和实际的表现。（如有）
希望点击退出按钮,退出组件
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
如题.

**Comment by jtsky** [comment]
无法退出doraemonkit是什么意思？有报错信息吗？

**Comment by jhwsx** [comment]
没有看到推出按钮

**Comment by jhwsx** [comment]
这是滑道底部的截图
![device-2020-06-24-112134](https://user-images.githubusercontent.com/19379538/85495344-eb31e580-b60c-11ea-8ccf-e0f4eaa6b611.png)

**Comment by jtsky** [comment]
> 这是滑到底部的截图
> ![device-2020-06-24-112134](https://user-images.githubusercontent.com/19379538/85495344-eb31e580-b60c-11ea-8ccf-e0f4eaa6b611.png)
> 我打算在 debug 模式下把 DoraemonKit 退出的,但是找不到退出按钮了.

可以升级到最新版本看看

**Comment by jhwsx** [comment]
好的

**Comment by jtsky** [comment]
> 好的

3.1.8版本有解决你的问题吗？

**Comment by jhwsx** [comment]
@jtsky 3.1.8 版本有解决了我的问题。非常谢谢。
