### ISSUE TITLE
iOS 添加带有UIWindow参数的初始化方法

### ISSUE THREAD

**Issue by jinaiyuanbaojie** [didi/DoraemonKit#59]
> 期望的表现和实际的表现。（如有）
能否添加一个带有window的初始化方法
> 问题重现的步骤。（如有）
我们的项目中AppDelegate没有window属性，初始化DoreamonKit后就会闪退。

Note：希望添加监控网络请求详情的功能

**Comment by nealkafuly** [comment]
锤子，没必要吧，你看jake大神的代码有注解的吗，没注解贼好看

**Comment by jinaiyuanbaojie** [comment]
> 锤子，没必要吧，你看jake大神的代码有注解的吗，没注解贼好看

????

**Comment by nealkafuly** [comment]
理解错了，你是要求增加方法实现

**Comment by nealkafuly** [comment]
这样可以自定义控制输出的地方，你很鸡贼

**Comment by yixiangboy** [comment]
网络监控详情的功能已经有了，流量监测里面 有一个“显示流量监测详情”的入口，您可以看一下

**Comment by yixiangboy** [comment]
iOS 添加带有UIWindow参数的初始化方法 这个是什么意思？

**Comment by jinaiyuanbaojie** [comment]
> iOS 添加带有UIWindow参数的初始化方法 这个是什么意思？

谢谢您的答复。
1.  [[DoraemonManager shareInstance] install];   这个初始化方法会触发
//不能让该View成为keyWindow，每一次它要成为keyWindow的时候，都要将appDelegate的window指为keyWindow
  | - (void)becomeKeyWindow{
  | UIWindow *appWindow = [[UIApplication sharedApplication].delegate window];
  | [appWindow makeKeyWindow];
  | }
 
但是我们的项目被某些二逼把 AppDelegate的window属性给删除了，调用上面的方法会导致 unrecgonized selector

2.  请问网络监控可以查看请求参数和返回的json么？ 
类似netfox这个开源项目的功能

**Comment by xiongwj0910** [comment]
1. [[UIApplication sharedApplication].delegate window]; 这种写法很蛋疼，为了一个window，必须依赖AppDelegate，并且Delegate还必须要有window这个属性。这样就限制死了使用者的delegate，这个设计可以修改一下，把window当成参数传入是个好建议

**Comment by yixiangboy** [comment]
好的 我们接下来会考虑进去
