### ISSUE TITLE
功能添加建议：网络监控详情中的响应体部分，加入一键复制响应体按钮

### ISSUE THREAD

**Issue by a714857512** [didi/DoraemonKit#593]
请补充如下信息。
> 期望的表现和实际的表现。
希望在网络监控详情中的响应体部分，加入一键复制响应体按钮，有的响应体很长很长，想复制完成很难。

**Comment by jtsky** [comment]
> 请补充如下信息。
> 
> > 期望的表现和实际的表现。
> > 希望在网络监控详情中的响应体部分，加入一键复制响应体按钮，有的响应体很长很长，想复制完成很难。

恩恩 这个可以考虑增加一个导出的功能

**Comment by jtsky** [comment]
> 请补充如下信息。
> 
> > 期望的表现和实际的表现。
> > 希望在网络监控详情中的响应体部分，加入一键复制响应体按钮，有的响应体很长很长，想复制完成很难。

你好 我看了一下代码 我们针对response其实做了长按复制功能的

**Comment by feiyang1235** [comment]
@jtsky 你好，这个网络流量监测内部原理是怎么样的呢？ 我集成进入我们项目后，很多请求的接口好像并没有拦截到请求信息

**Comment by jtsky** [comment]
> @jtsky 你好，这个网络流量监测内部原理是怎么样的呢？ 我集成进入我们项目后，很多请求的接口好像并没有拦截到请求信息

我们会拦截okhttp和urlconnection的网络请求 并记录在本地
