### ISSUE TITLE
libDoraemonKit.a

### ISSUE THREAD

**Issue by S209** [didi/DoraemonKit#6]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_CNContactStore", referenced from:
      objc-class-ref in libDoraemonKit.a(DoraemonAppInfoUtil.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

 我 pod 'DoraemonKit/Core', '~> 1.0.2' 版本

**Comment by yixiangboy** [comment]
加上 添加上Contacts.framework 试试。我这边不存在这个问题。

**Comment by yixiangboy** [comment]
加上 添加上Contacts.framework 试试。
