### ISSUE TITLE
Android dokit 不支持多渠道编译打包

### ISSUE THREAD

**Issue by jimoshusheng** [didi/DoraemonKit#608]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 希望能够支持多渠道编译，现在只是支持release & debug，而且是release的话是默认不进行AOP注入的，但是如果这个时候，我有其他的渠道包比如preprod(预发布)也是希望没有AOP注入的，这个时候，并不支持，默认就会进行注入，导致编译失败
> 问题重现的步骤。渠道包preprod ,preprodImplementation "com.didichuxing.doraemonkit:doraemonkit-no-op:3.0.2" ,编译失败。
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）
> 最好给我们提供可以复现问题的Demo

**Comment by jtsky** [comment]
dokit 只支持在开发阶段使用 所以我的理解假如到了多渠道打包阶段的时候应该不需要使用dokit了

**Comment by jimoshusheng** [comment]
> dokit 只支持在开发阶段使用 所以我的理解假如到了多渠道打包阶段的时候应该不需要使用dokit了

因为dokit在release下是会跳过AOP注入的，默认其他渠道包都是会AOP注入的，这个就会导致编译失败，如何关闭AOP注入？那个dokitPluginSwitch 开关？

**Comment by jtsky** [comment]
> > dokit 只支持在开发阶段使用 所以我的理解假如到了多渠道打包阶段的时候应该不需要使用dokit了
> 
> 因为dokit在release下是会跳过AOP注入的，默认其他渠道包都是会AOP注入的，这个就会导致编译失败，如何关闭AOP注入？那个dokitPluginSwitch 开关？

嗯 你可以关闭试试
