### ISSUE TITLE
iOS 未适配iPhone X以上机型

### ISSUE THREAD

**Issue by Kingson** [didi/DoraemonKit#61]
打开NSLog后，NSLog的显示位置在iPhone X以上机型中被遮挡，具体现象请查看附件
![screen shot 2019-02-14 at 4 42 37 pm](https://user-images.githubusercontent.com/468509/52774146-94f77e80-3077-11e9-9808-c86cbc77b193.png)

**Comment by yixiangboy** [comment]
1.1.5版本已经修复
