### ISSUE TITLE
iOS上如何在初始化默认开启某个功能

### ISSUE THREAD

**Issue by freesan44** [didi/DoraemonKit#616]
例如我想在启动的时候默认开启【Crash日志收集开关】或【NSLog】功能

**Comment by FengDeng** [comment]
`DoraemonCacheManager.sharedInstance()?.saveCrashSwitch(true)
  DoraemonCacheManager.sharedInstance()?.saveNSLogSwitch(true)`

**Comment by dustylove** [comment]
#import <DoraemonKit/DoraemonCacheManager.h>
[[DoraemonCacheManager sharedInstance] saveCrashSwitch:YES];
[[DoraemonCacheManager sharedInstance] saveNSLogSwitch:YES];
或者手动在常用工具打开开关再重启app

**Comment by freesan44** [comment]
好的，谢谢
