### ISSUE TITLE
MOCK有PathVariable参数无法匹配

### ISSUE THREAD

**Issue by UbunGit** [didi/DoraemonKit#617]
iOS
当api中的path中包含PathVariable参数的时候，无法匹配：如/api/{userid}
所以建议在DoraemonMockManager.m文件中189行代码加入正则匹配判断
     
    //匹配path
    if (([path hasSuffix:api.path]) && api.selected) {
     
替换为
     
    NSPredicate *pred = [NSPredicate predicateWithFormat:@"SELF MATCHES %@", api.path];
    //匹配path
    if (([path hasSuffix:api.path]||[pred evaluateWithObject:path]) && api.selected) {

**Comment by jtsky** [comment]
> iOS
> 当api中的path中包含PathVariable参数的时候，无法匹配：如/api/{userid}
> 所以建议在DoraemonMockManager.m文件中189行代码加入正则匹配判断
>      
>     //匹配path
>     if (([path hasSuffix:api.path]) && api.selected) {
>      
> 替换为
>      
>     NSPredicate *pred = [NSPredicate predicateWithFormat:@"SELF MATCHES %@", api.path];
>     //匹配path
>     if (([path hasSuffix:api.path]||[pred evaluateWithObject:path]) && api.selected) {
>      
> 
> 

方便的话 可以给我们提PR哦 我们这边经过review 如果通过的话 会将你的PR合并进master

**Comment by Haisens** [comment]
您的建议我们已经记录，感谢
