### ISSUE TITLE
iOS11以下版本点击沙盒浏览功能崩溃

### ISSUE THREAD

**Issue by jiaxiaoru** [didi/DoraemonKit#62]
崩溃信息：
 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UITableView setContentInsetAdjustmentBehavior:]: unrecognized selector sent to instance 0x7f883e922e00'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010c16ee65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000110ec0deb objc_exception_throw + 48
	2   CoreFoundation                      0x000000010c17748d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x000000010c0c490a ___forwarding___ + 970
	4   CoreFoundation                      0x000000010c0c44b8 _CF_forwarding_prep_0 + 120
	5   Finance                             0x00000001091e829b -[DoraemonSandboxViewController initUI] + 619
	6   Finance                             0x00000001091e7ebe -[DoraemonSandboxViewController viewDidLoad] + 94
	7   UIKit                               0x000000010e0a4f98 -[UIViewController loadViewIfRequired] + 1198
	8   UIKit                               0x000000010e0e9651 -[UINavigationController _layoutViewController:] + 54
	9   UIKit                               0x000000010e0e9f26 -[UINavigationController _updateScrollViewFromViewController:toViewController:] + 462
	10  UIKit                               0x000000010e0ea098 -[UINavigationController _startTransition:fromViewController:toViewController:] + 126
	11  UIKit                               0x000000010e0eb2f1 -[UINavigationController _startDeferredTransitionIfNeeded:] + 890
	12  UIKit                               0x000000010e0ec3af -[UINavigationController __viewWillLayoutSubviews] + 57
	13  UIKit                               0x000000010e292ff7 -[UILayoutContainerView layoutSubviews] + 248
	14  UIKit                               0x000000010dfc54a3 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 703
	15  QuartzCore                          0x000000010dc8f59a -[CALayer layoutSublayers] + 146
	16  QuartzCore                          0x000000010dc83e70 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 366
	17  QuartzCore                          0x000000010dc83cee _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
	18  QuartzCore                          0x000000010dc78475 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 277
	19  QuartzCore                          0x000000010dca5c0a _ZN2CA11Transaction6commitEv + 486
	20  UIKit                               0x000000010df08f7c _UIApplicationHandleEventQueue + 7329
	21  CoreFoundation                      0x000000010c09aa31 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	22  CoreFoundation                      0x000000010c09095c __CFRunLoopDoSources0 + 556
	23  CoreFoundation                      0x000000010c08fe13 __CFRunLoopRun + 867
	24  CoreFoundation                      0x000000010c08f828 CFRunLoopRunSpecific + 488
	25  GraphicsServices                    0x000000011287fad2 GSEventRunModal + 161
	26  UIKit                               0x000000010df0e610 UIApplicationMain + 171
	27  Finance                             0x0000000108b56220 main + 112
	28  libdyld.dylib                       0x0000000111c7092d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

这边看了下，导致这个崩溃的原因是DoraemonSandboxViewController.m文件的第51行
- (void)initUI 函数里的
self.tableView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentAutomatic;
这行代码崩溃了，contentInsetAdjustmentBehavior这个属性只有大于等于iOS11版本才有，所以iOS11版本以下会崩溃，请帮忙做下兼容，谢谢哈~

**Comment by yixiangboy** [comment]
1.1.5版本已修复
