### ISSUE TITLE
DoraemonKit导致项目中窗口属性的改变

### ISSUE THREAD

**Issue by wang-neng** [didi/DoraemonKit#624]
引入DoraemonKit后，项目中原有的一些窗口属性被改变，比如窗口新增了任意缩放大小的属性

**Comment by jtsky** [comment]
> 引入DoraemonKit后，项目中原有的一些窗口属性被改变，比如窗口新增了任意缩放大小的属性

android or ios?能详细描述一下情况吗

**Comment by wgng** [comment]
Android 。项目中的窗口是不允许缩放的，引入Doraemonkit后，应用启动之后，窗口自动缩小，且窗口的左下角能随意拖动，缩小和放大窗口

**Comment by jtsky** [comment]
> Android 。项目中的窗口是不允许缩放的，引入Doraemonkit后，应用启动之后，窗口自动缩小，且窗口的左下角能随意拖动，缩小和放大窗口

因为默认模式下 我们是在窗口的根布局中插入view来实现的，如果对你们的布局有影响，可以试试系统悬浮窗模式。
