### ISSUE TITLE
建议增加nslog日志存储到沙盒功能

### ISSUE THREAD

**Issue by xuXiaoDan** [didi/DoraemonKit#625]
将nslog日志存储到沙盒，下次啊启动还能看到日志

**Comment by jtsky** [comment]
> 将nslog日志存储到沙盒，下次啊启动还能看到日志

我们的log支持导出功能 你可以试下

**Comment by xuXiaoDan** [comment]
导出功能我知道，但是我想保留上次启动的nalog，每次都导出查看不太方便
