### ISSUE TITLE
希望增加webview加载路径的查看

### ISSUE THREAD

**Issue by applebest** [didi/DoraemonKit#629]
现在很多APP都嵌套了webview加载H5的页面，节省了原生的开发周期，但也增加了许多的调试成本。
希望在APP开发调试中能增加当前webView正在加载的路径，在H5内点击的按钮又进行了二次加载的链接也可以抓取到，现在开发中都是在调试台查看，输命令打印，十分不方便，望增加此功能

**Comment by Haisens** [comment]
建议已经记录

**Comment by applebest** [comment]
> 建议已经记录

大佬👍
