### ISSUE TITLE
升级AFNetworking

### ISSUE THREAD

**Issue by UKenn** [didi/DoraemonKit#630]
AFNetworking4.0版本未兼容低版本，下图post方法已删除，意见DoraemonKit升级AFNetworking

![img_1596002925559](https://user-images.githubusercontent.com/13403891/88763117-29d73480-d1a5-11ea-867b-ab4259bd4332.png)

**Comment by mizikoi53** [comment]
问题已记录

**Comment by Haisens** [comment]
已升级
