### ISSUE TITLE
Type com.google.gson.FieldNamingPolicy is defined multiple times

### ISSUE THREAD

**Issue by liuleshuai** [didi/DoraemonKit#637]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）
> 最好给我们提供可以复现问题的Demo

1.Android10系统，华为P30
gradle版本4.0.1
2.编译没问题，运行报错。
3.只集成了
debugApi 'com.didichuxing.doraemonkit:doraemonkit:3.2.0'
releaseApi 'com.didichuxing.doraemonkit:doraemonkit-no-op:3.2.0'
debugApi 'com.didichuxing.doraemonkit:doraemonkit-weex:3.2.0'
4.日志信息如下：
![image](https://user-images.githubusercontent.com/31751668/89643846-3d8f4300-d8e9-11ea-92ff-e841f214bbf2.png)

**Comment by liuleshuai** [comment]
将demo下载下来是能正常运行的，但是gradle版本升到4.0.1编译期也会报错
日志如下：
![image](https://user-images.githubusercontent.com/31751668/89645300-125a2300-d8ec-11ea-9992-68441fb6d331.png)

**Comment by jtsky** [comment]
> 将demo下载下来是能正常运行的，但是gradle版本升到4.0.1编译期也会报错
> 日志如下：
> ![image](https://user-images.githubusercontent.com/31751668/89645300-125a2300-d8ec-11ea-9992-68441fb6d331.png)

如果你修改了demo项目里的gradl版本，还需要把buildSrc目录下的build.gradle的gradle版本也统一一下，否则会报错

**Comment by liuleshuai** [comment]
demo：把buildSrc目录下的build.gradle的gradle版本统一升级到4.0.1，报如下错误：
![image](https://user-images.githubusercontent.com/31751668/89748667-e19a0980-daf6-11ea-9bee-e4d28949c111.png)

**Comment by liuleshuai** [comment]
我还有个问题，由于我使用了tinker，不支持java1.8，这种情况如何集成DoraemonKit呢？

**Comment by jtsky** [comment]
> demo：把buildSrc目录下的build.gradle的gradle版本统一升级到4.0.1，报如下错误：
> ![image](https://user-images.githubusercontent.com/31751668/89748667-e19a0980-daf6-11ea-9bee-e4d28949c111.png)

我这边试了一下 好像并没有出现你截图里的问题 你试过clean 或者重启AS吗

**Comment by jtsky** [comment]
> 我还有个问题，由于我使用了tinker，不支持java1.8，这种情况如何集成DoraemonKit呢？

你可以加下我们的QQ群 然后在群里@一下我 我叫金台 我们私聊 这样效率高点

**Comment by liuleshuai** [comment]
好的
