### ISSUE TITLE
ios12  ios13上面logo不显示 看不到_entryBtn 入口

### ISSUE THREAD

**Issue by dedencLichKing** [didi/DoraemonKit#641]
在
+ (nullable UIImage *)doraemon_imageNamed:(NSString *)name{
    if(name &&
       ![name isEqualToString:@""]){
        NSBundle *bundle = [NSBundle bundleForClass:NSClassFromString(@"DoraemonManager")];
        NSURL *url = [bundle URLForResource:@"DoraemonKit" withExtension:@"bundle"];
        if(!url) return [UIImage new];
        NSBundle *imageBundle = [NSBundle bundleWithURL:url];
        
        NSString *imageName = nil;
        CGFloat scale = [UIScreen mainScreen].scale;
        if (ABS(scale-3) <= 0.001){
            imageName = [NSString stringWithFormat:@"%@@3x",name];
        }else if(ABS(scale-2) <= 0.001){
            imageName = [NSString stringWithFormat:@"%@@2x",name];
        }else{
            imageName = name;
        }
        UIImage *image = [UIImage imageWithContentsOfFile:[imageBundle pathForResource:imageName ofType:@"png"]];
        if (!image) {
            image = [UIImage imageWithContentsOfFile:[imageBundle pathForResource:name ofType:@"png"]];
            if (!image) {
                image = [UIImage imageNamed:name];
            }
        }
        return image;
    }
    
    return nil;
}

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/28124734/90507172-0857e000-e188-11ea-8691-5162c12069bd.png">
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/28124734/90507224-1efe3700-e188-11ea-9d70-7a75a0f5b7cd.png">

无法获取图标   看不到入口

**Comment by codingiran** [comment]
![image](https://user-images.githubusercontent.com/11780294/95652393-34a63200-0b23-11eb-8e2b-d3ab5e540953.png)
获取不了Assets.car内的资源

**Comment by mizikoi53** [comment]
已修复
