### ISSUE TITLE
内存泄漏检查并弹窗，突然不起作用

### ISSUE THREAD

**Issue by a714857512** [didi/DoraemonKit#648]
请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。
在混合开发中的Swift控制器中，制造内存泄漏，然后退出页面，页面没有释放，但是没有提醒内存泄漏的弹窗（开关均打开）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？
iOS 13.5.1
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）
> 最好给我们提供可以复现问题的Demo

**Comment by wm219** [comment]
你好，能否提供一个可以复现的demo

**Comment by a714857512** [comment]
又有了
