### ISSUE TITLE
集成后bugly 无法上传错误日志了

### ISSUE THREAD

**Issue by liudao01** [didi/DoraemonKit#649]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）希望能让bugly 把错误正常上传
> 问题重现的步骤。（如有）直接继承bugly
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有） 正常
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有） bugly 无法上传
> 最好给我们提供可以复现问题的Demo

**Comment by jtsky** [comment]
> Please complete the following informations.
> 
> > Expected behavior and actual behavior.
> > Steps to reproduce the problem.
> > Android or iOS? OS version? Brand?
> > More informations such as error messages and stack traces are welcomed.
> 
> 请补充如下信息。
> 
> > 期望的表现和实际的表现。（如有）希望能让bugly 把错误正常上传
> > 问题重现的步骤。（如有）直接继承bugly
> > Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有） 正常
> > 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有） bugly 无法上传
> > 最好给我们提供可以复现问题的Demo

可能是因为dokit在debug模式下拦截了错误日志，导致bugly无法正常抓取。按照我的理解bugly针对的主要还是线上环境的异常捕获和收集，而dokit的no-op包下全部是空实现函数，所以不会对bugly造成影响，请放心使用。
