### ISSUE TITLE
iOS建议核心组件不要依赖第三方库

### ISSUE THREAD

**Issue by Dilrvvr** [didi/DoraemonKit#660]
iOS建议核心组件不要依赖第三方库

DoraemonKit/Core 3.0.4 核心组件依赖的GCDWebServer和FMDB这两个库我们的项目都是以手动方式导入的，并进行了一些修改，所以会有冲突，目前只能使用旧版本。

建议需要依赖第三库的功能改为可选组件 WithXXX，由使用者自行选择。

**Comment by wjacker** [comment]
碰到了同样的问题,  建议核心组件尽量少引入第三方库, 这样避免第三方库版本跟项目本身使用的版本有冲突

**Comment by mizikoi53** [comment]
已记录
