### ISSUE TITLE
UI Layout Error on iOS 14

### ISSUE THREAD

**Issue by Vanson** [didi/DoraemonKit#662]
Please complete the following informations.
Version 12.0 (12A7209) -> iOS 14.0 (18A373) -> iPhone Xs Max

DoraemonKit (3.0.4) 

use cocoapods 
    pod 'DoraemonKit/Core', :configurations => ['Debug']
    pod 'DoraemonKit/WithLogger', :configurations => ['Debug']
    pod 'DoraemonKit/WithGPS', :configurations => ['Debug']
    pod 'DoraemonKit/WithLoad', :configurations => ['Debug']
    pod 'DoraemonKit/WithWeex', :configurations => ['Debug']
    pod 'DoraemonKit/WithDatabase', :configurations => ['Debug']

![IMG_3626](https://user-images.githubusercontent.com/3021140/93861004-709f6180-fcf2-11ea-9171-e62533ad79e9.PNG)

**Comment by YasinZhou** [comment]
had been fixed
