### ISSUE TITLE
swift 5.0可以使用吗

### ISSUE THREAD

**Issue by wfs498121294** [didi/DoraemonKit#664]
swift 5    import DoraemonKit   报 No such module 'DoraemonKit'

请问支持swift 5.0吗

**Comment by wfs498121294** [comment]
pod 'DoraemonKit/Core', '~> 3.0.4', :configurations => ['Debug'] #必选
    pod 'DoraemonKit/WithGPS', '~> 3.0.4', :configurations => ['Debug'] #可选
    pod 'DoraemonKit/WithLoad', '~> 3.0.4', :configurations => ['Debug'] #可选
    pod 'DoraemonKit/WithLogger', '~> 3.0.4', :configurations => ['Debug'] #可选
    pod 'DoraemonKit/WithDatabase', '~> 3.0.4', :configurations => ['Debug'] #可选
    pod 'DoraemonKit/WithMLeaksFinder', '~> 3.0.4', :configurations => ['Debug'] #可选

**Comment by wm219** [comment]
创建一下桥接文件，桥接文件引入一下
