### ISSUE TITLE
iOS14 WithGPS locationManagerDidChangeAuthorization NSAssert

### ISSUE THREAD

**Issue by JoakimLiu** [didi/DoraemonKit#668]
version: 'DoraemonKit/WithGPS', '3.0.4'
手机：模拟器 iPhone 11 pro,  version: 14.0
crash 处：CLLocationManager+Doraemon.m 类 Line27 的 NSAssert
原因：没实现 iOS14 的 `locationManagerDidChangeAuthorization:` 代理方法导致的。

**Comment by bsyqc163** [comment]
是的，好像是iOS14系统才有的，项目直接跑不起来了。。。

**Comment by YasinZhou** [comment]
这个将会在新版本修复
