### ISSUE TITLE
fastlane 打包导出会有问题

### ISSUE THREAD

**Issue by hackjie** [didi/DoraemonKit#67]
应该还是 bitcode 的问题：
2019-02-15 16:16:44.044 xcodebuild[2770:4958222] [MT] IDEDistribution: Step failed: <IDEDistributionPackagingStep: 0x7f921fc6d810>: Error Domain=IDEFoundationErrorDomain Code=1 "Failed to verify bitcode in DoraemonLoadAnalyze.framework/DoraemonLoadAnalyze:
error: Bundle only contains bitcode-marker /var/folders/1w/mfxlxzjn69b6rnvcq9s82bym0000gn/T/XcodeDistPipeline.5O4/Root/Payload/TuandaiLoan.app/Frameworks/DoraemonLoadAnalyze.framework/DoraemonLoadAnalyze (armv7)

" UserInfo={NSLocalizedDescription=Failed to verify bitcode in DoraemonLoadAnalyze.framework/DoraemonLoadAnalyze:
error: Bundle only contains bitcode-marker /var/folders/1w/mfxlxzjn69b6rnvcq9s82bym0000gn/T/XcodeDistPipeline.5O4/Root/Payload/TuandaiLoan.app/Frameworks/DoraemonLoadAnalyze.framework/DoraemonLoadAnalyze (armv7)

}
error: exportArchive: Failed to verify bitcode in DoraemonLoadAnalyze.framework/DoraemonLoadAnalyze:
error: Bundle only contains bitcode-marker /var/folders/1w/mfxlxzjn69b6rnvcq9s82bym0000gn/T/XcodeDistPipeline.5O4/Root/Payload/TuandaiLoan.app/Frameworks/DoraemonLoadAnalyze.framework/DoraemonLoadAnalyze (armv7)

Error Domain=IDEFoundationErrorDomain Code=1 "Failed to verify bitcode in DoraemonLoadAnalyze.framework/DoraemonLoadAnalyze:
error: Bundle only contains bitcode-marker /var/folders/1w/mfxlxzjn69b6rnvcq9s82bym0000gn/T/XcodeDistPipeline.5O4/Root/Payload/TuandaiLoan.app/Frameworks/DoraemonLoadAnalyze.framework/DoraemonLoadAnalyze (armv7)

**Comment by EyreFree** [comment]
1. 参考 [https://github.com/didi/DoraemonKit/issues/40](https://github.com/didi/DoraemonKit/issues/40) 中的临时解决方案；
2. 也可以手动将相应 target 的 ENABLE_BITCODE 设为 NO。

**Comment by hackjie** [comment]
嗯 改 podfile 了：

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if 'DoraemonKit' == config.build_settings['PRODUCT_NAME']
                config.build_settings['ENABLE_BITCODE'] = 'NO'
            end
        end
    end
end
```

但是利用 fastlane 最后导出包还是会报上面的问题

**Comment by albertjson** [comment]
嗯 改 podfile 了：

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if 'DoraemonKit' == config.build_settings['PRODUCT_NAME']
                config.build_settings['ENABLE_BITCODE'] = 'NO'
            end
        end
    end
end
```
我按照这样弄了，fastlane打包导出的时候还是会报错

```ruby
[18:21:37]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[18:21:37]: 📋  For the complete and more detailed error log, check the full log at:
[18:21:37]: 📋  /Users/ios1/Library/Logs/gym/WMDoctor-WMDoctor.log
[18:21:37]: 
[18:21:37]: Your `export_method` in gym is defined as `development`
[18:21:37]: which might cause problems when signing your application
[18:21:37]: Are you sure want to build and export for development?
[18:21:37]: Please make sure to define the correct export methods when calling
[18:21:37]: gym in your Fastfile or from the command line
```

**Comment by yixiangboy** [comment]
可以更新到1.1.5，看看有没有修复？

**Comment by albertjson** [comment]
> 可以更新到1.1.5，看看有没有修复？
试过了，已经可以正常fastlane打包了，O(∩_∩)O谢谢

**Comment by hackjie** [comment]
@albertjson 1.1.5 你还在 podfile 里加那段用来关闭 bitcode 了么

**Comment by albertjson** [comment]
> @albertjson 1.1.5 你还在 podfile 里加那段用来关闭 bitcode 了么

不需要了，我都把那段代码去掉了
