### ISSUE TITLE
Android-无法捕获app网络请求

### ISSUE THREAD

**Issue by geekTaolipeng** [didi/DoraemonKit#684]
androidx 

依赖配置:
  com.didichuxing.doraemonkit:dokitx:3.3.1
  com.didichuxing.doraemonkit:dokitx-plugin:3.3.1

打开app ,无法在网络模块中获取网络请求信息
apk 进行反编译 已经插入到okhttp

**Comment by geekTaolipeng** [comment]
解决bug:
    application 自己网络请求初始化大于 dokit 导致 okhttp中
       ` this.interceptors.addAll(OkHttpHook.globalInterceptors);
      this.networkInterceptors.addAll(OkHttpHook.globalNetworkInterceptors);`
    还未开始放入值

**Comment by newcaoguo** [comment]
good!
