### ISSUE TITLE
引入DoraemonKit后，APP启动时无法正常加载其他第三方so库

### ISSUE THREAD

**Issue by Dovar66** [didi/DoraemonKit#69]
引入DoraemonKit后，APP启动时无法正常加载其他第三方so库。
错误信息：java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader
异常设备：Android9.0的小米8、Android7.0的小米Max

但是在魅族设备上没问题

**Comment by LinJZong** [comment]
找不到的so是你们app的so吗，DoraemonKit中是没使用so的，理论上来说不会有问题。麻烦上一下具体的堆栈信息。

**Comment by Dovar66** [comment]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.xxx.xxx-cpqjAYRqnUsvap2ShRxuvA==/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx.xxx-cpqjAYRqnUsvap2ShRxuvA==/lib/arm64, /system/fake-libs64, /data/app/com.xxx.xxx-cpqjAYRqnUsvap2ShRxuvA==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libhyphenate.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.hyphenate.chat.EMClient.loadLibrary(Unknown Source:25)

是我项目中原有的第三方so，只要在build.gradle文件中引入了DoraemonKit就会导致找不到第三方so库，上面这个是找不到环信的报错

我是这样引入DoraemonKit的：
    debugImplementation 'com.didichuxing.doraemonkit:doraemonkit:1.1.1'
    releaseImplementation 'com.didichuxing.doraemonkit:doraemonkit-no-op:1.1.1'

**Comment by Dovar66** [comment]
问题我解决了，但是有个疑问，确定DoraemonKit中没引用到so吗?因为我的项目中jniLibs下只保留了armeabi目录，引入Doraemonkit之后运行在arm64-v8a设备上提示找不到so文件，所以应该是Doraemonkit中jniLibs下保留了多个架构目录，那就说明Doraemonkit有引用so啊。

**Comment by LinJZong** [comment]
你好，刚看了下，DoraemonKit是有引用了一个检测是否root的sdk,com.scottyab:rootbeer-lib,里面包含了所有架构的so。建议gradle配置ndk{ abiFilter "armeabi"}的方式来指定app保留的架构
