### ISSUE TITLE
不支持AndroidTV上使用遥控器操作

### ISSUE THREAD

**Issue by binaryxiaobao** [didi/DoraemonKit#697]
期望：可以在TV上使用遥控器操作

**Comment by jtsky** [comment]
> 期望：可以在TV上使用遥控器操作

当前DoKit针对的场景都是手机终端，暂时还不支持TV等其他大屏终端

**Comment by ff-frida** [comment]
> > 期望：可以在TV上使用遥控器操作
> 
> 当前DoKit针对的场景都是手机终端，暂时还不支持TV等其他大屏终端

大佬，后期不打算支持下吗
