### ISSUE TITLE
iOS DoraemonNSURLProtocol 中对didReceiveChallenge方法处理不完整  导致拦截失败

### ISSUE THREAD

**Issue by HYPERCHEN** [didi/DoraemonKit#698]
版本信息： iOS  DoraemonKit 3.0.4 
问题位置：DoraemonNSURLProtocol.m   line 207
问题描述：只判断了一种证书认证场景，导致其他证书认证场景失效。
建议 ：不对didReceiveChallenge方法进行重写。

**Comment by mizikoi53** [comment]
已修改，请等待新版
