### ISSUE TITLE
屏幕支持不完善

### ISSUE THREAD

**Issue by miku1958** [didi/DoraemonKit#70]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
屏幕支持有些问题,比方说:
横屏的时候,组件检查显示的内容是竖屏的,小屏幕显示不全
横屏的时候,带刘海的机型在显示设备信息的时候显示不全

> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
iOS
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

**Comment by LinJZong** [comment]
下个版本修复
