### ISSUE TITLE
CPU和内存在release的签名包中不work，获取不到数据

### ISSUE THREAD

**Issue by MrDoLoop** [didi/DoraemonKit#700]
CPU和内存在release的签名包中不work，获取不到数据
一加7/7pro/8都不行啊
Android 10是不是都不行了

**Comment by jtsky** [comment]
> CPU和内存在release的签名包中不work，获取不到数据
> 一加7/7pro/8都不行啊
> Android 10是不是都不行了

dokit的所有功能均为在release环境得到过验证，我们也不建议用户在release中使用

**Comment by MichaelJokAr** [comment]
+1
