### ISSUE TITLE
iOS更新到3.0.4后提审被拒，提示“二进制文件无效”

### ISSUE THREAD

**Issue by homekuanyi** [didi/DoraemonKit#704]
您好，这是我非常喜欢的开源工具之一，最近使用iOS版本DoraemonKit升级到3.0.4版本时，AppStore提审被拒，提示了“二进制文件无效”。

CocoaPods版本：1.10.0

Podfile相关部分如下：
```
  pod 'DoraemonKit/Core', :configurations => ['Debug'] #Required
  pod 'DoraemonKit/WithGPS', :configurations => ['Debug'] #Optional
  pod 'DoraemonKit/WithLoad', :configurations => ['Debug'] #Optional
```

检查苹果邮件：
ITMS-90853: Invalid font - There was an error validating the font at '***.app/Frameworks/GCDWebServer.framework/GCDWebUploader.bundle/Contents/Resources/fonts/glyphicons-halflings-regular.woff'. Font not supported by platform.

排查后发现DoraemonKit其中一项依赖库GCDWebServer使用了glyphicons-halflings-regular.woff，也就是GCDWebServer在Release也被引入了，只要修改Podfile文件即可解决。

`pod 'GCDWebServer', :configurations => ['Debug']`

对比3.0.2和3.0.4的podsec，留意GCDWebServer库在3.0.4被引入，这里建议DoraemonKit减少第三方库依赖，或者，更新下集成文档。借此PO出解决过程希望后面的童鞋减少踩坑。

**Comment by lhr000lhrmega** [comment]
is there any update about this issue?

**Comment by lhr000lhrmega** [comment]
The Cocoapods should have excluded these dependencies as well.
I wonder whether it's pod's bug.

**Comment by Haisens** [comment]
> 您好，这是我非常喜欢的开源工具之一，最近使用iOS版本DoraemonKit升级到3.0.4版本时，AppStore提审被拒，提示了“二进制文件无效”。
> 
> CocoaPods版本：1.10.0
> 
> Podfile相关部分如下：
> 
> ```
>   pod 'DoraemonKit/Core', :configurations => ['Debug'] #Required
>   pod 'DoraemonKit/WithGPS', :configurations => ['Debug'] #Optional
>   pod 'DoraemonKit/WithLoad', :configurations => ['Debug'] #Optional
> ```
> 
> 检查苹果邮件：
> ITMS-90853: Invalid font - There was an error validating the font at '***.app/Frameworks/GCDWebServer.framework/GCDWebUploader.bundle/Contents/Resources/fonts/glyphicons-halflings-regular.woff'. Font not supported by platform.
> 
> 排查后发现DoraemonKit其中一项依赖库GCDWebServer使用了glyphicons-halflings-regular.woff，也就是GCDWebServer在Release也被引入了，只要修改Podfile文件即可解决。
> 
> `pod 'GCDWebServer', :configurations => ['Debug']`
> 
> 对比3.0.2和3.0.4的podsec，留意GCDWebServer库在3.0.4被引入，这里建议DoraemonKit减少第三方库依赖，或者，更新下集成文档。借此PO出解决过程希望后面的童鞋减少踩坑。

感谢您对Dokit的支持，您的建议我们会认真对待。
