### ISSUE TITLE
3.0.4版本动态库集成时添加自定义插件无法显示图标

### ISSUE THREAD

**Issue by homekuanyi** [didi/DoraemonKit#705]
您好，使用DoraemonManager以下方法添加自定义插件时，由于图标从动态库读取，无法加载到UIImage，请问是否有其他方式添加自定义插件并正确显示预览图标？

`- (void)addPluginWithTitle:(NSString *)title icon:(NSString *)iconName desc:(NSString *)desc pluginName:(NSString *)entryName atModule:(NSString *)moduleName handle:(void(^)(NSDictionary *itemData))handleBlock;`

相关信息：
iOS版本3.0.4
引入方式动态库

**Comment by wm219** [comment]
暂时不支持
