### ISSUE TITLE
swift 日志如何记录和导出

### ISSUE THREAD

**Issue by zuqiu123** [didi/DoraemonKit#708]
目前发现nslog无法接受swift的日志？请问如何处理

**Comment by xhp281** [comment]
使用 CocoaLumberjack 这个插件

**Comment by wm219** [comment]
暂时不支持哈

**Comment by JeansHuang** [comment]
swift发个通知，给oc去调用NSLog
`func DLog<T>(_ object: T?, filename: String = #file, function: String = #function, line: Int = #line) {
    let fileString = filename as NSString
    let fileLastPathComponent = fileString.lastPathComponent as NSString
    let filename = fileLastPathComponent.deletingPathExtension
    var d: [String: Any] = ["n": filename, "f": function, "l": String(line)]
    if let o = object {
        d["o"] = o
    }
    // Swift 无法使用DoKit的日志记录功能，只能走OC调用
    NotificationCenter.default.post(name: NSNotification.Name("SwiftDLog"), object: nil, userInfo: d)
}`

- (void)swiftLogNotification: (NSNotification *)noti {
    DLog(@"fileName:%@\nfunction:%@\nline:%@\nobject:%@",
         noti.userInfo[@"n"],
         noti.userInfo[@"f"],
         noti.userInfo[@"l"],
         noti.userInfo[@"o"]
         );
}

#define DLog(fmt, ...) NSLog((@"%s [Line %d] \n" fmt), __PRETTY_FUNCTION__, __LINE__, ##__VA_ARGS__)
