### ISSUE TITLE
android版本会默认修改activity对话框的gravity居左显示

### ISSUE THREAD

**Issue by dongweiq** [didi/DoraemonKit#71]
- 问题重现的步骤。创建一个activity弹出非全屏的对话框，如果不引入gradle的库。默认剧中显示，引入后对话框居左显示。
- Android 5.1的设备，是一个开发板

**Comment by LinJZong** [comment]
应该是跟support库的版本有关，请问你们项目中使用的support库版本号是多少

**Comment by dongweiq** [comment]
supportLibVersion = "27.1.1"
