### ISSUE TITLE
Flutter DoraemonKit runZone的问题

### ISSUE THREAD

**Issue by zmtzawqlp** [didi/DoraemonKit#726]
在main函数入口初始化。 DoKit使用runZone的方式进行日志捕获，方法通道的捕获，如果你的app需要使用同样的方式会有冲突

---
实际中项目中会上报这些错误，所以希望能够将回调都暴露出来这样的话，也不影响外部使用

**Comment by LinJZong** [comment]
0.2.6版本添加了日志和异常回调
