### ISSUE TITLE
t项目中使用了DoraemonKit，导致了项目中UITextView和UITextField不能复制粘贴了,这个问题还是比较影响我们项目使用的

### ISSUE THREAD

**Issue by canlanrensheng** [didi/DoraemonKit#728]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）
> 最好给我们提供可以复现问题的Demo

**Comment by songhongkang** [comment]
刚试了，没有影响

**Comment by canlanrensheng** [comment]
嗯，我排查发现&nbsp;[[CJDeveloperEnvironmentManager shareInstance] install];
这段代码导致复制粘贴功能失效的，把上面这句代码放在[self.window makeKeyAndVisible];后面就可以了，具体原因我还不知道，估计是window导致的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "didi/DoraemonKit"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月26日(星期二) 上午9:44
收件人:&nbsp;"didi/DoraemonKit"<DoraemonKit@noreply.github.com&gt;;
抄送:&nbsp;"灿烂人生"<2649154231@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [didi/DoraemonKit] t项目中使用了DoraemonKit，导致了项目中UITextView和UITextField不能复制粘贴了,这个问题还是比较影响我们项目使用的 (#728)





 
刚试了，没有影响
