### ISSUE TITLE
open activity time cost should not use "System.currentTimeMillis()"

### ISSUE THREAD

**Issue by guanglixiang** [didi/DoraemonKit#733]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
用“System.currentTimeMillis()"方式计算出来的耗时，可能会出现负数，或者失真的情况。
> 问题重现的步骤。（如有）
很难复现的问题，但极端情况下会出现。猜测一种出现的可能场景是：手机同步改变了系统时间，恰在此时打开了待统计的activity
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
Android
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

> 最好给我们提供可以复现问题的Demo

**Comment by jtsky** [comment]
已采纳 感谢提供的建议
