### ISSUE TITLE
文档中的weex依赖写错了~ 

### ISSUE THREAD

**Issue by Bilue404** [didi/DoraemonKit#738]
![image](https://user-images.githubusercontent.com/5109522/105656329-e9126b00-5efc-11eb-87d5-897d534d5d1d.png)

文档中的weex依赖写错了，导致下载不到~ 
改成dokitx下载到了~

**Comment by jtsky** [comment]
> ![image](https://user-images.githubusercontent.com/5109522/105656329-e9126b00-5efc-11eb-87d5-897d534d5d1d.png)
> 
> 文档中的weex依赖写错了，导致下载不到~
> 改成dokitx下载到了~

好的  感谢提醒  我这边改一下
