### ISSUE TITLE
集成dokit flutter 安卓端报错

### ISSUE THREAD

**Issue by leileiChenGentleman** [didi/DoraemonKit#739]
**FAILURE: Build failed with an exception.

* Where:
Initialization script '/Users/aikucun/flutter/flutter/packages/flutter_tools/gradle/aar_init_script.gradle' line: 15

* What went wrong:
Android property not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

Gradle task assembleAarDebug failed with exit code 0.**

本地flutter版本1.17.1

**Comment by LinJZong** [comment]
你的工程或者你引用的plugin里面不包含android module 如果是demo工程 检查下是否包含android目录 如果是正式工程 检查下引用的pub库 可以在aar_init_script.gradle脚本里自己加一下报错的工程信息。
`
void configureProject(Project project, String outputDir) {
    if (!project.hasProperty("android")) {
        println("Android property not found ${project}");
        throw new GradleException("Android property not found.")
    }
`

**Comment by leileiChenGentleman** [comment]
> **FAILURE: Build failed with an exception.
> 
> * Where:
>   Initialization script '/Users/aikucun/flutter/flutter/packages/flutter_tools/gradle/aar_init_script.gradle' line: 15
> * What went wrong:
>   Android property not found.
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1s
> 
> Gradle task assembleAarDebug failed with exit code 0.**
> 
> 本地flutter版本1.17.1

**Comment by leileiChenGentleman** [comment]
问题已解决，项目基于的flutter版本低于了1.17.5
