### ISSUE TITLE
开启内存或CPU点击关闭DoraemonKit，mask依然存在

### ISSUE THREAD

**Issue by zou145688zhuang** [didi/DoraemonKit#74]
![2019-02-18 4 59 03](https://user-images.githubusercontent.com/11897056/52939394-0d737d80-339f-11e9-9321-3f6327698bf0.png)
![20190218170221837](https://user-images.githubusercontent.com/11897056/52939399-119f9b00-339f-11e9-8ccd-5ff721c5aebb.png)
![20190218170230897](https://user-images.githubusercontent.com/11897056/52939405-12d0c800-339f-11e9-97c3-77308727c4d2.png)

**Comment by yixiangboy** [comment]
我看你的界面是很旧的版本了，请更新到最新版本。https://github.com/didi/DoraemonKit/blob/master/Doc/iOS_cn_guide.md
