### ISSUE TITLE
崩溃DoraemonNSURLProtocol

### ISSUE THREAD

**Issue by zou145688zhuang** [didi/DoraemonKit#75]
iPhone 8 Plus -12.1
![2019-02-18 5 08 10](https://user-images.githubusercontent.com/11897056/52939730-d6ea3280-339f-11e9-9e27-3e283d6b7654.png)

**Comment by yixiangboy** [comment]
有详细日志吗？

**Comment by yixiangboy** [comment]
请更新到最新版本
