### ISSUE TITLE
【DoKit-Flutter】-方法渠道(methodChannel)监听问题

### ISSUE THREAD

**Issue by Silence17136** [didi/DoraemonKit#752]
加入了sensors(传感器)库并监听，方法渠道列表不停的刷，导致无法查看其它渠道

**Comment by LinJZong** [comment]
sensors库本质上就是通过方法通道从native端回调数据，符合预期。
后续考虑增加配置黑名单功能。

**Comment by LinJZong** [comment]
已在0.2.14版本增加黑名单功能，具体请看文档和example
