### ISSUE TITLE
【iOS】请问为什么mock数据不支持匹配域名？

### ISSUE THREAD

**Issue by SelmerZhang** [didi/DoraemonKit#757]
比如我要用的接口是https://www.baidu.com/myapi和https://www.tencent.com/myapi，只能设置path为myapi来匹配（两个都会被mock），而不能匹配到域名？是我用的方法有问题吗？

**Comment by jtsky** [comment]
> 比如我要用的接口是[https://www.baidu.com/myapi和https://www.tencent.com/myapi，只能设置path为myapi来匹配（两个都会被mock），而不能匹配到域名？是我用的方法有问题吗？](https://www.baidu.com/myapi%E5%92%8Chttps://www.tencent.com/myapi%EF%BC%8C%E5%8F%AA%E8%83%BD%E8%AE%BE%E7%BD%AEpath%E4%B8%BAmyapi%E6%9D%A5%E5%8C%B9%E9%85%8D%EF%BC%88%E4%B8%A4%E4%B8%AA%E9%83%BD%E4%BC%9A%E8%A2%ABmock%EF%BC%89%EF%BC%8C%E8%80%8C%E4%B8%8D%E8%83%BD%E5%8C%B9%E9%85%8D%E5%88%B0%E5%9F%9F%E5%90%8D%EF%BC%9F%E6%98%AF%E6%88%91%E7%94%A8%E7%9A%84%E6%96%B9%E6%B3%95%E6%9C%89%E9%97%AE%E9%A2%98%E5%90%97%EF%BC%9F)

DoKit在设计数据Mock这个功能的时候就是不匹配域名的，因为一般通过一个app每个环境(debug、pre、release)的域名是不一样的，所以为了让数据mock的功能更具有通用性我们就排除了域名匹配。

**Comment by SelmerZhang** [comment]
了解了，谢谢
