### ISSUE TITLE
kotlin-android-extensions 这个插件已经废弃了。

### ISSUE THREAD

**Issue by woligiaogiaoa** [didi/DoraemonKit#764]
kotlin-android-extensions 这个插件已经废弃了。然后这个插件 里面的一些代码 已经被迁移了到其他软件包了，比如kotlinx.android.parcel.Parcelize里面的很多类被迁移到新的软件包 比如org.jetbrains.kotlin:kotlin-parcelize-runtime:1.4.20-RC。
我的项目里面用了一些第三方库比如我用了airbnb的epoxy，epoxy里面引用了 org.jetbrains.kotlin:kotlin-parcelize-runtime:1.4.20-RC.所以导致我集成滴滴的开源库的时候，DoraemonKit 和 epoxy都有相同名字的类。所以会报错duplicate class

**Comment by jtsky** [comment]
> kotlin-android-extensions 这个插件已经废弃了。然后这个插件 里面的一些代码 已经被迁移了到其他软件包了，比如kotlinx.android.parcel.Parcelize里面的很多类被迁移到新的软件包 比如org.jetbrains.kotlin:kotlin-parcelize-runtime:1.4.20-RC。
> 我的项目里面用了一些第三方库比如我用了airbnb的epoxy，epoxy里面引用了 org.jetbrains.kotlin:kotlin-parcelize-runtime:1.4.20-RC.所以导致我集成滴滴的开源库的时候，DoraemonKit 和 epoxy都有相同名字的类。所以会报错duplicate class

我们后期会去适配这个问题的

**Comment by jtsky** [comment]
最新版本已经去掉
