### ISSUE TITLE
LaunchScreen.storyboard 启动页该如何适配所有机型

### ISSUE THREAD

**Issue by csc-EricWu** [didi/DoraemonKit#78]
iOS   LaunchScreen.storyboard 如果只放一张图的话，该如何适配所有机型，这张图的尺寸应该是多少，能否在demo中做个范例。

**Comment by yixiangboy** [comment]
建议提的issues跟DoraemonKit相关，可以在qq群里提出来，让大家讨论。因为我也不清楚，没遇到过。
