### ISSUE TITLE
iOS 依赖包FBRetainCycleDetector 编译报错

### ISSUE THREAD

**Issue by JzwOnly** [didi/DoraemonKit#787]
Xcode 12.5
MacOS 11.2.3
![image](https://user-images.githubusercontent.com/21191349/115805778-3a58ca80-a418-11eb-9dfc-23ba4812306e.png)

**Comment by ZhangTonghai** [comment]
https://github.com/facebook/FBRetainCycleDetector/issues/115
参考官方临时解决方法

**Comment by macRong** [comment]
直接办法：
`layoutCache[(id<NSCopying>)currentClass] = ivars;`
