### ISSUE TITLE
和JGProgressHUD的layoutSubviews 循环调用了

### ISSUE THREAD

**Issue by zxconan** [didi/DoraemonKit#79]
iOS12.1 应用启动
![image](https://user-images.githubusercontent.com/2890376/52993881-add5aa80-3450-11e9-9d22-23dd5633ea67.png)

**Comment by hiXgb** [comment]
感谢反馈，修复的代码已经提交至master分支

**Comment by yixiangboy** [comment]
1.1.6已经修复
