### ISSUE TITLE
【DoKit生态场景】iphone刘海屏适配问题

### ISSUE THREAD

**Issue by 371726787** [didi/DoraemonKit#799]
![IMG_5117](https://user-images.githubusercontent.com/80081972/116497513-21e62580-a8da-11eb-886a-380b57de71ef.PNG)

**Comment by kabda** [comment]
你好，请问你使用的环境，以及设备的机型是什么？

**Comment by ianisme** [comment]
我提过PR了，已经修复了，你用最新的master代码就行了。

**Comment by 371726787** [comment]
好的好的，感谢

**Comment by 371726787** [comment]
> 你好，请问你使用的环境，以及设备的机型是什么？

iphonex，从原来3.0.初到现在一直都发现iphone刘海屏的都有问题
