### ISSUE TITLE
【DoKit生态场景】-升级Xcode12.5编译报错

### ISSUE THREAD

**Issue by yangln123** [didi/DoraemonKit#808]
升级完XCode12.5版本后，FBRetainCycleDetector库编译报错；
使用3.0.7版本；
错误信息“Cannot initialize a parameter of type 'id<NSCopying> _Nonnull' with an rvalue of type 'Class'”

**Comment by Serena1993** [comment]
+1

**Comment by a714857512** [comment]
+1

**Comment by a714857512** [comment]
+1

**Comment by ChasonTang** [comment]
Just replace
pod 'FBRetainCycleDetector', '~> 0.1.4'
with
pod 'FBRetainCycleDetector', :git => 'git@github.com:facebook/FBRetainCycleDetector.git' ,:branch => 'master'
then
pod update
