### ISSUE TITLE
iOS: 程序打开时异常

### ISSUE THREAD

**Issue by TimberTang** [didi/DoraemonKit#81]
在
UIView+DoraemonViewMetrics分类里面打开load方法,
appdelegate还没有[[DoraemonManager shareInstance] install] 程序运行时抛出异常
报错内容如下:

[UINavigationBar _applyConstrainedContentSizeIfNecessary]: unrecognized selector sent to instance 0x104b24be0
2019-02-19 16:57:57.773546+0800 XiaoQueXin[16393:7141406] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UINavigationBar _applyConstrainedContentSizeIfNecessary]: unrecognized selector sent to instance 0x104b24be0'
*** First throw call stack:
(0x1dada0ec4 0x1d9f71a40 0x1dacb9c24 0x2080e4558 0x1dada67dc 0x1dada848c 0x2084ddee8 0x2083e3bb8 0x2078c0190 0x20855f7dc 0x2078bff8c 0x1df39db74 0x1df3a2b2c 0x20854acc8 0x207a4b5b4 0x207a4b800 0x207a4af5c 0x207a4a8c4 0x207a51e48 0x207aef50c 0x207aefc78 0x207a5fe30 0x207a5f9e0 0x207a417a4 0x1024e747c 0x1dac870d4 0x1024e7200 0x1024e6dd8 0x207a25664 0x1024f0bac 0x2080adde0 0x2080af548 0x2080b4f94 0x2079508f4 0x207959574 0x207950570 0x207950f10 0x20794f010 0x20794ecbc 0x207953e7c 0x207954ddc 0x207953d34 0x207958c20 0x2080b348c 0x207c9e1fc 0x1dd7d79d4 0x1dd7e279c 0x1dd7e1e94 0x1047ecdc8 0x1047f0a10 0x1dd816a9c 0x1dd816728 0x1dd816d44 0x1dad311f0 0x1dad31170 0x1dad30a54 0x1dad2b920 0x1dad2b1f0 0x1dcfa4584 0x2080b6d40 0x10244cd4c 0x1da7eabb4)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by TimberTang** [comment]
iOS 12.1.2 iPhone 7p

**Comment by LDXu** [comment]
相同问题

**Comment by hiXgb** [comment]
感谢反馈，修复的代码已经提交至master分支
