### ISSUE TITLE
【DoKit生态场景】-DoKitCommTransform This feature requires ASM7

### ISSUE THREAD

**Issue by donlan** [didi/DoraemonKit#810]
【问题】编译遇到ASM7错误，导致无法完成编译
【版本】Android 3.3.5
【Android Studio】 4.2
【JDK】11
【Gradle】6.5.1

```
> Task :app:transformClassesWithDoKitCommTransformForDevDebug UP-TO-DATE
error processing /Users/xxxx/Android/xxxxx/app/build/intermediates/transforms/DoKitCommTransform/dev/debug/235.jar
java.lang.UnsupportedOperationException: This feature requires ASM7
	at org.objectweb.asm.ClassVisitor.visitNestHost(ClassVisitor.java:150)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:550)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
	at com.android.builder.desugaring.DesugaringClassAnalyzer.analyze(DesugaringClassAnalyzer.java:153)
	at com.android.builder.desugaring.DesugaringClassAnalyzer.analyzeJar(DesugaringClassAnalyzer.java:100)
	at com.android.builder.desugaring.DesugaringClassAnalyzer.analyze(DesugaringClassAnalyzer.java:68)
	at com.android.build.gradle.internal.tasks.DesugarIncrementalHelper.lambda$getInitalGraphData$4(DesugarIncrementalHelper.java:146)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

```

**Comment by jtsky** [comment]
> 【问题】编译遇到ASM7错误，导致无法完成编译
> 【版本】Android 3.3.5
> 【Android Studio】 4.2
> 【JDK】11
> 【Gradle】6.5.1
> 
> 
> ```
> > Task :app:transformClassesWithDoKitCommTransformForDevDebug UP-TO-DATE
> error processing /Users/dooze/Android/daycam-android/app/build/intermediates/transforms/DoKitCommTransform/dev/debug/235.jar
> java.lang.UnsupportedOperationException: This feature requires ASM7
> 	at org.objectweb.asm.ClassVisitor.visitNestHost(ClassVisitor.java:150)
> 	at org.objectweb.asm.ClassReader.accept(ClassReader.java:550)
> 	at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
> 	at com.android.builder.desugaring.DesugaringClassAnalyzer.analyze(DesugaringClassAnalyzer.java:153)
> 	at com.android.builder.desugaring.DesugaringClassAnalyzer.analyzeJar(DesugaringClassAnalyzer.java:100)
> 	at com.android.builder.desugaring.DesugaringClassAnalyzer.analyze(DesugaringClassAnalyzer.java:68)
> 	at com.android.build.gradle.internal.tasks.DesugarIncrementalHelper.lambda$getInitalGraphData$4(DesugarIncrementalHelper.java:146)
> 	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
> 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
> 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
> 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
> 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
> ```

现在插件暂时还没适配AS4.2 正在积极适配中

**Comment by jtsky** [comment]
> > 【问题】编译遇到ASM7错误，导致无法完成编译
> > 【版本】Android 3.3.5
> > 【Android Studio】 4.2
> > 【JDK】11
> > 【Gradle】6.5.1
> > ```
> > > Task :app:transformClassesWithDoKitCommTransformForDevDebug UP-TO-DATE
> > error processing /Users/dooze/Android/daycam-android/app/build/intermediates/transforms/DoKitCommTransform/dev/debug/235.jar
> > java.lang.UnsupportedOperationException: This feature requires ASM7
> > 	at org.objectweb.asm.ClassVisitor.visitNestHost(ClassVisitor.java:150)
> > 	at org.objectweb.asm.ClassReader.accept(ClassReader.java:550)
> > 	at org.objectweb.asm.ClassReader.accept(ClassReader.java:400)
> > 	at com.android.builder.desugaring.DesugaringClassAnalyzer.analyze(DesugaringClassAnalyzer.java:153)
> > 	at com.android.builder.desugaring.DesugaringClassAnalyzer.analyzeJar(DesugaringClassAnalyzer.java:100)
> > 	at com.android.builder.desugaring.DesugaringClassAnalyzer.analyze(DesugaringClassAnalyzer.java:68)
> > 	at com.android.build.gradle.internal.tasks.DesugarIncrementalHelper.lambda$getInitalGraphData$4(DesugarIncrementalHelper.java:146)
> > 	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448)
> > 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
> > 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
> > 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
> > 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
> > 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
> > ```
> 
> 现在插件暂时还没适配AS4.2 正在积极适配中

DoKit for Android v3.4.0-alpha02版本已发发布
https://github.com/didi/DoraemonKit/blob/master/Doc/android-ReleaseNotes.md
