### ISSUE TITLE
OkHttpAspect在demo中编译后未插桩代码

### ISSUE THREAD

**Issue by lizuojing** [didi/DoraemonKit#82]
运行demo代码，编译后在build文件夹中并没有生成插桩后的代码？为什么呢？
![image](https://user-images.githubusercontent.com/4328469/53017684-86e89a00-348b-11e9-8c10-cf2fb8773ae0.png)

**Comment by LinJZong** [comment]
目前版本只支持主module的代码插桩，后续会完善对依赖包的支持

**Comment by wanglikun7342** [comment]
1.1.5版本已经支持，请替换插桩插件
