### ISSUE TITLE
统计app信息到滴滴服务器上不太合适吧

### ISSUE THREAD

**Issue by jseanj** [didi/DoraemonKit#83]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

**Comment by yixiangboy** [comment]
您好。我们目前只上传了bundleId和appName（详见DoraemonStatisticsUtil这个类），这些并不是隐私数据，上传这些数据我们完全是为了了解我们这个项目的使用量和发展，不用于任何恶意行为，如果您还是有所担心的话，我们会在后续版本加上开关，您可以主动关闭数据上传功能。谢谢您的反馈。

**Comment by Richard-Cao** [comment]
@yixiangboy 这个统计功能什么时候会去掉呢

**Comment by yixiangboy** [comment]
> @yixiangboy 这个统计功能什么时候会去掉呢

后来我们决定还是需要统计一下真正使用的用户，对于我们这个项目的活跃度有个了解，我们在github官网也有使用说明。

**Comment by yixiangboy** [comment]
> @yixiangboy 这个统计功能什么时候会去掉呢

不过 你放心 我们不会用于任何恶意用途，单纯了解一下 我们sdk的用户数。

**Comment by Richard-Cao** [comment]
> > @yixiangboy 这个统计功能什么时候会去掉呢
> 
> 不过 你放心 我们不会用于任何恶意用途，单纯了解一下 我们sdk的用户数。

是这样的，可能有些APP是比较保密或者隐私的，但是也想用这个库，这时候发现你们统计了包名、APP名字等信息，就会有比较大的顾虑，加个能关闭上传的开关也好啊

**Comment by yixiangboy** [comment]
> > > @yixiangboy 这个统计功能什么时候会去掉呢
> > 
> > 
> > 不过 你放心 我们不会用于任何恶意用途，单纯了解一下 我们sdk的用户数。
> 
> 是这样的，可能有些APP是比较保密或者隐私的，但是也想用这个库，这时候发现你们统计了包名、APP名字等信息，就会有比较大的顾虑，加个能关闭上传的开关也好啊

好的 兄弟。我们下个版本加个开关。也欢迎给我们提意见和PR。

**Comment by Richard-Cao** [comment]
> > > > @yixiangboy 这个统计功能什么时候会去掉呢
> > > 
> > > 
> > > 不过 你放心 我们不会用于任何恶意用途，单纯了解一下 我们sdk的用户数。
> > 
> > 
> > 是这样的，可能有些APP是比较保密或者隐私的，但是也想用这个库，这时候发现你们统计了包名、APP名字等信息，就会有比较大的顾虑，加个能关闭上传的开关也好啊
> 
> 好的 兄弟。我们下个版本加个开关。也欢迎给我们提意见和PR。

好的，感谢，坐等更新，这个功能我觉得做成让接入方可选的是最合理的，其实如果是可选的，对APP名字什么的没太大隐私问题的话都会帮你们统计的，如果这方面顾虑比较大的用户可以选择不统计，但是也可以用你们的库，会增大库的使用人数，也算是为开源社区做贡献嘛

**Comment by Richard-Cao** [comment]
下个版本什么时候发布呢，好像有一段时间没发版了 @yixiangboy

**Comment by Richard-Cao** [comment]
#161
