### ISSUE TITLE
无法对输入法软键盘进行测试

### ISSUE THREAD

**Issue by shiduanbin** [didi/DoraemonKit#86]
如题

**Comment by yixiangboy** [comment]
能够描述详细一点吗？

**Comment by shiduanbin** [comment]
sorry，描述太简单了
我开发了一个输入法app，我尝试在它上面集成DoraemonKit。对于一个Activity来说，进入到界面后能看到测试入口，但是输入法是运行在其他应用的界面之上，它本身的界面不是一个Activity，我无法在输入法app上集成DoraemonKit来测试输入法的性能

**Comment by LinJZong** [comment]
目前入口icon的显示是通过注册Application的ActivityLifecycleCallbacks的方式，在Activity的onResume方法被回调时进行显示的，如果app没有Activity，可以通过直接调用DoraemonKit.show()方法手动去显示
