### ISSUE TITLE
Kotlin 1.5.20 无法使用

### ISSUE THREAD

**Issue by Felix8029** [didi/DoraemonKit#864]
Unable to find method ''void kotlin.jvm.internal.FunctionReferenceImpl.<init>(int, java.lang.Object, java.lang.Class, java.lang.String, java.lang.String, int)''
'void kotlin.jvm.internal.FunctionReferenceImpl.<init>(int, java.lang.Object, java.lang.Class, java.lang.String, java.lang.String, int)'

![image](https://user-images.githubusercontent.com/23181228/126751195-7a0327f2-d54f-4002-917c-0d058a6b76ce.png)

**Comment by jtsky** [comment]
> Unable to find method ''void kotlin.jvm.internal.FunctionReferenceImpl.(int, java.lang.Object, java.lang.Class, java.lang.String, java.lang.String, int)''
> 'void kotlin.jvm.internal.FunctionReferenceImpl.(int, java.lang.Object, java.lang.Class, java.lang.String, java.lang.String, int)'
> 
> ![image](https://user-images.githubusercontent.com/23181228/126751195-7a0327f2-d54f-4002-917c-0d058a6b76ce.png)

dokit由于涉及到用户以及编译环境比较多 所以依赖的kotlin环境暂时还没法升级到1.5版本。当前kotlin支持1.3.72 以及1.4.32

**Comment by jtsky** [comment]
> Unable to find method ''void kotlin.jvm.internal.FunctionReferenceImpl.(int, java.lang.Object, java.lang.Class, java.lang.String, java.lang.String, int)''
> 'void kotlin.jvm.internal.FunctionReferenceImpl.(int, java.lang.Object, java.lang.Class, java.lang.String, java.lang.String, int)'
> 
> ![image](https://user-images.githubusercontent.com/23181228/126751195-7a0327f2-d54f-4002-917c-0d058a6b76ce.png)

你可以试试dokit 3.4.2版本是依赖kotlin 1.4.32打包出来的 我在1.5+的环境上试过 好像是可以的。

**Comment by Felix8029** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
