### ISSUE TITLE
【Android】-和项目中samsung的多窗口jar包发生重复依赖冲突

### ISSUE THREAD

**Issue by feels-good** [didi/DoraemonKit#866]
dokit:3.3.5

**Comment by jtsky** [comment]
> dokit:3.3.5

建议参考dokit.cn的安卓接入文档升级到最新版本

**Comment by feels-good** [comment]
![image](https://user-images.githubusercontent.com/65146067/127131118-8b5757fb-8585-48a2-93d3-16fd9c72c2e2.png)
![image](https://user-images.githubusercontent.com/65146067/127135010-8a7420af-fea2-4034-a9b2-9a1e264bea91.png)
![image](https://user-images.githubusercontent.com/65146067/127135024-bbcb3be2-4a67-4dc7-9c93-0786a317d863.png)
更新到了3.4.0，报错如上图
