### ISSUE TITLE
ios 打包报错

### ISSUE THREAD

**Issue by nicesgoodnight** [didi/DoraemonKit#90]
ld: warning: directory not found for option '-L/Users/wangyi/Desktop/healthManager/XG'
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_DoraemonManager", referenced from:
      objc-class-ref in DoraemonKitHelper.o
      objc-class-ref in KDDoraemonEnvPlugin.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

工程测试都没问题 但是打包就提示创建的工具类有问题  如果DoraemonKit包存在工程 不调用接入的代码又不会有问题

**Comment by yixiangboy** [comment]
接入的是哪一个版本？

**Comment by yixiangboy** [comment]
你可以参考一下这两个issues https://github.com/didi/DoraemonKit/issues/67  https://github.com/didi/DoraemonKit/issues/40
