### ISSUE TITLE
iOS15启动崩溃（3.0.7、3.1.0均崩溃）

### ISSUE THREAD

**Issue by 371726787** [didi/DoraemonKit#909]
<img width="1268" alt="截屏2021-09-22 上午11 28 29" src="https://user-images.githubusercontent.com/80081972/134279838-8fb28437-5739-47da-9ca2-a9ef84f8cefc.png">

**Comment by ChenPingSheng** [comment]
我这里崩在WKWebView的loadRequest方法
![截屏2021-09-23 上午11 07 40](https://user-images.githubusercontent.com/14194096/134449384-702efa5e-23fd-47f6-9a7f-77fbd4252d2b.png)

**Comment by ChenPingSheng** [comment]
参考这个链接解决了，可能是Xcode13的bug：https://developer.apple.com/forums/thread/689022

**Comment by githublsy** [comment]
![image](https://user-images.githubusercontent.com/13412799/137682454-75032b92-9297-46f8-92e0-51925328180c.png)

有这种情况的吗

**Comment by ChasonTang** [comment]
该问题已在 iOS 3.1.2 版本解决
