### ISSUE TITLE
【iOS15 】- release真机crash，debug正常

### ISSUE THREAD

**Issue by jtans** [didi/DoraemonKit#927]
It is recommended to refer to the following process before submitting issues：https://github.com/didi/DoraemonKit/issues/745
If you still cannot solve your problem, you can submit your issue according to the following template

Please complete the following informations.
> Android、iOS? OS version? Brand? 
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> More informations such as error messages and stack traces are welcomed.
>

建议提issues之前可以参考一下DoKit社区答疑流程：https://github.com/didi/DoraemonKit/issues/745
假如还是无法解决你的问题，你可以按照以下模板来提交你的issue

请补充如下信息。
>  iOS 15真机
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> 
Date/Time:           2021-10-27 14:26:33.5349 +0800
Launch Time:         2021-10-27 14:26:32.8554 +0800
OS Version:          iPhone OS 15.0.2 (19A404)
Release Type:        User
Baseband Version:    7.02.00
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  0

Application Specific Information:

Thread 0 name:   Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_kernel.dylib        	       0x1bca06a48 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x1dce428d8 pthread_kill + 208
2   libsystem_c.dylib             	       0x18d8ed0c0 abort + 120
3   libsystem_c.dylib             	       0x18d9406ac err + 0
4   DoraemonKit                   	       0x1028027c0 doraemon_perform_rebinding_with_section.cold.3 + 780224 (doraemon_fishhook.c:0)
5   DoraemonKit                   	       0x10274d150 doraemon_perform_rebinding_with_section + 37200 (doraemon_fishhook.c:158)
6   DoraemonKit                   	       0x10274ce04 doraemon_rebind_symbols_for_image + 36356 (doraemon_fishhook.c:210)
7   dyld                          	       0x10254eec8 invocation function for block in dyld4::APIs::_dyld_register_func_for_add_image(void (*)+ 44744 (mach_header const*, long)) + 164
8   dyld                          	       0x1025482d4 dyld4::RuntimeState::withLoadersReadLock(void + 17108 () block_pointer) + 60
9   dyld                          	       0x10256e3d0 dyld4::APIs::_dyld_register_func_for_add_image(void (*)+ 173008 (mach_header const*, long)) + 124
10  DoraemonKit                   	       0x10274ceec doraemon_rebind_symbols + 36588 (doraemon_fishhook.c:259)
11  DoraemonKit                   	       0x1027b7534 -[DoraemonNSLogManager startNSLogMonitor] + 472372 (DoraemonNSLogManager.m:0)
12  DoraemonKit                   	       0x1027907e4 -[DoraemonManager installWithCustomBlock:] + 313316 (DoraemonManager.m:173)

**Comment by ChasonTang** [comment]
可以试一下 iOS  3.1.1 版本

**Comment by yingkong1987** [comment]
> 可以试一下 DoKit iOS 3.1.1 版本

我iOS3.1.1版本 ，真机调试，拔线后启动APP，此处必现Crash。

**Comment by ChasonTang** [comment]
行，我看下

**Comment by ChasonTang** [comment]
已修复并发布，请尝试 DoKit iOS 3.1.2 版本
