### ISSUE TITLE
andorid app 跳转到二级界面中，点击Dokit 图标展开Dokit 界面背景变成透明的了 

### ISSUE THREAD

**Issue by qiushihang** [didi/DoraemonKit#934]
It is recommended to refer to the following process before submitting issues：https://github.com/didi/DoraemonKit/issues/745
If you still cannot solve your problem, you can submit your issue according to the following template

Please complete the following informations.
> Android、iOS? OS version? Brand? 
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> More informations such as error messages and stack traces are welcomed.
>

建议提issues之前可以参考一下DoKit社区答疑流程：https://github.com/didi/DoraemonKit/issues/745
假如还是无法解决你的问题，你可以按照以下模板来提交你的issue

请补充如下信息。
> Android 还是 iOS？系统版本是多少？手机品牌是什么  Anroid, HUWAWEI andorid 11
> 期望的表现和实际的表现。（Dokit 控制操作界面纯白色背景
> 问题重现的步骤。android app 启动后，点击一个二级界面，再点击Dokit icon 打开控制界面，发现控制界面背景是透明的，很不方便
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

**Comment by alvince** [comment]
需要提供更详细的上下文信息

**Comment by qiushihang** [comment]
已经解决了，是我代码的问题。

**Comment by qiushihang** [comment]
已经解决了，是我代码的问题。
