### ISSUE TITLE
希望增加flutter的接入

### ISSUE THREAD

**Issue by ppjjzz** [didi/DoraemonKit#94]
Please complete the following informations.
> Expected behavior and actual behavior.
> Steps to reproduce the problem.
> Android or iOS? OS version? Brand? 
> More informations such as error messages and stack traces are welcomed.

请补充如下信息。
> 期望的表现和实际的表现。（如有）
> 问题重现的步骤。（如有）
> Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

**Comment by LinJZong** [comment]
flutter的壳工程本身是可以直接接入的，就是有些功能可能无法正常使用，如组件检查之类的

**Comment by chzuliutao** [comment]
> Please complete the following informations.
> 
> > Expected behavior and actual behavior.
> > Steps to reproduce the problem.
> > Android or iOS? OS version? Brand?
> > More informations such as error messages and stack traces are welcomed.
> 
> 请补充如下信息。
> 
> > 期望的表现和实际的表现。（如有）
> > 问题重现的步骤。（如有）
> > Android 还是 iOS？系统版本是多少？手机品牌是什么？（如有）
> > 其他的错误信息和堆栈信息如果有也可以一并提供出来。（如有）

目前

> flutter的壳工程本身是可以直接接入的，就是有些功能可能无法正常使用，如组件检查之类的

在有接入的相关方案或者博客吗？如果方便的话建议在这个工程里补充flutter接入文档
