### ISSUE TITLE
希望增加安卓版本自定义功能支持导出性能数据

### ISSUE THREAD

**Issue by wholegale39** [didi/DoraemonKit#97]
1、问题描述：
中文版README.md中功能模块-性能监控-第6条有提到自定义功能，可以把性能监控数据导出至本地，但是我在安卓版本上-悬浮窗打开后，性能监控无自定义功能（QQ群2019.02.23号22:42我有咨询相关问题）
2、期望表现：
期望在安卓版本上性能监控增加自定义功能，导出性能监控数据，目前还不清楚你们导出的数据格式，期望可以使用导出数据做成html样式的性能报告

**Comment by wholegale39** [comment]
Hi，最近发现集成插件后，对安卓内存CPU损耗有点严重，比如应用后台运行时大概占用50M内存，进入前台内存占用大概在70M左右，然后再打开插件中的内存监控，整个应用内存占用直接到130M左右了，CPU类似，有没有办法进行优化？

**Comment by LinJZong** [comment]
> Hi，最近发现集成插件后，对安卓内存CPU损耗有点严重，比如应用后台运行时大概占用50M内存，进入前台内存占用大概在70M左右，然后再打开插件中的内存监控，整个应用内存占用直接到130M左右了，CPU类似，有没有办法进行优化？

读取CPU数据和内存数据本身会有一定消耗，后续考虑放到另一个进程处理；还有目前的实时图对于性能影响也比较大，后续会优化下表现形式

**Comment by wholegale39** [comment]
是否可以添加一个实时图形打开关闭的功能，这样的话，影响就减小很多

**Comment by yixiangboy** [comment]
请更新到最新版本 已经支持
